# coding: utf-8
"""
TypeORM Emitter - Sinh TypeORM entities cho NestJS backend.

Module nay chua TypeORMEmitter de render TypeORM entity files
tu DataModelCollection su dung Jinja2 templates.

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.emitters.core.cp08_database.models import (
    DataModel,
    DataModelCollection,
    ColumnDef,
    ColumnType,
    Relationship,
    Datasource,
    DatabaseEngine,
    SpatialColumn,
    SpatialIndex,
    TimeSeriesModel,
    RetentionPolicy,
    ReadModel,
    DistributedTransaction,
    TransactionParticipant,
    JSONBColumn,
    JSONBIndex,
)


# Mapping tu ColumnType sang TypeORM type
_TYPEORM_TYPE_MAP = {
    ColumnType.STRING: "String",
    ColumnType.INTEGER: "Int",
    ColumnType.BOOLEAN: "Boolean",
    ColumnType.DECIMAL: "Decimal",
    ColumnType.TEXT: "Text",
    ColumnType.JSON: "jsonb",
    ColumnType.DATETIME: "Date",
    ColumnType.UUID: "uuid",
    ColumnType.ARRAY: "simple-array",
    ColumnType.BYTES: "blob",
    ColumnType.TIME: "Time",
}


@dataclass
class TypeORMEmitter:
    """
    Emitter de sinh TypeORM entity files cho NestJS.

    Render models tu DataModelCollection sang TypeORM entity classes.
    KPI-029: Tenant isolation qua tenantId column.
    """

    def emit(
        self,
        collection: DataModelCollection,
        output_dir: Path,
    ) -> dict[str, str]:
        """
        Emit TypeORM entity files tu DataModelCollection.

        Args:
            collection: Collection chua cac data models
            output_dir: Directory de luu files

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}
        entities_dir = output_dir / "entities"
        entities_dir.mkdir(parents=True, exist_ok=True)

        if not collection.models:
            return files

        for model in collection.models:
            filename = f"{self._to_kebab_case(model.id)}.entity.ts"
            content = self._emit_entity_file(model)
            file_key = str((entities_dir / filename).relative_to(output_dir)).replace("\\", "/")
            files[file_key] = content

        # Sinh index.ts
        index_key = str((entities_dir / "index.ts").relative_to(output_dir)).replace("\\", "/")
        files[index_key] = self._emit_entities_index(collection)

        return files

    def _emit_entity_file(self, model: DataModel) -> str:
        """Sinh TypeORM entity file cho mot model."""
        lines: list[str] = []
        class_name = model.id
        table_name = self._to_kebab_case(model.table_name)

        lines.append(f"// KPI-029: Tenant Isolation: {model.tenant_isolated}")
        lines.append("")
        lines.append("import { Entity, Column, PrimaryGeneratedColumn, Index, ManyToOne, OneToMany, JoinTable } from 'typeorm';")
        lines.append("")
        lines.append(f"@Entity('{table_name}')")
        if model.tenant_isolated:
            lines.append("// KPI-029: Tenant isolated entity")
        lines.append(f"export class {class_name} {{")
        lines.append("")

        # Columns
        for col in model.columns:
            orm_type = _TYPEORM_TYPE_MAP.get(col.column_type, "String")
            col_name = self._to_camel_case(col.name)

            if col.primary_key:
                lines.append(f"  @PrimaryGeneratedColumn('{{{orm_type.lower()}}}')")
            else:
                opts = self._column_options(col)
                lines.append(f"  @Column({{{opts}}})")

            lines.append(f"  {col_name}!: {orm_type};")
            lines.append("")

        # Relationships
        for rel in model.relationships:
            rel_name = self._to_camel_case(rel.target_model.lower() + "_rel")
            lines.append(f"  @ManyToOne(() => {rel.target_model})")
            lines.append(f"  {rel_name}!: {rel.target_model};")
            lines.append("")

        lines.append("}")
        lines.extend(["", ""])
        return "\n".join(lines)

    def _column_options(self, col: ColumnDef) -> str:
        """Xay dung column options string."""
        opts: list[str] = []
        opts.append(f"type: '{_TYPEORM_TYPE_MAP.get(col.column_type, 'String').lower()}'")
        if col.required:
            opts.append("nullable: false")
        if col.unique:
            opts.append("unique: true")
        if col.max_length:
            opts.append(f"length: {col.max_length}")
        if col.tenant_aware:
            opts.append("// KPI-029: Tenant isolation")
        return ", ".join(opts)

    def _emit_entities_index(self, collection: DataModelCollection) -> str:
        """Sinh index.ts cho entities directory."""
        lines = ["// Entities index - auto-generated by Midicoder CE", ""]
        for model in collection.models:
            import_path = self._to_kebab_case(model.id) + ".entity"
            lines.append(f"export * from './{import_path}';")
        return "\n".join(lines)

    @staticmethod
    def _to_kebab_case(name: str) -> str:
        """Chuyen PascalCase sang kebab-case."""
        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1-\2", name)
        return re.sub("([a-z0-9])([A-Z])", r"\1-\2", s1).lower()

    def emit_connection_config(self, datasource: Datasource) -> dict[str, str]:
        """
        Sinh datasource.ts voi TypeORM config.

        Args:
            datasource: Datasource config de sinh connection code

        Returns:
            Dictionary {file_path: content}
        """
        lines: list[str] = []
        lines.append(f"// Database connection configuration - Auto-generated by Midicoder CE.")
        lines.append(f"// Datasource: {datasource.name}")
        lines.append(f"// Engine: {datasource.engine.value}")
        lines.append("")
        lines.append("import { DataSource } from 'typeorm';")
        lines.append("import { ConfigService } from '@nestjs/config';")
        lines.append("")
        lines.append("")
        lines.append("// TypeORM DataSource Config")
        lines.append("export const dataSourceOptions = {")
        lines.append(f"  type: '{datasource.engine.value}' as any,")
        lines.append(f"  url: process.env.{datasource.name.upper()}_URL || '{datasource.connection_string}',")
        lines.append(f"  pool_size: {datasource.pool_size},")
        lines.append(f"  max_overflow: {datasource.max_overflow},")
        lines.append(f"  socket_timeout: {datasource.pool_timeout * 1000},")
        lines.append("")
        lines.append("  synchronize: false,")
        lines.append("  logging: process.env.NODE_ENV !== 'production',")
        lines.append("")
        lines.append("  entities: [__dirname + '/**/*.entity{.ts,.js}'],")
        lines.append("  subscribers: [__dirname + '/**/*.subscriber{.ts,.js}'],")
        lines.append("  migrations: [__dirname + '/migrations/*{.ts,.js}'],")
        lines.append("};")
        lines.append("")
        lines.append("")
        lines.append("export const AppDataSource = new DataSource(dataSourceOptions);")
        lines.append("")
        lines.append("")
        lines.append("export async function initDataSource() {")
        lines.append("  if (!AppDataSource.isInitialized) {")
        lines.append("    await AppDataSource.initialize();")
        lines.append("  }")
        lines.append("  return AppDataSource;")
        lines.append("}")

        return {"datasource.ts": "\n".join(lines)}

    def emit_base_repository(self) -> dict[str, str]:
        """
        Sinh BaseEntityRepository voi CRUD + tenant isolation.

        Returns:
            Dictionary {file_path: content}
        """
        lines: list[str] = []
        lines.append("// Base Repository - CRUD base class với tenant isolation (KPI-029)")
        lines.append("// Auto-generated by Midicoder CE.")
        lines.append("")
        lines.append("import { EntityTarget, Repository } from 'typeorm';")
        lines.append("import { AppDataSource } from '../datasource';")
        lines.append("")
        lines.append("")
        lines.append("/**")
        lines.append(" * Base repository với CRUD operations và tenant isolation (KPI-029).")
        lines.append(" *")
        lines.append(" * Usage:")
        lines.append(" *   class UserRepository extends BaseEntityRepository<UserEntity> {")
        lines.append(" *     constructor() {")
        lines.append(" *       super(UserEntity);")
        lines.append(" *     }")
        lines.append(" *   }")
        lines.append(" */")
        lines.append("export abstract class BaseEntityRepository<T> {")
        lines.append("  protected repository: Repository<T>;")
        lines.append("")
        lines.append("  constructor(entityClass: EntityTarget<T>) {")
        lines.append("    this.repository = AppDataSource.getRepository(entityClass);")
        lines.append("  }")
        lines.append("")
        lines.append("  protected getRepo(): Repository<T> {")
        lines.append("    return this.repository;")
        lines.append("  }")
        lines.append("")
        lines.append("  async getById(id: string): Promise<T | null> {")
        lines.append("    return this.repository.findOne({ where: { id } as any });")
        lines.append("  }")
        lines.append("")
        lines.append("  async list(tenantId?: string): Promise<T[]> {")
        lines.append("    // KPI-029: Tu dong filter theo tenantId neu co")
        lines.append("    const where: any = {};")
        lines.append("    if (tenantId) {")
        lines.append("      where.tenantId = tenantId;")
        lines.append("    }")
        lines.append("    return this.repository.find({ where });")
        lines.append("  }")
        lines.append("")
        lines.append("  async create(entity: T): Promise<T> {")
        lines.append("    return this.repository.save(entity);")
        lines.append("  }")
        lines.append("")
        lines.append("  async update(id: string, data: Partial<T>): Promise<T | null> {")
        lines.append("    await this.repository.update(id, data);")
        lines.append("    return this.getById(id);")
        lines.append("  }")
        lines.append("")
        lines.append("  async delete(id: string): Promise<boolean> {")
        lines.append("    const result = await this.repository.delete(id);")
        lines.append("    return (result.affected ?? 0) > 0;")
        lines.append("  }")
        lines.append("}")

        return {"repositories/base-entity-repository.ts": "\n".join(lines)}

    def emit_migration(self, model: DataModel, version: str) -> dict[str, str]:
        """
        Sinh TypeORM migration file cho model.

        Args:
            model: DataModel de sinh migration
            version: Version revision ID

        Returns:
            Dictionary {file_path: content}
        """
        lines: list[str] = []
        lines.append(f"// Create {model.table_name} table")
        lines.append(f"// Revision: {version}")
        lines.append("")
        lines.append("import { MigrationInterface, QueryRunner, Table, TableIndex } from 'typeorm';")
        lines.append("")
        lines.append("")
        lines.append(f"export class Create{model.table_name}{version} implements MigrationInterface {{")
        lines.append("")
        lines.append("  public async up(queryRunner: QueryRunner): Promise<void> {")

        # Create table
        lines.append(f'    await queryRunner.createTable(new Table({{')
        lines.append(f'      name: "{model.table_name}",')
        lines.append('      columns: [')

        for col in model.columns:
            orm_type = _TYPEORM_TYPE_MAP.get(col.column_type, "varchar")
            col_name = TypeORMEmitter._to_camel_case(col.name)
            col_def = f'        new TableColumn({{ name: "{col_name}", type: "{orm_type}"'
            if col.primary_key:
                col_def += ', isPrimary: true'
            if col.required and not col.primary_key:
                col_def += ', isNullable: false'
            if col.unique:
                col_def += ', isUnique: true'
            if col.max_length and orm_type in ("varchar", "nvarchar"):
                col_def += f', length: {col.max_length}'
            col_def += '})'
            lines.append(col_def + ',')

        lines.append('      ],')
        lines.append('    }), true);')

        # Create indexes
        for idx in model.indexes:
            lines.append(f'    await queryRunner.createIndex(new TableIndex({{')
            lines.append(f'      name: "{idx.name}",')
            lines.append(f'      table: "table_name",')
            lines.append(f'      columnNames: {idx.columns},')
            lines.append(f'      isUnique: {idx.unique},')
            lines.append('    }), true);')

        lines.append('  }')
        lines.append('')
        lines.append('  public async down(queryRunner: QueryRunner): Promise<void> {')
        lines.append(f'    await queryRunner.dropTable("{model.table_name}");')
        lines.append('  }')
        lines.append('}')
        lines.append('')
        lines.append('export class CreateMigration implements MigrationInterface {')
        lines.append('  public async up(queryRunner: QueryRunner): Promise<void> {')
        lines.append('    await new CreateMigration().up(queryRunner);')
        lines.append('  }')
        lines.append('  public async down(queryRunner: QueryRunner): Promise<void> {')
        lines.append('    await new CreateMigration().down(queryRunner);')
        lines.append('  }')
        lines.append('}')

        filename = f"migrations/{version}-Create{model.table_name}.ts"
        return {filename: "\n".join(lines)}

    def emit_seed_data(self, entities: list[DataModel]) -> dict[str, str]:
        """
        Sinh TypeORM seed service.

        Args:
            entities: Danh sach entities de sinh seed data

        Returns:
            Dictionary {file_path: content}
        """
        lines: list[str] = []
        lines.append("// Seed data service - Auto-generated by Midicoder CE.")
        lines.append("")
        lines.append("import { AppDataSource } from '../datasource';")
        lines.append("")
        lines.append("")
        lines.append("/**")
        lines.append(" * Tao seed data cho cac bang.")
        lines.append(" */")
        lines.append("export class SeedService {")
        lines.append("  async seed(): Promise<void> {")
        lines.append("    const dataSource = await AppDataSource.initialize();")
        lines.append("")
        for entity in entities:
            lines.append(f"    // Seed data cho {entity.table_name}")
            lines.append(f'    console.log("Seeding {entity.table_name}...");')
            lines.append("")
        lines.append('    console.log("Seed data completed!");')
        lines.append('  }')
        lines.append('}')
        lines.append('')
        lines.append('')
        lines.append('async function main() {')
        lines.append('  const seedService = new SeedService();')
        lines.append('  await seedService.seed();')
        lines.append('}')
        lines.append('')
        lines.append('main();')

        return {"seed.ts": "\n".join(lines)}

    @staticmethod
    def _to_camel_case(name: str) -> str:
        """Chuyen snake_case sang camelCase."""
        parts = name.split("_")
        return parts[0] + "".join(p.capitalize() for p in parts[1:])

    # ------------------------------------------------------------------
    # Advanced Capabilities
    # ------------------------------------------------------------------

    def emit_spatial_columns(self, columns: list[SpatialColumn]) -> dict[str, str]:
        """Sinh PostGIS spatial decorators cho TypeORM."""
        lines: list[str] = []
        lines.append("// PostGIS Spatial Decorators — Auto-generated by Midicoder CE.")
        lines.append("// Obligation: All spatial columns must declare explicit SRID (default: 4326 WGS84)")
        lines.append("")
        lines.append("import { Column } from 'typeorm';")
        lines.append("")
        lines.append("")
        lines.append("// Obligation: All spatial columns must declare explicit SRID (default: 4326 WGS84)")
        lines.append("const DEFAULT_SRID = 4326;")
        lines.append("")
        lines.append("")

        for col in columns:
            srid_val = col.srid or 4326
            lines.append(f"// PostGIS {col.spatial_type.value} column (SRID={srid_val})")
            lines.append(f"// Usage:")
            lines.append(f"//   @Column('geometry', {{")
            lines.append(f"//     spatialFeatureType: '{col.spatial_type.value}',")
            lines.append(f"//     srid: {srid_val},")
            lines.append(f"//   }})")
            lines.append(f"//   {self._to_camel_case(col.name)}!: string;")
            lines.append("")

        lines.append("")
        lines.append("export function SpatialColumn(type: string, srid: number = DEFAULT_SRID) {")
        lines.append("  return Column({ type: 'geometry', spatialFeatureType: type, srid });")
        lines.append("}")

        return {"spatial/spatial.decorators.ts": "\n".join(lines)}

    def emit_spatial_index(self, indexes: list[SpatialIndex]) -> dict[str, str]:
        """Sinh spatial index migration cho TypeORM."""
        lines: list[str] = []
        lines.append("// Spatial Index Migration — Auto-generated by Midicoder CE.")
        lines.append("")
        lines.append("import { MigrationInterface, QueryRunner } from 'typeorm';")
        lines.append("")
        lines.append("")
        lines.append("export class CreateSpatialIndexes implements MigrationInterface {")
        lines.append("")
        lines.append("  public async up(queryRunner: QueryRunner): Promise<void> {")
        for idx in indexes:
            lines.append(f'    await queryRunner.query(`CREATE INDEX "{idx.name}" ON "{idx.column}_table" USING {idx.index_type.value} ("{idx.column}")`);')
        lines.append("  }")
        lines.append("")
        lines.append("  public async down(queryRunner: QueryRunner): Promise<void> {")
        for idx in indexes:
            lines.append(f'    await queryRunner.query(`DROP INDEX "{idx.name}"`);')
        lines.append("  }")
        lines.append("}")

        return {"spatial/spatial-indexes.ts": "\n".join(lines)}

    def emit_time_series_model(self, model: TimeSeriesModel) -> dict[str, str]:
        """Sinh time-series entity với partitioning cho TypeORM."""
        lines: list[str] = []
        lines.append(f"// Time-Series Entity: {model.id}")
        lines.append(f"// Timestamp Column: {model.timestamp_column}")
        lines.append(f"// Granularity: {model.granularity.value}")
        if model.retention_policy:
            lines.append(f"// Retention: {model.retention_policy.policy_type.value} — threshold={model.retention_policy.threshold}")
        lines.append("")
        lines.append("import { Entity, Column, PrimaryGeneratedColumn, Index } from 'typeorm';")
        lines.append("")
        lines.append(f"@Entity('{model.table_name}')")
        lines.append(f"// KPI: Time-series partitioned table")
        lines.append(f"// Timestamp column: {model.timestamp_column}")
        lines.append(f"export class {model.id} {{")
        lines.append("")
        lines.append(f"  @PrimaryGeneratedColumn('uuid')")
        lines.append(f"  id!: string;")
        lines.append("")
        lines.append(f"  @Column({{ type: 'timestamptz', nullable: false }})")
        lines.append(f"  @Index()")
        lines.append(f"  {self._to_camel_case(model.timestamp_column)}!: Date;")

        for vc in model.value_columns:
            lines.append("")
            lines.append(f"  @Column({{ type: 'float', nullable: true }})")
            lines.append(f"  {self._to_camel_case(vc)}!: number;")
        for gc in model.grain_columns:
            lines.append("")
            lines.append(f"  @Column({{ type: 'varchar', nullable: true }})")
            lines.append(f"  {self._to_camel_case(gc)}!: string;")

        if model.retention_policy:
            lines.append("")
            lines.append(f"  // Retention: {model.retention_policy.policy_type.value} — threshold={model.retention_policy.threshold}")

        lines.append("}")
        lines.append("")
        lines.append("")
        lines.append(f"# Migration: create hypertable for time-series partitioning")
        lines.append(f"#   SELECT create_hypertable('{model.table_name}', '{model.timestamp_column}',")
        lines.append(f"#       timescaledb.skip_custom_backfill := true,")
        lines.append(f"#       number_partitions := 4);")
        if model.retention_policy:
            lines.append(f"#   SELECT add_retention_policy('{model.table_name}', INTERVAL '{model.retention_policy.threshold} days');")

        filename = f"time_series/{self._to_kebab_case(model.table_name)}.entity.ts"
        return {filename: "\n".join(lines)}

    def emit_read_model(self, read_model: ReadModel) -> dict[str, str]:
        """Sinh CQRS read model cho TypeORM."""
        lines: list[str] = []
        lines.append(f"// CQRS Read Model: {read_model.id}")
        lines.append(f"// Source: {read_model.source.value}")
        lines.append(f"// Refresh: {read_model.refresh_strategy.value}")
        lines.append("")
        lines.append("import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';")
        lines.append("")
        lines.append(f"@Entity('{read_model.table_name}')")
        lines.append(f"// Read model — {read_model.source.value}")
        lines.append(f"// Refresh strategy: {read_model.refresh_strategy.value}")
        lines.append(f"// Source tables: {', '.join(read_model.source_models)}")
        lines.append(f"export class {read_model.id} {{")
        lines.append("")
        lines.append(f"  @PrimaryGeneratedColumn('uuid')")
        lines.append(f"  id!: string;")

        for col in read_model.columns:
            orm_type = _TYPEORM_TYPE_MAP.get(col.column_type, "String")
            nullable = "" if col.required else ", nullable: true"
            lines.append("")
            lines.append(f"  @Column({{ type: '{orm_type}'{nullable} }})")
            lines.append(f"  {self._to_camel_case(col.name)}!: {orm_type};")

        lines.append("")
        lines.append(f"  @Column({{ type: 'timestamptz', nullable: true }})")
        lines.append(f"  lastRefreshedAt!: Date | null;")

        lines.append("")
        lines.append(f"  static refreshStrategy = '{read_model.refresh_strategy.value}';")

        strategy = read_model.refresh_strategy.value
        if strategy == "real_time":
            lines.append(f"  // Real-time: triggered by event handler on every write")
        elif strategy == "batch":
            lines.append(f"  // Batch: scheduled CRON job")
        elif strategy == "lazy":
            lines.append(f"  // Lazy: refreshed on first read after staleness threshold")
        elif strategy == "event_driven":
            lines.append(f"  // Event-driven: triggered by domain events")

        lines.append("}")
        lines.append("")

        filename = f"read_models/{self._to_kebab_case(read_model.table_name)}.entity.ts"
        return {filename: "\n".join(lines)}

    def emit_distributed_transaction(self, tx: DistributedTransaction) -> dict[str, str]:
        """Sinh distributed transaction coordinator (Saga/2PC/Outbox/TCC)."""
        lines: list[str] = []
        lines.append(f"// Distributed Transaction: {tx.id}")
        lines.append(f"// Protocol: {tx.protocol.value}")
        lines.append(f"// Timeout: {tx.timeout_seconds}s")
        lines.append("")
        lines.append("import { Injectable } from '@nestjs/common';")
        lines.append("")
        lines.append("")

        if tx.protocol.value == "saga":
            lines.append(f"enum SagaStep {{")
            for p in tx.participants:
                step_name = p.role.upper().replace(" ", "_")
                lines.append(f"  {step_name} = '{p.role}',")
                lines.append(f"  {step_name}_COMPENSATE = '{p.role}_compensate',")
            lines.append("}")
            lines.append("")
            lines.append("")
            lines.append(f"@Injectable()")
            lines.append(f"export class {tx.id.replace('-', '_').title().replace('_', '')}Saga {{")
            lines.append(f"  // Saga orchestrator for '{tx.id}'.")
            lines.append(f"  // Participants: {len(tx.participants)}")
            lines.append(f"  // Timeout: {tx.timeout_seconds}s")
            lines.append("")
            lines.append(f"  async execute() {{")
            lines.append(f"    // Execute saga steps forward; on failure, compensate.")
            lines.append(f"    const steps = Object.values(SagaStep);")
            lines.append(f"    for (const step of steps) {{")
            lines.append(f"      try {{")
            lines.append(f"        await this.runStep(step);")
            lines.append(f"      }} catch (error) {{")
            lines.append(f"        await this.compensate(error);")
            lines.append(f"        return false;")
            lines.append(f"      }}")
            lines.append(f"    }}")
            lines.append(f"    return true;")
            lines.append(f"  }}")
            lines.append("")
            lines.append(f"  private async compensate(error: any) {{")
            lines.append(f"    // Execute compensation steps in reverse.")
            lines.append(f"  }}")
            lines.append(f"")
            lines.append(f"  private async runStep(step: string) {{")
            lines.append(f"    switch (step) {{")
            for p in tx.participants:
                step_name = p.role.upper().replace(" ", "_")
                lines.append(f"      case SagaStep.{step_name}:")
                lines.append(f"        break;")
            lines.append(f"      default:")
            lines.append(f"        break;")
            lines.append(f"    }}")
            lines.append(f"  }}")
            lines.append("}")

        elif tx.protocol.value == "two_phase_commit":
            lines.append(f"@Injectable()")
            lines.append(f"export class {tx.id.replace('-', '_').title().replace('_', '')}Coordinator {{")
            lines.append(f"  // Two-Phase Commit coordinator for '{tx.id}'.")
            lines.append("")
            lines.append(f"  async prepare(): Promise<Record<string, boolean>> {{")
            lines.append(f"    // Phase 1: ask all participants to prepare.")
            lines.append(f"    const results: Record<string, boolean> = {{}};")
            for p in tx.participants:
                lines.append(f"    results['{p.role}'] = await this.prepare_{p.role.replace(' ', '_')}();")
            lines.append(f"    return results;")
            lines.append(f"  }}")
            lines.append("")
            lines.append(f"  async commit(): Promise<boolean> {{")
            lines.append(f"    // Phase 2: commit all if all prepared.")
            lines.append(f"    return true;")
            lines.append(f"  }}")
            lines.append("")
            lines.append(f"  async abort(): Promise<boolean> {{")
            lines.append(f"    // Phase 2: abort all if any failed.")
            lines.append(f"    return true;")
            lines.append(f"  }}")
            lines.append("}")

        else:
            lines.append(f"export class {tx.id.replace('-', '_').title().replace('_', '')}Outbox {{")
            lines.append(f"  // Outbox pattern for '{tx.id}'.")
            lines.append("")
            lines.append(f"  @PrimaryGeneratedColumn('uuid')")
            lines.append(f"  id!: string;")
            lines.append("")
            lines.append(f"  @Column()")
            lines.append(f"  aggregateType!: string;")
            lines.append("")
            lines.append(f"  @Column()")
            lines.append(f"  aggregateId!: string;")
            lines.append("")
            lines.append(f"  @Column()")
            lines.append(f"  eventType!: string;")
            lines.append("")
            lines.append(f"  @Column({{ nullable: true }})")
            lines.append(f"  payload: string | null;")
            lines.append("")
            lines.append(f"  @Column({{ default: false }})")
            lines.append(f"  published: boolean;")
            lines.append("}")

        lines.append("")

        filename = f"transactions/{self._to_kebab_case(tx.id)}.ts"
        return {filename: "\n".join(lines)}

    def emit_jsonb_columns(self, columns: list[JSONBColumn]) -> dict[str, str]:
        """Sinh JSONB column decorators + GIN index cho TypeORM."""
        lines: list[str] = []
        lines.append("// JSONB Column Decorators — Auto-generated by Midicoder CE.")
        lines.append("")
        lines.append("import { Column, Index } from 'typeorm';")
        lines.append("")
        lines.append("")

        for col in columns:
            lines.append(f"// JSONB column: {col.name}")
            if col.validation_mode.value != "none":
                lines.append(f"// Validation: {col.validation_mode.value}")
            if col.jsonb_indexes:
                lines.append(f"// GIN Index: {len(col.jsonb_indexes)} indexes defined")
            lines.append(f"// Usage:")
            lines.append(f"//   @Column('jsonb')")
            for idx in col.jsonb_indexes:
                lines.append(f"//   @Index('{idx.name}', {{ unique: false, spatialIndex: false }})")
            lines.append(f"//   {self._to_camel_case(col.name)}!: any;")
            lines.append("")

        lines.append("")
        lines.append("export function JsonbColumn(options: any = {}) {")
        lines.append("  return Column('jsonb', options);")
        lines.append("}")
        lines.append("")
        lines.append("")
        lines.append("export function JsonbGinIndex(name: string) {")
        lines.append("  return Index(name, { unique: false });")
        lines.append("}")

        return {"jsonb/jsonb.decorators.ts": "\n".join(lines)}
