# coding: utf-8
"""
Elasticsearch Emitter - Sinh Elasticsearch config cho FastAPI backend.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.emitters.core.search.models import SearchCollection


@dataclass
class ElasticsearchEmitter:
    """Emitter de sinh Elasticsearch config cho FastAPI."""

    def emit(self, collection: SearchCollection, output_dir: Path) -> dict[str, str]:
        """Emit search files tu SearchCollection."""
        files: dict[str, str] = {}
        search_dir = output_dir / "search"
        search_dir.mkdir(parents=True, exist_ok=True)
        if not collection.indices:
            return files
        content = self._emit_index_config(collection)
        file_key = str((search_dir / "index_config.py").relative_to(output_dir)).replace("\\", "/")
        files[file_key] = content
        init_key = str((search_dir / "__init__.py").relative_to(output_dir)).replace("\\", "/")
        files[init_key] = '"""Search package - auto-generated by Midicoder CE."""\n'
        return files

    def _emit_index_config(self, collection: SearchCollection) -> str:
        """Sinh index_config.py."""
        lines = [
            "# coding: utf-8",
            '"""',
            "Search Index Configuration - Auto-generated by Midicoder CE.",
            "KPI-029: Tenant-aware search index isolation.",
            '"""',
            "",
        ]
        for index in collection.indices:
            lines.append(f"# Index: {index.id}")
            lines.append(f"INDEX_{index.id.upper()}_PROVIDER = '{index.provider.value}'")
            lines.append(f"INDEX_{index.id.upper()}_SYNC_STRATEGY = '{index.sync_strategy.value}'")
            lines.append(f"INDEX_{index.id.upper()}_SYNC_TRIGGER = '{index.sync_trigger.value}'")
            if index.tenant_isolated:
                lines.append("# KPI-029: Tenant isolated = True")
                lines.append(f"INDEX_{index.id.upper()}_TENANT_PREFIX = 'tenant:'")
            lines.append("")
            for col in index.columns:
                lines.append(f"  # Column: {col.name} ({col.column_type})")
            lines.append("")
        return "\n".join(lines)