# coding: utf-8
"""
SearchModule Emitter - Sinh SearchModule cho NestJS backend.

Module nay chua SearchModuleEmitter de render NestJS search module
tu SearchCollection su dung Jinja2 templates.

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.emitters.core.search.models import (
    SearchCollection,
    SearchIndex,
)


@dataclass
class SearchModuleEmitter:
    """
    Emitter de sinh SearchModule files cho NestJS.

    Render search module tu SearchCollection sang TypeScript files.
    KPI-029: Tenant isolation qua tenant-specific indices.
    """

    def emit(
        self,
        collection: SearchCollection,
        output_dir: Path,
    ) -> dict[str, str]:
        """
        Emit search module files tu SearchCollection.

        Args:
            collection: Collection chua search indices
            output_dir: Directory de luu files

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}
        search_dir = output_dir / "search"
        search_dir.mkdir(parents=True, exist_ok=True)

        if not collection.indices:
            return files

        content = self._emit_search_module(collection)
        file_key = str((search_dir / "search.module.ts").relative_to(output_dir)).replace("\\", "/")
        files[file_key] = content

        content = self._emit_search_service(collection)
        file_key = str((search_dir / "search.service.ts").relative_to(output_dir)).replace("\\", "/")
        files[file_key] = content

        return files

    def _emit_search_module(self, collection: SearchCollection) -> str:
        """Sinh search.module.ts."""
        lines = [
            "// SearchModule - Auto-generated by Midicoder CE",
            "// KPI-029: Tenant-aware search",
            "",
            "import { Module, Global } from '@nestjs/common';",
            "import { SearchService } from './search.service';",
            "",
            "@Global()",
            "@Module({",
            "  providers: [SearchService],",
            "  exports: [SearchService],",
            "})",
            "export class SearchModule {}",
            "",
        ]
        return "\n".join(lines)

    def _emit_search_service(self, collection: SearchCollection) -> str:
        """Sinh search.service.ts."""
        lines = [
            "// SearchService - Auto-generated by Midicoder CE",
            "// KPI-029: Tenant-aware search",
            "",
            "import { Injectable, Logger } from '@nestjs/common';",
            "import { Client } from '@elastic/elasticsearch';",
            "",
            "@Injectable()",
            "export class SearchService {",
            "  private readonly logger = new Logger(SearchService.name);",
            "  private readonly esClient: Client;",
            "",
            "  constructor() {",
            "    this.esClient = new Client({",
            "      node: process.env.ELASTICSEARCH_URL || 'http://localhost:9200',",
            "    });",
            "  }",
            "",
            "  // KPI-029: Tenant-aware index name building",
            "  private getIndexName(index: string, tenantId?: string): string {",
            "    return tenantId ? `${tenantId}_${index}` : index;",
            "  }",
            "",
            "  async search(index: string, query: string, tenantId?: string): Promise<unknown> {",
            "    const indexName = this.getIndexName(index, tenantId);",
            "    return this.esClient.search({ index: indexName, body: { query: { match: { _all: query } } } });",
            "  }",
            "",
            "  async indexDocument(index: string, id: string, doc: unknown, tenantId?: string): Promise<void> {",
            "    const indexName = this.getIndexName(index, tenantId);",
            "    await this.esClient.index({ index: indexName, id, body: doc });",
            "  }",
            "",
            "  async deleteDocument(index: string, id: string, tenantId?: string): Promise<void> {",
            "    const indexName = this.getIndexName(index, tenantId);",
            "    await this.esClient.delete({ index: indexName, id });",
            "  }",
            "}",
            "",
        ]
        return "\n".join(lines)