# coding: utf-8
"""
FastAPI Tenant Emitter — Sinh tenant middleware, context, router cho FastAPI.

Module nay chua FastAPITenantEmitter de emit cac file:
- app/core/security/tenant_middleware.py: Tenant identification middleware
- app/core/security/tenant_context.py: Tenant context management
- app/core/security/tenant_router.py: Tenant provisioning endpoints

KPI-029: Tenant Isolation — bat buoc tenant context cho moi request.

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from midicoder.emitters.core.tenant.models import TenantConfig, TenantMode

DOC = '"""'


class FastAPITenantEmitter:
    """
    Emitter de sinh tenant-related files cho FastAPI backend.

    Generate middleware, context, va provisioning router theo TenantMode.
    """

    def emit(self, config: TenantConfig) -> dict[str, str]:
        """
        Emit tat ca tenant files cho FastAPI.

        Args:
            config: TenantConfig chua cau hinh isolation strategy

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}
        files["app/core/security/tenant_context.py"] = self._emit_context(config)
        files["app/core/security/tenant_middleware.py"] = self._emit_middleware(config)
        files["app/core/security/tenant_router.py"] = self._emit_router(config)
        return files

    def _emit_context(self, config: TenantConfig) -> str:
        """Sinh tenant_context.py — Tenant context management."""
        lines = [
            DOC,
            "Tenant Context Management — Auto-generated by Midicoder CE.",
            "",
            "Quan ly tenant context trong request lifecycle.",
            "KPI-029: Tenant Isolation enforced.",
            DOC,
            "",
            "from contextvars import ContextVar",
            "from typing import Optional",
            "from .tenant_models import TenantContext, TenantMode",
            "",
            "# Context variables cho tenant",
            '_tenant_id_var: ContextVar[Optional[str]] = ContextVar("tenant_id", default=None)',
            '_user_id_var: ContextVar[Optional[str]] = ContextVar("user_id", default=None)',
            '_mode_var: ContextVar[TenantMode] = ContextVar("tenant_mode", default=TenantMode.' + config.mode.value.upper() + ')',
            "",
            "def get_tenant_id() -> Optional[str]:",
            '    """Lay tenant ID tu current context."""',
            "    return _tenant_id_var.get()",
            "",
            "def set_tenant_id(tenant_id: str) -> None:",
            '    """Set tenant ID vao current context."""',
            "    _tenant_id_var.set(tenant_id)",
            "",
            "def get_user_id() -> Optional[str]:",
            '    """Lay user ID tu current context."""',
            "    return _user_id_var.get()",
            "",
            "def set_user_id(user_id: str) -> None:",
            '    """Set user ID vao current context."""',
            "    _user_id_var.set(user_id)",
            "",
            "def get_tenant_mode() -> TenantMode:",
            '    """Lay tenant mode hien tai."""',
            "    return _mode_var.get()",
            "",
            "def clear_context() -> None:",
            '    """Xoa toan bo tenant context."""',
            "    _tenant_id_var.set(None)",
            "    _user_id_var.set(None)",
        ]
        return "\n".join(lines)

    def _emit_middleware(self, config: TenantConfig) -> str:
        """Sinh tenant_middleware.py — Tenant identification middleware."""
        mode = config.mode.value
        domain = config.domain
        default_id = config.default_tenant_id
        prefix = config.schema_prefix

        if config.mode == TenantMode.SCHEMA:
            resolve_block = (
                '        # SCHEMA mode: Resolve tenant va switch schema\n'
                '        tenant_id = headers.get("X-Tenant-ID")\n'
                '        if not tenant_id:\n'
                '            tenant_id = conn.scope.get("state", {}).get("jwt_tenant_id")\n'
                '        if not tenant_id:\n'
                '            host = conn.scope.get("server", ("",))[0]\n'
                '            tenant_id = resolver.resolve(headers=dict(headers), host=host)\n'
                '        if tenant_id:\n'
                '            set_tenant_id(tenant_id)\n'
                '            schema_name = prefix + tenant_id\n'
                '            async with conn.app.state.db.engine.begin() as conn_db:\n'
                '                await conn_db.execute(text(f"SET search_path TO " + schema_name))\n'
            )
        elif config.mode == TenantMode.SUBDOMAIN:
            resolve_block = (
                '        # SUBDOMAIN mode: Resolve tenant tu subdomain\n'
                '        host = conn.scope.get("server", ("",))[0]\n'
                '        tenant_id = resolver.resolve(\n'
                '            headers=dict(headers),\n'
                '            jwt_claims=conn.scope.get("state", {}).get("jwt_claims", {}),\n'
                '            host=host,\n'
                '        )\n'
                '        if tenant_id:\n'
                '            set_tenant_id(tenant_id)\n'
            )
        else:
            resolve_block = (
                '        # ROW mode: Resolve tenant ID va set context\n'
                '        tenant_id = headers.get("X-Tenant-ID")\n'
                '        if not tenant_id:\n'
                '            jwt_claims = conn.scope.get("state", {}).get("jwt_claims", {})\n'
                '            tenant_id = jwt_claims.get("tenant_id", "")\n'
                '        if not tenant_id:\n'
                '            host = conn.scope.get("server", ("",))[0]\n'
                '            tenant_id = resolver.resolve(\n'
                '                headers=dict(headers),\n'
                '                jwt_claims=jwt_claims,\n'
                '                host=host,\n'
                '            )\n'
                '        if tenant_id:\n'
                '            set_tenant_id(tenant_id)\n'
            )

        q3 = '"""'
        return (
            f'{q3}\n'
            f'Tenant Identification Middleware — Auto-generated by Midicoder CE.\n'
            f'\n'
            f'Trich tenant ID tu request (header/JWT/subdomain) va set vao context.\n'
            f'Mode: {mode} | KPI-029: Tenant Isolation enforced.\n'
            f'{q3}\n'
            '\n'
            'from __future__ import annotations\n'
            '\n'
            'from starlette.middleware.base import BaseHTTPMiddleware\n'
            'from starlette.requests import Request\n'
            'from starlette.responses import Response\n'
            'from starlette.status import HTTP_400_BAD_REQUEST\n'
            'import json\n'
            '\n'
            'from .tenant_context import get_tenant_id, set_tenant_id, set_user_id\n'
            'from .tenant_models import TenantResolver\n'
            '\n'
            '# Resolver singleton\n'
            f'resolver = TenantResolver(\n'
            f'    domain="{domain}",\n'
            f'    default_tenant_id="{default_id}",\n'
            f')\n'
            '\n'
            '\n'
            'class TenantMiddleware(BaseHTTPMiddleware):\n'
            f'    {q3}Middleware de identify va enforce tenant context cho moi request.{q3}\n'
            '\n'
            '    async def dispatch(self, request: Request, call_next) -> Response:\n'
            '        # Bypass cho health check va docs\n'
            '        if request.url.path in ["/health", "/docs", "/redoc", "/openapi.json", "/"]:\n'
            '            response = await call_next(request)\n'
            '            return response\n'
            '\n'
            '        headers = dict(request.headers)\n'
            '\n'
            '        try:\n'
            + resolve_block +
            '        except Exception as e:\n'
            '            return Response(\n'
            '                content=json.dumps({"error": "Tenant ID khong the resolve: " + str(e)}),\n'
            '                status_code=HTTP_400_BAD_REQUEST,\n'
            '                media_type="application/json",\n'
            '            )\n'
            '\n'
            '        response = await call_next(request)\n'
            '\n'
            '        current_tenant = get_tenant_id()\n'
            '        if current_tenant:\n'
            '            response.headers["X-Tenant-ID"] = current_tenant\n'
            '\n'
            '        return response\n'
        )

    def _emit_router(self, config: TenantConfig) -> str:
        """Sinh tenant_router.py — Tenant provisioning endpoints."""
        mode = config.mode.value
        prefix = config.schema_prefix
        q3 = '"""'

        return (
            f'{q3}\n'
            f'Tenant Provisioning Router — Auto-generated by Midicoder CE.\n'
            f'\n'
            f'Endpoints cho tenant management:\n'
            f'- POST /api/tenants: Tao tenant moi\n'
            f'- GET /api/tenants/{{tenant_id}}: Lay thong tin tenant\n'
            f'- GET /api/tenants: Liet ke tenants (admin chi)\n'
            f'\n'
            f'Mode: {mode} | KPI-029: Tenant Isolation.\n'
            f'{q3}\n'
            '\n'
            'from fastapi import APIRouter, HTTPException, Depends\n'
            'from typing import Optional\n'
            '\n'
            'router = APIRouter(prefix="/api/tenants", tags=["tenants"])\n'
            '\n'
            '\n'
            '@router.post("")\n'
            'async def create_tenant(\n'
            '    tenant_id: str,\n'
            '    name: str,\n'
            f'    mode: str = "{mode}",\n'
            '):\n'
            f'    {q3}Tao tenant moi voi provisioning tu dong.{q3}\n'
            '    if mode == "schema":\n'
            f'        schema_name = "{prefix}" + tenant_id\n'
            '        # execute: CREATE SCHEMA IF NOT EXISTS schema_name\n'
            '        pass\n'
            '    elif mode == "subdomain":\n'
            '        # Cau hinh subdomain cho tenant\n'
            '        pass\n'
            '    # ROW mode: khong can provisioning\n'
            '\n'
            '    return {"tenant_id": tenant_id, "name": name, "status": "active", "mode": mode}\n'
            '\n'
            '\n'
            '@router.get("/{tenant_id}")\n'
            'async def get_tenant(tenant_id: str):\n'
            f'    {q3}Lay thong tin tenant theo ID.{q3}\n'
            f'    return {{"tenant_id": tenant_id, "mode": "{mode}", "status": "active"}}\n'
            '\n'
            '\n'
            '@router.get("")\n'
            'async def list_tenants():\n'
            f'    {q3}Liet ke toan bo tenants (admin chi).{q3}\n'
            '    return [{"tenant_id": "example", "status": "active"}]\n'
        )
