# coding: utf-8
"""
React Tenant Emitter — Sinh TenantContext, TenantProvider, useTenant hook cho React.

Module nay chua ReactTenantEmitter de emit cac file:
- src/app/core/tenant/TenantContext.ts: React Context cho tenant
- src/app/core/tenant/TenantProvider.tsx: Provider component
- src/app/core/tenant/useTenant.ts: Custom hook

KPI-029: Tenant Isolation — bat buoc tenant context cho moi request.

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from midicoder.emitters.core.tenant.models import TenantConfig, TenantMode

_TRIPLE = "'''"


class ReactTenantEmitter:
    """
    Emitter de sinh tenant-related files cho React frontend.

    Generate Context, Provider, va Hook theo TenantMode.
    """

    def emit(self, config: TenantConfig) -> dict[str, str]:
        """
        Emit tat ca tenant files cho React.

        Args:
            config: TenantConfig chua cau hinh isolation strategy

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}
        files["src/app/core/tenant/TenantContext.ts"] = self._emit_context(config)
        files["src/app/core/tenant/TenantProvider.tsx"] = self._emit_provider(config)
        files["src/app/core/tenant/useTenant.ts"] = self._emit_hook(config)
        return files

    def _emit_context(self, config: TenantConfig) -> str:
        """Sinh TenantContext.ts — React Context."""
        return f'''{_TRIPLE}
Tenant Context — Auto-generated by Midicoder CE.

React Context cho tenant management.
Mode: {config.mode.value} | KPI-029: Tenant Isolation.
{_TRIPLE}

import {{ createContext, useContext, ReactNode }} from 'react';

export interface TenantInfo {{
  id: string;
  name?: string;
  mode: '{config.mode.value}' | 'schema' | 'row' | 'subdomain';
}}

export interface TenantContextType {{
  tenant: TenantInfo | null;
  setTenant: (tenant: TenantInfo) => void;
  clearTenant: () => void;
  hasTenant: boolean;
}}

export const TenantContext = createContext<TenantContextType | undefined>(undefined);

export interface TenantProviderProps {{
  children: ReactNode;
}}
'''

    def _emit_provider(self, config: TenantConfig) -> str:
        """Sinh TenantProvider.tsx — Provider Component."""
        return f'''{_TRIPLE}
Tenant Provider — Auto-generated by Midicoder CE.

Provider component cho tenant state management.
Mode: {config.mode.value} | KPI-029: Tenant Isolation.
{_TRIPLE}

import {{ useState, useCallback, useMemo }} from 'react';
import {{ TenantContext, TenantInfo, TenantProviderProps }} from './TenantContext';

const STORAGE_KEY = 'midicoder_tenant_id';

export function TenantProvider({{ children }}: TenantProviderProps) {{
  const [tenant, setTenantState] = useState<TenantInfo | null>(null);

  // Load tenant tu localStorage khi mount
  useState(() => {{
    const storedId = localStorage.getItem(STORAGE_KEY);
    if (storedId) {{
      setTenantState({{ id: storedId, mode: '{config.mode.value}' }});
    }}
  }});

  const setTenant = useCallback((newTenant: TenantInfo) => {{
    setTenantState(newTenant);
    localStorage.setItem(STORAGE_KEY, newTenant.id);
  }}, []);

  const clearTenant = useCallback(() => {{
    setTenantState(null);
    localStorage.removeItem(STORAGE_KEY);
  }}, []);

  const hasTenant = !!tenant;

  const value = useMemo(
    () => ({{ tenant, setTenant, clearTenant, hasTenant }}),
    [tenant, setTenant, clearTenant, hasTenant],
  );

  return (
    <TenantContext.Provider value={{value}}>
      {{children}}
    </TenantContext.Provider>
  );
}}
'''

    def _emit_hook(self, config: TenantConfig) -> str:
        """Sinh useTenant.ts — Custom Hook."""
        return f'''{_TRIPLE}
useTenant Hook — Auto-generated by Midicoder CE.

Custom hook de truy cap tenant context.
Mode: {config.mode.value} | KPI-029: Tenant Isolation.
{_TRIPLE}

import {{ useContext }} from 'react';
import {{ TenantContext, TenantContextType }} from './TenantContext';

export function useTenant(): TenantContextType {{
  const context = useContext(TenantContext);

  if (context === undefined) {{
    throw new Error('useTenant must be used within a TenantProvider');
  }}

  return context;
}}

/** Hook de lay tenant ID nhanh */
export function useTenantId(): string | null {{
  const {{ tenant }} = useTenant();
  return tenant?.id ?? null;
}}
'''