"""
Query utilities for accessing and filtering indexed context data.

This module provides helper functions to load, search, and filter the context
files generated by the indexing process. It implements the query tools
described in Section 5-6 of the technical documentation.

Examples:
    Load all symbols and search for User-related items:
    
        from midicoder.context.query import load_symbols, search_symbols
        
        symbols = load_symbols('.midicoder/context')
        user_symbols = search_symbols(r'User', symbols)
        
    Filter exemplars by kind:
    
        from midicoder.context.query import load_exemplars, filter_exemplars_by_kind
        
        exemplars = load_exemplars('.midicoder/context')
        handlers = filter_exemplars_by_kind('command_handler', exemplars)
        
    Get all entry points:
    
        from midicoder.context.query import load_entrypoints
        
        entrypoints = load_entrypoints('.midicoder/context')
"""

import fnmatch
import json
import re
from difflib import unified_diff
from pathlib import Path
from typing import Any, Dict, List, Optional

# Type aliases for better readability
Symbol = Dict[str, Any]
EntryPoint = Dict[str, Any]
Seam = Dict[str, Any]
Exemplar = Dict[str, Any]
Profile = Dict[str, Any]
Manifest = Dict[str, Any]


def load_symbols(context_dir: str = ".midicoder/context") -> List[Symbol]:
    """
    Load all symbols from symbols.json.

    Args:
        context_dir: Path to the context directory (default: .midicoder/context)

    Returns:
        List of symbol dictionaries containing name, kind, file, line, signature

    Example:
        >>> symbols = load_symbols()
        >>> print(f"Total symbols: {len(symbols)}")
        >>> print(f"First symbol: {symbols[0]['name']}")
    """
    symbols_path = Path(context_dir) / "symbols.json"

    if not symbols_path.exists():
        return []

    with open(symbols_path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_entrypoints(context_dir: str = ".midicoder/context") -> List[EntryPoint]:
    """
    Load all entry points from entrypoints.json.

    Args:
        context_dir: Path to the context directory (default: .midicoder/context)

    Returns:
        List of entry point dictionaries containing kind, file, line, detail

    Example:
        >>> entrypoints = load_entrypoints()
        >>> for ep in entrypoints:
        ...     print(f"{ep['kind']}: {ep['file']}")
    """
    entrypoints_path = Path(context_dir) / "entrypoints.json"

    if not entrypoints_path.exists():
        return []

    with open(entrypoints_path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_seams(context_dir: str = ".midicoder/context") -> List[Seam]:
    """
    Load all seams from seams.json.

    Args:
        context_dir: Path to the context directory (default: .midicoder/context)

    Returns:
        List of seam dictionaries containing kind, file, line, detail, group_id, paired

    Example:
        >>> seams = load_seams()
        >>> paired_seams = [s for s in seams if s.get('paired')]
    """
    seams_path = Path(context_dir) / "seams.json"

    if not seams_path.exists():
        return []

    with open(seams_path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_exemplars(context_dir: str = ".midicoder/context") -> List[Exemplar]:
    """
    Load all exemplars from exemplars.json.

    Args:
        context_dir: Path to the context directory (default: .midicoder/context)

    Returns:
        List of exemplar dictionaries containing kind, file, line, snippet, score

    Example:
        >>> exemplars = load_exemplars()
        >>> handlers = [e for e in exemplars if e['kind'] == 'command_handler']
    """
    exemplars_path = Path(context_dir) / "exemplars.json"

    if not exemplars_path.exists():
        return []

    with open(exemplars_path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_profile(context_dir: str = ".midicoder/context") -> Optional[Profile]:
    """
    Load project profile from profile.json.

    Args:
        context_dir: Path to the context directory (default: .midicoder/context)

    Returns:
        Profile dictionary containing language, framework, orm, di_style, etc.
        Returns None if profile doesn't exist.

    Example:
        >>> profile = load_profile()
        >>> if profile:
        ...     print(f"Language: {profile['language']}")
        ...     print(f"Frameworks: {', '.join(profile['framework'])}")
    """
    profile_path = Path(context_dir) / "profile.json"

    if not profile_path.exists():
        return None

    with open(profile_path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_manifest(context_dir: str = ".midicoder/context") -> Optional[Manifest]:
    """
    Load indexing manifest from manifest.json.

    Args:
        context_dir: Path to the context directory (default: .midicoder/context)

    Returns:
        Manifest dictionary containing indexed_at, repo_hash, tool_version, etc.
        Returns None if manifest doesn't exist.

    Example:
        >>> manifest = load_manifest()
        >>> if manifest:
        ...     print(f"Indexed at: {manifest['indexed_at']}")
        ...     print(f"Files indexed: {manifest['file_count']}")
    """
    manifest_path = Path(context_dir) / "manifest.json"

    if not manifest_path.exists():
        return None

    with open(manifest_path, "r", encoding="utf-8") as f:
        return json.load(f)


def search_symbols(
    pattern: str,
    symbols: List[Symbol],
    case_sensitive: bool = False,
    use_regex: bool = True,
) -> List[Symbol]:
    """
    Search symbols by name pattern.

    Args:
        pattern: Search pattern (regex by default, or plain string)
        symbols: List of symbols to search
        case_sensitive: Whether to match case (default: False)
        use_regex: Whether pattern is regex (default: True)

    Returns:
        List of matching symbols

    Example:
        >>> symbols = load_symbols()
        >>> # Find all User-related symbols
        >>> user_symbols = search_symbols(r'User', symbols)
        >>> # Find all handlers (case insensitive)
        >>> handlers = search_symbols(r'handler', symbols, case_sensitive=False)
        >>> # Plain string search
        >>> exact = search_symbols('UserService', symbols, use_regex=False)
    """
    flags = 0 if case_sensitive else re.IGNORECASE

    if use_regex:
        compiled_pattern = re.compile(pattern, flags)
        return [s for s in symbols if compiled_pattern.search(s.get("name", ""))]
    else:
        if case_sensitive:
            return [s for s in symbols if pattern in s.get("name", "")]
        else:
            pattern_lower = pattern.lower()
            return [s for s in symbols if pattern_lower in s.get("name", "").lower()]


def filter_symbols_by_kind(kind: str, symbols: List[Symbol]) -> List[Symbol]:
    """
    Filter symbols by their kind (class, function, method, etc.).

    Args:
        kind: Symbol kind to filter (e.g., 'class', 'function', 'method')
        symbols: List of symbols to filter

    Returns:
        List of symbols matching the kind

    Example:
        >>> symbols = load_symbols()
        >>> classes = filter_symbols_by_kind('class', symbols)
        >>> functions = filter_symbols_by_kind('function', symbols)
    """
    return [s for s in symbols if s.get("kind") == kind]


def filter_symbols_by_file(
    file_pattern: str, symbols: List[Symbol], use_fnmatch: bool = True
) -> List[Symbol]:
    """
    Filter symbols by file path pattern.

    Args:
        file_pattern: File pattern (supports wildcards if use_fnmatch=True)
        symbols: List of symbols to filter
        use_fnmatch: Use fnmatch for wildcard matching (default: True)

    Returns:
        List of symbols from matching files

    Example:
        >>> symbols = load_symbols()
        >>> # Get all symbols from models directory
        >>> model_symbols = filter_symbols_by_file('*/models/*', symbols)
        >>> # Get symbols from specific file
        >>> user_file = filter_symbols_by_file('app/user.py', symbols, use_fnmatch=False)
    """
    if use_fnmatch:
        return [s for s in symbols if fnmatch.fnmatch(s.get("file", ""), file_pattern)]
    else:
        return [s for s in symbols if s.get("file", "") == file_pattern]


def filter_exemplars_by_kind(kind: str, exemplars: List[Exemplar]) -> List[Exemplar]:
    """
    Filter exemplars by their kind.

    Args:
        kind: Exemplar kind to filter (e.g., 'command_handler', 'repository', 'workflow')
        exemplars: List of exemplars to filter

    Returns:
        List of exemplars matching the kind

    Example:
        >>> exemplars = load_exemplars()
        >>> handlers = filter_exemplars_by_kind('command_handler', exemplars)
        >>> repos = filter_exemplars_by_kind('repository', exemplars)
    """
    return [e for e in exemplars if e.get("kind") == kind]


def filter_exemplars_by_file(
    file_pattern: str, exemplars: List[Exemplar], use_fnmatch: bool = True
) -> List[Exemplar]:
    """
    Filter exemplars by file path pattern.

    Args:
        file_pattern: File pattern (supports wildcards if use_fnmatch=True)
        exemplars: List of exemplars to filter
        use_fnmatch: Use fnmatch for wildcard matching (default: True)

    Returns:
        List of exemplars from matching files

    Example:
        >>> exemplars = load_exemplars()
        >>> api_exemplars = filter_exemplars_by_file('*/api/*', exemplars)
    """
    if use_fnmatch:
        return [
            e for e in exemplars if fnmatch.fnmatch(e.get("file", ""), file_pattern)
        ]
    else:
        return [e for e in exemplars if e.get("file", "") == file_pattern]


def get_context_slice(
    symbols: List[Symbol], limit: int = 10, offset: int = 0
) -> List[Symbol]:
    """
    Get a slice of symbols for context injection into LLM prompts.

    Args:
        symbols: List of symbols to slice
        limit: Maximum number of symbols to return (default: 10)
        offset: Starting position (default: 0)

    Returns:
        Sliced list of symbols

    Example:
        >>> symbols = load_symbols()
        >>> # Get first 10 symbols
        >>> context = get_context_slice(symbols, limit=10)
        >>> # Get next 10 symbols
        >>> next_context = get_context_slice(symbols, limit=10, offset=10)
    """
    return symbols[offset : offset + limit]


def compare_contexts(
    old_context_dir: str, new_context_dir: str, file_name: str = "symbols.json"
) -> List[str]:
    """
    Compare two context snapshots and return diff.

    Uses difflib to generate unified diff between old and new context files.

    Args:
        old_context_dir: Path to old context directory
        new_context_dir: Path to new context directory
        file_name: Name of the file to compare (default: symbols.json)

    Returns:
        List of diff lines

    Example:
        >>> diff = compare_contexts('.midicoder/context.old', '.midicoder/context')
        >>> for line in diff:
        ...     print(line)
    """
    old_path = Path(old_context_dir) / file_name
    new_path = Path(new_context_dir) / file_name

    if not old_path.exists() or not new_path.exists():
        return []

    with open(old_path, "r", encoding="utf-8") as f:
        old_lines = f.readlines()

    with open(new_path, "r", encoding="utf-8") as f:
        new_lines = f.readlines()

    diff = unified_diff(
        old_lines, new_lines, fromfile=str(old_path), tofile=str(new_path), lineterm=""
    )

    return list(diff)


def find_symbols_in_context(
    query: str,
    context_dir: str = ".midicoder/context",
    kinds: Optional[List[str]] = None,
    file_patterns: Optional[List[str]] = None,
    limit: int = 10,
) -> List[Symbol]:
    """
    Comprehensive search across symbols with multiple filters.

    This is a convenience function that combines loading and filtering.

    Args:
        query: Search pattern for symbol names (regex)
        context_dir: Path to context directory
        kinds: Optional list of symbol kinds to include
        file_patterns: Optional list of file patterns to include
        limit: Maximum results to return

    Returns:
        List of matching symbols

    Example:
        >>> # Find User-related classes in models directory
        >>> results = find_symbols_in_context(
        ...     r'User',
        ...     kinds=['class'],
        ...     file_patterns=['*/models/*'],
        ...     limit=5
        ... )
    """
    symbols = load_symbols(context_dir)

    # Apply name search
    if query:
        symbols = search_symbols(query, symbols)

    # Apply kind filter
    if kinds:
        symbols = [s for s in symbols if s.get("kind") in kinds]

    # Apply file pattern filter
    if file_patterns:
        filtered = []
        for pattern in file_patterns:
            filtered.extend(filter_symbols_by_file(pattern, symbols))
        symbols = filtered

    # Apply limit
    return get_context_slice(symbols, limit=limit)


def get_symbol_context_for_llm(
    query: str, context_dir: str = ".midicoder/context", max_symbols: int = 10
) -> str:
    """
    Format symbol context for LLM prompt injection.

    Args:
        query: Search pattern for relevant symbols
        context_dir: Path to context directory
        max_symbols: Maximum symbols to include

    Returns:
        Formatted string ready for LLM prompt

    Example:
        >>> context = get_symbol_context_for_llm(r'User', max_symbols=5)
        >>> prompt = f"Given this codebase context:\\n{context}\\nPlease generate..."
    """
    symbols = find_symbols_in_context(query, context_dir, limit=max_symbols)

    if not symbols:
        return "No relevant symbols found."

    lines = ["# Relevant Symbols\n"]
    for sym in symbols:
        kind = sym.get("kind", "unknown")
        name = sym.get("name", "unknown")
        file = sym.get("file", "unknown")
        line = sym.get("line", 0)
        signature = sym.get("signature", "")

        lines.append(f"- {kind} `{name}` in {file}:{line}")
        if signature:
            lines.append(f"  ```\n  {signature}\n  ```")

    return "\n".join(lines)


def get_exemplar_context_for_llm(
    kind: str, context_dir: str = ".midicoder/context", max_exemplars: int = 3
) -> str:
    """
    Format exemplar snippets for LLM prompt injection.

    Args:
        kind: Type of exemplar (e.g., 'command_handler', 'repository')
        context_dir: Path to context directory
        max_exemplars: Maximum exemplars to include

    Returns:
        Formatted string with code snippets

    Example:
        >>> context = get_exemplar_context_for_llm('command_handler', max_exemplars=2)
        >>> prompt = f"Follow these examples:\\n{context}\\nNow generate..."
    """
    exemplars = load_exemplars(context_dir)
    filtered = filter_exemplars_by_kind(kind, exemplars)[:max_exemplars]

    if not filtered:
        return f"No exemplars found for kind: {kind}"

    lines = [f"# Example {kind} patterns\n"]
    for i, ex in enumerate(filtered, 1):
        file = ex.get("file", "unknown")
        line_start = ex.get("line", 0)
        snippet = ex.get("snippet", "")

        lines.append(f"## Example {i} ({file}:{line_start})")
        lines.append(f"```\n{snippet}\n```\n")

    return "\n".join(lines)


def load_all_context(context_dir: str = ".midicoder/context") -> Dict[str, Any]:
    """
    Load all context files into a single dictionary.

    Args:
        context_dir: Path to context directory

    Returns:
        Dictionary with all context data

    Example:
        >>> context = load_all_context()
        >>> print(f"Language: {context['profile']['language']}")
        >>> print(f"Symbols: {len(context['symbols'])}")
        >>> print(f"Entry points: {len(context['entrypoints'])}")
    """
    return {
        "profile": load_profile(context_dir),
        "symbols": load_symbols(context_dir),
        "entrypoints": load_entrypoints(context_dir),
        "seams": load_seams(context_dir),
        "exemplars": load_exemplars(context_dir),
        "manifest": load_manifest(context_dir),
    }


def get_stats(context_dir: str = ".midicoder/context") -> Dict[str, Any]:
    """
    Get statistics about the indexed context.

    Args:
        context_dir: Path to context directory

    Returns:
        Dictionary with statistics

    Example:
        >>> stats = get_stats()
        >>> print(f"Total symbols: {stats['symbol_count']}")
        >>> print(f"Classes: {stats['classes']}")
        >>> print(f"Functions: {stats['functions']}")
    """
    symbols = load_symbols(context_dir)
    exemplars = load_exemplars(context_dir)
    entrypoints = load_entrypoints(context_dir)
    seams = load_seams(context_dir)

    symbol_kinds = {}
    for sym in symbols:
        kind = sym.get("kind", "unknown")
        symbol_kinds[kind] = symbol_kinds.get(kind, 0) + 1

    exemplar_kinds = {}
    for ex in exemplars:
        kind = ex.get("kind", "unknown")
        exemplar_kinds[kind] = exemplar_kinds.get(kind, 0) + 1

    return {
        "symbol_count": len(symbols),
        "symbol_kinds": symbol_kinds,
        "classes": symbol_kinds.get("class", 0),
        "functions": symbol_kinds.get("function", 0),
        "methods": symbol_kinds.get("method", 0),
        "entrypoint_count": len(entrypoints),
        "seam_count": len(seams),
        "paired_seams": len([s for s in seams if s.get("paired")]),
        "exemplar_count": len(exemplars),
        "exemplar_kinds": exemplar_kinds,
    }
