# coding: utf-8
"""
SQLAlchemy Emitter - Sinh SQLAlchemy models cho FastAPI backend.

Module nay chua SQLAlchemyEmitter de render SQLAlchemy model files
tu DataModelCollection su dung Jinja2 templates.

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.emitters.core.db.models import (
    DataModel,
    DataModelCollection,
    ColumnType,
)


# Mapping tu ColumnType sang SQLAlchemy type
_SQLALCHEMY_TYPE_MAP = {
    ColumnType.STRING: "String",
    ColumnType.INTEGER: "Integer",
    ColumnType.BOOLEAN: "Boolean",
    ColumnType.DECIMAL: "Numeric",
    ColumnType.TEXT: "Text",
    ColumnType.JSON: "JSON",
    ColumnType.DATETIME: "DateTime",
    ColumnType.UUID: "String",
}


@dataclass
class SQLAlchemyEmitter:
    """
    Emitter de sinh SQLAlchemy model files cho FastAPI.

    Render models tu DataModelCollection sang SQLAlchemy classes.
    KPI-029: Tenant isolation qua tenant_id column.
    """

    def emit(
        self,
        collection: DataModelCollection,
        output_dir: Path,
    ) -> dict[str, str]:
        """
        Emit SQLAlchemy model files tu DataModelCollection.

        Args:
            collection: Collection chua cac data models
            output_dir: Directory de luu files

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}
        models_dir = output_dir / "models"
        models_dir.mkdir(parents=True, exist_ok=True)

        if not collection.models:
            return files

        for model in collection.models:
            filename = f"{self._to_snake_case(model.id)}.py"
            content = self._emit_model_file(model)
            file_key = str((models_dir / filename).relative_to(output_dir)).replace("\\", "/")
            files[file_key] = content

        # Sinh __init__.py
        init_key = str((models_dir / "__init__.py").relative_to(output_dir)).replace("\\", "/")
        files[init_key] = self._emit_models_init(collection)

        return files

    def _emit_model_file(self, model: DataModel) -> str:
        """Sinh SQLAlchemy model file cho mot model."""
        lines: list[str] = []
        class_name = model.id

        lines.append('"""')
        lines.append(f"SQLAlchemy Model: {class_name}")
        lines.append(f"Table: {model.table_name}")
        if model.description:
            lines.append(f"Description: {model.description}")
        lines.append("")
        lines.append("Auto-generated by Midicoder CE.")
        lines.append('"""')
        lines.append("")
        lines.append("from __future__ import annotations")
        lines.append("")
        lines.append("from sqlalchemy import String, Integer, Boolean, Numeric, Text, DateTime, Index")
        lines.append("from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship")
        lines.append("from typing import Optional")
        lines.append("")
        lines.append("")

        # KPI-029: Tenant mixin
        if model.tenant_isolated:
            lines.append("# KPI-029: Tenant Isolation enforced")
            lines.append("")

        lines.append(f"class {class_name}(Base):")
        lines.append(f'    """{model.description or model.table_name}"""')
        lines.append(f"    __tablename__ = '{model.table_name}'")
        lines.append("")

        # Columns
        for col in model.columns:
            sa_type = _SQLALCHEMY_TYPE_MAP.get(col.column_type, "String")
            col_options = []

            if col.primary_key:
                col_options.append("primary_key=True")
            if col.required and not col.primary_key:
                col_options.append("nullable=False")
            if col.unique:
                col_options.append("unique=True")
            if col.max_length and sa_type == "String":
                col_options.append(f"length={col.max_length}")
            if col.precision and sa_type == "Numeric":
                col_options.append(f"precision={col.precision}")
                if col.scale:
                    col_options.append(f"scale={col.scale}")
            if col.tenant_aware:
                col_options.append("# KPI-029: Tenant isolation")

            options_str = ", ".join(col_options)
            if options_str:
                lines.append(f"    {col.name}: Mapped[{sa_type}] = mapped_column({options_str})")
            else:
                lines.append(f"    {col.name}: Mapped[{sa_type}] = mapped_column()")

        # Relationships
        for rel in model.relationships:
            rel_name = self._to_snake_case(rel.target_model) + "_rel"
            lines.append(f"    {rel_name} = relationship('{rel.target_model}')")

        lines.extend(["", ""])
        return "\n".join(lines)

    def _emit_models_init(self, collection: DataModelCollection) -> str:
        """Sinh __init__.py cho models directory."""
        lines = ['"""Models package - auto-generated by Midicoder CE."""', ""]
        for model in collection.models:
            import_name = self._to_snake_case(model.id)
            lines.append(f"from .{import_name} import {model.id}")
        lines.append("")
        lines.append("__all__ = [")
        for model in collection.models:
            lines.append(f'    "{model.id}",')
        lines.append("]")
        return "\n".join(lines)

    @staticmethod
    def _to_snake_case(name: str) -> str:
        """Chuyen PascalCase sang snake_case."""
        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
        return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()