# coding: utf-8
"""
SQLAlchemy Emitter - Sinh SQLAlchemy models cho FastAPI backend.

Module nay chua SQLAlchemyEmitter de render SQLAlchemy model files
tu DataModelCollection su dung Jinja2 templates.

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.emitters.core.db.models import (
    DataModel,
    DataModelCollection,
    ColumnType,
    Datasource,
    DatabaseEngine,
)


# Mapping tu ColumnType sang SQLAlchemy type
_SQLALCHEMY_TYPE_MAP = {
    ColumnType.STRING: "String",
    ColumnType.INTEGER: "Integer",
    ColumnType.BOOLEAN: "Boolean",
    ColumnType.DECIMAL: "Numeric",
    ColumnType.TEXT: "Text",
    ColumnType.JSON: "JSON",
    ColumnType.DATETIME: "DateTime",
    ColumnType.UUID: "String",
}

# Chuoi docstring 3 dau gach dau
_TRIPLE_DQ = '"""'
# Chuoi docstring 3 dau gach dau dan
_TRIPLE_SQ = "'''"


@dataclass
class SQLAlchemyEmitter:
    """
    Emitter de sinh SQLAlchemy model files cho FastAPI.

    Render models tu DataModelCollection sang SQLAlchemy classes.
    KPI-029: Tenant isolation qua tenant_id column.
    """

    def emit(
        self,
        collection: DataModelCollection,
        output_dir: Path,
    ) -> dict[str, str]:
        """
        Emit SQLAlchemy model files tu DataModelCollection.

        Args:
            collection: Collection chua cac data models
            output_dir: Directory de luu files

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}
        models_dir = output_dir / "models"
        models_dir.mkdir(parents=True, exist_ok=True)

        if not collection.models:
            return files

        for model in collection.models:
            filename = f"{self._to_snake_case(model.id)}.py"
            content = self._emit_model_file(model)
            file_key = str((models_dir / filename).relative_to(output_dir)).replace("\\", "/")
            files[file_key] = content

        # Sinh __init__.py
        init_key = str((models_dir / "__init__.py").relative_to(output_dir)).replace("\\", "/")
        files[init_key] = self._emit_models_init(collection)

        return files

    def _emit_model_file(self, model: DataModel) -> str:
        """Sinh SQLAlchemy model file cho mot model."""
        lines: list[str] = []
        class_name = model.id

        lines.append(_TRIPLE_DQ)
        lines.append(f"SQLAlchemy Model: {class_name}")
        lines.append(f"Table: {model.table_name}")
        if model.description:
            lines.append(f"Description: {model.description}")
        lines.append("")
        lines.append("Auto-generated by Midicoder CE.")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from __future__ import annotations")
        lines.append("")
        lines.append("from sqlalchemy import String, Integer, Boolean, Numeric, Text, DateTime, Index")
        lines.append("from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship")
        lines.append("from typing import Optional")
        lines.append("")
        lines.append("")

        # KPI-029: Tenant mixin
        if model.tenant_isolated:
            lines.append("# KPI-029: Tenant Isolation enforced")
            lines.append("")

        lines.append(f"class {class_name}(Base):")
        lines.append(f"    {_TRIPLE_DQ}{model.description or model.table_name}{_TRIPLE_DQ}")
        lines.append(f"    __tablename__ = '{model.table_name}'")
        lines.append("")

        # Columns
        for col in model.columns:
            sa_type = _SQLALCHEMY_TYPE_MAP.get(col.column_type, "String")
            col_options = []

            if col.primary_key:
                col_options.append("primary_key=True")
            if col.required and not col.primary_key:
                col_options.append("nullable=False")
            if col.unique:
                col_options.append("unique=True")
            if col.max_length and sa_type == "String":
                col_options.append(f"length={col.max_length}")
            if col.precision and sa_type == "Numeric":
                col_options.append(f"precision={col.precision}")
                if col.scale:
                    col_options.append(f"scale={col.scale}")
            if col.tenant_aware:
                col_options.append("# KPI-029: Tenant isolation")

            options_str = ", ".join(col_options)
            if options_str:
                lines.append(f"    {col.name}: Mapped[{sa_type}] = mapped_column({options_str})")
            else:
                lines.append(f"    {col.name}: Mapped[{sa_type}] = mapped_column()")

        # Relationships
        for rel in model.relationships:
            rel_name = self._to_snake_case(rel.target_model) + "_rel"
            lines.append(f"    {rel_name} = relationship('{rel.target_model}')")

        lines.extend(["", ""])
        return "\n".join(lines)

    def _emit_models_init(self, collection: DataModelCollection) -> str:
        """Sinh __init__.py cho models directory."""
        lines = [f'{_TRIPLE_DQ}Models package - auto-generated by Midicoder CE.{_TRIPLE_DQ}', ""]
        for model in collection.models:
            import_name = self._to_snake_case(model.id)
            lines.append(f"from .{import_name} import {model.id}")
        lines.append("")
        lines.append("__all__ = [")
        for model in collection.models:
            lines.append(f'    "{model.id}",')
        lines.append("]")
        return "\n".join(lines)

    def emit_connection_config(self, datasource: Datasource) -> dict[str, str]:
        """
        Sinh file database.py voi engine + pool config.

        Args:
            datasource: Datasource config de sinh connection code

        Returns:
            Dictionary {file_path: content}
        """
        lines: list[str] = []
        lines.append(_TRIPLE_DQ)
        lines.append(f"Database connection configuration - Auto-generated by Midicoder CE.")
        lines.append(f"Datasource: {datasource.name}")
        lines.append(f"Engine: {datasource.engine.value}")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from sqlalchemy import create_engine")
        lines.append("from sqlalchemy.orm import sessionmaker, DeclarativeBase")
        lines.append("from sqlalchemy.pool import QueuePool")
        lines.append("import os")
        lines.append("")
        lines.append("")
        lines.append(f"# Connection string (de: ${{{datasource.name}_URL}})")
        lines.append("DATABASE_URL = os.environ.get(")
        lines.append(f'    "{datasource.name.upper()}_URL",')
        lines.append(f'    "{datasource.connection_string}",')
        lines.append(")")
        lines.append("")
        lines.append("")
        lines.append("# Engine voi pool config")
        lines.append("engine = create_engine(")
        lines.append("    DATABASE_URL,")
        lines.append(f"    pool_size={datasource.pool_size},")
        lines.append(f"    max_overflow={datasource.max_overflow},")
        lines.append(f"    pool_timeout={datasource.pool_timeout},")
        lines.append(f"    pool_recycle={datasource.pool_recycle},")
        lines.append(f"    poolclass=QueuePool,")
        if datasource.ssl_enabled:
            lines.append("    connect_args={'ssl': True},")
        lines.append(")")
        lines.append("")
        lines.append("")
        lines.append("SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)")
        lines.append("")
        lines.append("")
        lines.append("class Base(DeclarativeBase):")
        lines.append(f"    {_TRIPLE_DQ}Base class for all SQLAlchemy models.{_TRIPLE_DQ}")
        lines.append("    pass")
        lines.append("")
        lines.append("")
        lines.append("def get_db():")
        lines.append(f"    {_TRIPLE_DQ}Dependency provider cho database session.{_TRIPLE_DQ}")
        lines.append("    db = SessionLocal()")
        lines.append("    try:")
        lines.append("        yield db")
        lines.append("    finally:")
        lines.append("        db.close()")

        # Sinh read replica config neu co
        if datasource.read_replicas:
            lines.append("")
            lines.append("")
            lines.append("# Read Replicas")
            for replica in datasource.read_replicas:
                replica_name = replica.name.upper()
                lines.append(f"{replica.name}_engine = create_engine(")
                lines.append(f'    os.environ.get("{replica_name}_URL", "{replica.connection_string}"),')
                lines.append(f"    pool_size={datasource.pool_size},")
                lines.append(")")

        return {"database.py": "\n".join(lines)}

    def emit_base_repository(self) -> dict[str, str]:
        """
        Sinh BaseRepository voi CRUD + tenant filter.

        Returns:
            Dictionary {file_path: content}
        """
        lines: list[str] = []
        lines.append(_TRIPLE_DQ)
        lines.append("Base Repository - CRUD base class voi tenant isolation (KPI-029)")
        lines.append("Auto-generated by Midicoder CE.")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from __future__ import annotations")
        lines.append("")
        lines.append("from typing import Any, Generic, TypeVar, Optional, Sequence")
        lines.append("from sqlalchemy.orm import Session")
        lines.append("")
        lines.append("")
        lines.append("ModelType = TypeVar('ModelType')")
        lines.append("")
        lines.append("")
        lines.append("class BaseRepository(Generic[ModelType]):")
        lines.append(f"    {_TRIPLE_DQ}Base repository voi CRUD operations va tenant isolation (KPI-029).")
        lines.append("    Usage:")
        lines.append("        class UserRepository(BaseRepository[User]):")
        lines.append("            model_class = User")
        lines.append(f"    {_TRIPLE_DQ}")
        lines.append("")
        lines.append("    model_class: type[ModelType]")
        lines.append("")
        lines.append("    def __init__(self, db: Session, tenant_id: str | None = None):")
        lines.append(f"        {_TRIPLE_DQ}Khai bao repository voi database session va tenant context.{_TRIPLE_DQ}")
        lines.append("        self.db = db")
        lines.append("        self.tenant_id = tenant_id")
        lines.append("")
        lines.append("    def get(self, id: Any) -> Optional[ModelType]:")
        lines.append(f"        {_TRIPLE_DQ}Lay record theo ID.{_TRIPLE_DQ}")
        lines.append("        return self.db.get(self.model_class, id)")
        lines.append("")
        lines.append("    def list(self, **filters: Any) -> Sequence[ModelType]:")
        lines.append(f"        {_TRIPLE_DQ}Lay danh sach records voi filters.{_TRIPLE_DQ}")
        lines.append("        query = self.db.query(self.model_class)")
        lines.append("        # KPI-029: Tu dong filter theo tenant_id neu co")
        lines.append("        if self.tenant_id:")
        lines.append("            query = query.filter_by(tenant_id=self.tenant_id)")
        lines.append("        for key, value in filters.items():")
        lines.append("            if value is not None:")
        lines.append("                query = query.filter(**{key: value})")
        lines.append("        return query.all()")
        lines.append("")
        lines.append("    def create(self, obj: ModelType) -> ModelType:")
        lines.append(f"        {_TRIPLE_DQ}Tao record moi.{_TRIPLE_DQ}")
        lines.append("        self.db.add(obj)")
        lines.append("        self.db.commit()")
        lines.append("        self.db.refresh(obj)")
        lines.append("        return obj")
        lines.append("")
        lines.append("    def update(self, id: Any, **kwargs: Any) -> Optional[ModelType]:")
        lines.append(f"        {_TRIPLE_DQ}Cap nhat record theo ID.{_TRIPLE_DQ}")
        lines.append("        obj = self.get(id)")
        lines.append("        if obj:")
        lines.append("            for key, value in kwargs.items():")
        lines.append("                setattr(obj, key, value)")
        lines.append("            self.db.commit()")
        lines.append("            self.db.refresh(obj)")
        lines.append("        return obj")
        lines.append("")
        lines.append("    def delete(self, id: Any) -> bool:")
        lines.append(f"        {_TRIPLE_DQ}Xoa record theo ID.{_TRIPLE_DQ}")
        lines.append("        obj = self.get(id)")
        lines.append("        if obj:")
        lines.append("            self.db.delete(obj)")
        lines.append("            self.db.commit()")
        lines.append("            return True")
        lines.append("        return False")

        return {"repositories/base_repository.py": "\n".join(lines)}

    def emit_migration(self, model: DataModel, version: str) -> dict[str, str]:
        """
        Sinh Alembic migration file cho model.

        Args:
            model: DataModel de sinh migration
            version: Version revision ID

        Returns:
            Dictionary {file_path: content}
        """
        lines: list[str] = []
        lines.append(_TRIPLE_DQ)
        lines.append(f"Create {model.table_name} table")
        lines.append("")
        lines.append(f"Revision ID: {version}")
        lines.append("Revises: ")
        lines.append("Create Date: 2026-05-06")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from alembic import op")
        lines.append("import sqlalchemy as sa")
        lines.append("")
        lines.append("")
        lines.append(f"revision = '{version}'")
        lines.append("down_revision = None")
        lines.append("branch_labels = None")
        lines.append("depends_on = None")
        lines.append("")
        lines.append("")
        lines.append("def upgrade() -> None:")
        lines.append(f'    op.create_table("{model.table_name}",')

        # Columns
        for col in model.columns:
            sa_type = _SQLALCHEMY_TYPE_MAP.get(col.column_type, "sa.String")
            nullable = "nullable=True" if not col.required and not col.primary_key else "nullable=False"
            col_line = f'        sa.Column("{col.name}", {sa_type}, {nullable})'
            if col.primary_key:
                col_line = f'        sa.Column("{col.name}", {sa_type}, primary_key=True)'
            lines.append(col_line + ",")

        lines.append("    )")

        # Indexes
        for idx in model.indexes:
            unique_param = "unique=True" if idx.unique else "unique=False"
            lines.append(f'    op.create_index(op.f("{idx.name}"), "{model.table_name}", {idx.columns}, {unique_param})')

        lines.append("")
        lines.append("")
        lines.append("def downgrade() -> None:")
        # Reverse indexes
        for idx in model.indexes:
            lines.append(f'    op.drop_index(op.f("{idx.name}"), table_name="{model.table_name}")')
        lines.append(f'    op.drop_table("{model.table_name}")')

        filename = f"migrations/versions/{version}_create_{model.table_name}.py"
        return {filename: "\n".join(lines)}

    def emit_seed_data(self, models: list[DataModel]) -> dict[str, str]:
        """
        Sinh seed data Python script.

        Args:
            models: Danh sach models de sinh seed data

        Returns:
            Dictionary {file_path: content}
        """
        lines: list[str] = []
        lines.append(_TRIPLE_DQ)
        lines.append("Seed data script - Auto-generated by Midicoder CE.")
        lines.append("Su dung: python seed_data.py")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from sqlalchemy.orm import Session")
        lines.append("from database import SessionLocal, Base, engine")
        lines.append("")
        lines.append("")
        lines.append("def seed():")
        lines.append(f"    {_TRIPLE_DQ}Tao seed data cho cac bang.{_TRIPLE_DQ}")
        lines.append("    Base.metadata.create_all(bind=engine)")
        lines.append("    db = SessionLocal()")
        lines.append("    try:")
        for model in models:
            lines.append(f"        # Seed data cho {model.table_name}")
            lines.append(f'        print(f"Seeding {model.table_name}...")')
            lines.append("")
        lines.append('        print("Seed data completed!")')
        lines.append("    finally:")
        lines.append("        db.close()")
        lines.append("")
        lines.append("")
        lines.append(f"if __name__ == '{_TRIPLE_SQ}__main__{_TRIPLE_SQ}':")
        lines.append("    seed()")

        return {"seed_data.py": "\n".join(lines)}

    @staticmethod
    def _to_snake_case(name: str) -> str:
        """Chuyen PascalCase sang snake_case."""
        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
        return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()