# coding: utf-8
"""
TypeORM Emitter - Sinh TypeORM entities cho NestJS backend.

Module nay chua TypeORMEmitter de render TypeORM entity files
tu DataModelCollection su dung Jinja2 templates.

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.emitters.core.db.models import (
    DataModel,
    DataModelCollection,
    ColumnDef,
    ColumnType,
    Relationship,
)


# Mapping tu ColumnType sang TypeORM type
_TYPEORM_TYPE_MAP = {
    ColumnType.STRING: "String",
    ColumnType.INTEGER: "Int",
    ColumnType.BOOLEAN: "Boolean",
    ColumnType.DECIMAL: "Decimal",
    ColumnType.TEXT: "Text",
    ColumnType.JSON: "jsonb",
    ColumnType.DATETIME: "Date",
    ColumnType.UUID: "uuid",
}


@dataclass
class TypeORMEmitter:
    """
    Emitter de sinh TypeORM entity files cho NestJS.

    Render models tu DataModelCollection sang TypeORM entity classes.
    KPI-029: Tenant isolation qua tenantId column.
    """

    def emit(
        self,
        collection: DataModelCollection,
        output_dir: Path,
    ) -> dict[str, str]:
        """
        Emit TypeORM entity files tu DataModelCollection.

        Args:
            collection: Collection chua cac data models
            output_dir: Directory de luu files

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}
        entities_dir = output_dir / "entities"
        entities_dir.mkdir(parents=True, exist_ok=True)

        if not collection.models:
            return files

        for model in collection.models:
            filename = f"{self._to_kebab_case(model.id)}.entity.ts"
            content = self._emit_entity_file(model)
            file_key = str((entities_dir / filename).relative_to(output_dir)).replace("\\", "/")
            files[file_key] = content

        # Sinh index.ts
        index_key = str((entities_dir / "index.ts").relative_to(output_dir)).replace("\\", "/")
        files[index_key] = self._emit_entities_index(collection)

        return files

    def _emit_entity_file(self, model: DataModel) -> str:
        """Sinh TypeORM entity file cho mot model."""
        lines: list[str] = []
        class_name = model.id
        table_name = self._to_kebab_case(model.table_name)

        lines.append(f"// KPI-029: Tenant Isolation: {model.tenant_isolated}")
        lines.append("")
        lines.append("import { Entity, Column, PrimaryGeneratedColumn, Index, ManyToOne, OneToMany, JoinTable } from 'typeorm';")
        lines.append("")
        lines.append(f"@Entity('{table_name}')")
        if model.tenant_isolated:
            lines.append("// KPI-029: Tenant isolated entity")
        lines.append(f"export class {class_name} {{")
        lines.append("")

        # Columns
        for col in model.columns:
            orm_type = _TYPEORM_TYPE_MAP.get(col.column_type, "String")
            col_name = self._to_camel_case(col.name)

            if col.primary_key:
                lines.append(f"  @PrimaryGeneratedColumn('{{{orm_type.lower()}}}')")
            else:
                opts = self._column_options(col)
                lines.append(f"  @Column({{{opts}}})")

            lines.append(f"  {col_name}!: {orm_type};")
            lines.append("")

        # Relationships
        for rel in model.relationships:
            rel_name = self._to_camel_case(rel.target_model.lower() + "_rel")
            lines.append(f"  @ManyToOne(() => {rel.target_model})")
            lines.append(f"  {rel_name}!: {rel.target_model};")
            lines.append("")

        lines.append("}")
        lines.extend(["", ""])
        return "\n".join(lines)

    def _column_options(self, col: ColumnDef) -> str:
        """Xay dung column options string."""
        opts: list[str] = []
        opts.append(f"type: '{_TYPEORM_TYPE_MAP.get(col.column_type, 'String').lower()}'")
        if col.required:
            opts.append("nullable: false")
        if col.unique:
            opts.append("unique: true")
        if col.max_length:
            opts.append(f"length: {col.max_length}")
        if col.tenant_aware:
            opts.append("// KPI-029: Tenant isolation")
        return ", ".join(opts)

    def _emit_entities_index(self, collection: DataModelCollection) -> str:
        """Sinh index.ts cho entities directory."""
        lines = ["// Entities index - auto-generated by Midicoder CE", ""]
        for model in collection.models:
            import_path = self._to_kebab_case(model.id) + ".entity"
            lines.append(f"export * from './{import_path}';")
        return "\n".join(lines)

    @staticmethod
    def _to_kebab_case(name: str) -> str:
        """Chuyen PascalCase sang kebab-case."""
        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1-\2", name)
        return re.sub("([a-z0-9])([A-Z])", r"\1-\2", s1).lower()

    @staticmethod
    def _to_camel_case(name: str) -> str:
        """Chuyen snake_case sang camelCase."""
        parts = name.split("_")
        return parts[0] + "".join(p.capitalize() for p in parts[1:])