"""Extractor constants and integration hints."""

from __future__ import annotations

TOOL_VERSION = "0.1.0"

MAX_EXEMPLARS = 100
MAX_FILES_FOR_PROFILE = 30
MAX_FILES_FOR_EXEMPLARS = None
SNIPPET_CONTEXT_BEFORE = 2
SNIPPET_CONTEXT_AFTER = 8
SNIPPET_MIN_LENGTH = 50
EXEMPLAR_PATTERN_BEFORE = 3
EXEMPLAR_PATTERN_AFTER = 15
