# coding: utf-8
"""
NestJS Route Emitter - Sinh route files cho NestJS backend.

Module nay chua cac emitter de generate:
- NestJSRouteEmitter: HTTP REST routes
- NestJSGraphQLResolverEmitter: GraphQL
- NestJSWebhookEmitter: Webhooks

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.emitters.core.gateway.route_models import (
    Route,
    RouteCollection,
    GraphQLResolver,
    WebhookHandler,
    HttpMethod,
)


# ===========================================================================
# NestJS Route Emitter
# ===========================================================================


@dataclass
class NestJSRouteEmitter:
    """Emitter de sinh NestJS controller files tu RouteCollection."""

    def emit(
        self,
        collection: RouteCollection,
        output_dir: Path,
    ) -> dict[str, str]:
        """Emit NestJS controller files."""
        files: dict[str, str] = {}
        if not collection.routes:
            return files

        routes_dir = output_dir / "routes"
        routes_dir.mkdir(parents=True, exist_ok=True)

        groups = collection.group_routes_by_tag()
        if not groups:
            groups = {"default": collection.routes}

        for tag, routes in groups.items():
            filename = f"{self._to_kebab_case(tag)}-controller.ts"
            content = self._emit_controller_file(tag, routes)
            files[str(routes_dir / filename)] = content

        return files

    def _emit_controller_file(self, tag: str, routes: list[Route]) -> str:
        """Sinh controller file cho mot group routes."""
        controller_name = self._to_pascal_case(tag) + "Controller"

        lines = [
            '"""',
            f"Controller: {tag} endpoints.",
            "Auto-generated by Midicoder CE.",
            '"""',
            "",
            "import {",
            "  Controller, Get, Post, Put, Patch, Delete,",
            "  Param, Query, Body, Headers,",
            "} from '@nestjs/common';",
            "import { ApiTags, ApiOperation, ApiResponse } from '@nestjs/swagger';",
            "",
            f"@ApiTags('{tag}')",
            f"@Controller('/api/{self._to_kebab_case(tag)}')",
            f"export class {controller_name} {{",
        ]

        for route in routes:
            lines.extend(self._emit_route_method(route))
            lines.append("")

        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    def _emit_route_method(self, route: Route) -> list[str]:
        """Sinh method cho mot route."""
        method_decorator = self._http_method_decorator(route)
        path = route.path.lstrip("/api/").lstrip("/")

        lines = [f"  {method_decorator}('{path}')"]
        lines.append(f'  @ApiOperation({{ summary: "{route.description or route.id}" }})')
        lines.append(f"  @ApiResponse({{ status: {route.response_status}, description: 'Success' }})")

        func_name = self._to_camel_case(route.id)
        params: list[str] = []

        for pp in route.path_params:
            params.append(f"@Param('{pp.name}') {pp.name}: string")

        for qp in route.query_params:
            params.append(f"@Query('{qp.name}') {qp.name}: {self._ts_type(qp.param_type)}")

        if route.is_write_operation() and route.request_schema:
            dto_name = self._to_pascal_case(route.id) + "Dto"
            params.append(f"@Body() payload: {dto_name}")

        if route.requires_auth():
            lines.insert(0, "  @UseGuards(JwtAuthGuard, TenantGuard)")

        params_str = ", ".join(params) if params else ""
        return_type = "Promise<any>"

        lines.append(f"  async {func_name}({params_str}): {return_type} {{")

        if route.requires_auth():
            lines.append("    // KPI-029: Tenant isolation enforced by TenantGuard")

        handler_service = self._to_camel_case(route.handler_id) + "Service"
        handler_method = "execute" if route.is_write_operation() else "find"
        lines.append(f"    return this.{handler_service}.{handler_method}(")

        if params:
            lines.append(f"      {{ {', '.join(p.split(':')[0].strip() for p in params)} }}")
        else:
            lines.append("      {}")

        lines.append("    )")
        lines.append("  }")
        return lines

    def _http_method_decorator(self, route: Route) -> str:
        """Map HTTP method sang NestJS decorator."""
        method_map = {
            HttpMethod.GET: "Get", HttpMethod.POST: "Post",
            HttpMethod.PUT: "Put", HttpMethod.PATCH: "Patch",
            HttpMethod.DELETE: "Delete", HttpMethod.HEAD: "Head",
            HttpMethod.OPTIONS: "Options",
        }
        decorator = method_map.get(route.method, "Get")
        return f"@{decorator}()"

    def _ts_type(self, type_str: str) -> str:
        """Map type string sang TypeScript type."""
        type_map = {
            "str": "string", "string": "string",
            "int": "number", "integer": "number",
            "float": "number", "decimal": "number",
            "bool": "boolean", "boolean": "boolean",
            "uuid": "string", "datetime": "Date",
        }
        return type_map.get(type_str.lower(), "string")

    @staticmethod
    def _to_kebab_case(name: str) -> str:
        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1-\2", name)
        return re.sub("([a-z0-9])([A-Z])", r"\1-\2", s1).lower()

    @staticmethod
    def _to_pascal_case(name: str) -> str:
        return "".join(word.capitalize() for word in name.replace("-", " ").replace("_", " ").split())

    @staticmethod
    def _to_camel_case(name: str) -> str:
        words = name.replace("-", " ").replace("_", " ").split()
        return words[0].lower() + "".join(w.capitalize() for w in words[1:])


# ===========================================================================
# NestJS GraphQL Resolver Emitter
# ===========================================================================


@dataclass
class NestJSGraphQLResolverEmitter:
    """Emitter de sinh GraphQL resolver files cho NestJS."""

    def emit(
        self,
        collection: RouteCollection,
        output_dir: Path,
    ) -> dict[str, str]:
        """Emit GraphQL resolver files."""
        files: dict[str, str] = {}
        if not collection.resolvers:
            return files

        graphql_dir = output_dir / "graphql"
        graphql_dir.mkdir(parents=True, exist_ok=True)

        for resolver in collection.resolvers:
            filename = f"{self._to_kebab_case(resolver.id)}.resolver.ts"
            content = self._emit_resolver_file(resolver)
            files[str(graphql_dir / filename)] = content

        return files

    def _emit_resolver_file(self, resolver: GraphQLResolver) -> str:
        """Sinh resolver file cho mot GraphQL resolver."""
        type_name = self._to_pascal_case(resolver.id)
        op_decorator = "Query" if resolver.operation.value == "query" else "Mutation"

        lines = [
            '"""',
            f"GraphQL Resolver: {resolver.id}",
            "Auto-generated by Midicoder CE.",
            '"""',
            "",
            f"import {{ {op_decorator}, Resolver, Args }} from '@nestjs/graphql';",
            f"import {{ {type_name}Output }} from './{self._to_kebab_case(resolver.id)}.dto';",
            "",
            f"@Resolver('{self._to_pascal_case(resolver.type_name)}')",
            f"export class {type_name}Resolver {{",
            "",
            f"  @{op_decorator.lower()}(() => {type_name}Output)",
        ]

        args_str = ""
        if resolver.args:
            args_str = ", ".join(
                f"@Args('{a.name}') {a.name}: {self._ts_type(a.arg_type)}"
                for a in resolver.args
            )

        func_name = self._to_camel_case(resolver.id)
        lines.append(f"  async {func_name}({args_str}): Promise<{type_name}Output> {{")

        if resolver.tenant_scoped:
            lines.append("    // KPI-029: Tenant scope enforced")

        handler = self._to_camel_case(resolver.handler_id) + "Service"
        lines.append(f"    return this.{handler}.execute({{}})")
        lines.append("  }")
        lines.append("}")
        lines.append("")

        return "\n".join(lines)

    def _ts_type(self, type_str: str) -> str:
        type_map = {
            "String": "string", "Int": "number",
            "Float": "number", "Boolean": "boolean",
            "ID": "string", "Date": "Date",
        }
        return type_map.get(type_str, "string")

    @staticmethod
    def _to_kebab_case(name: str) -> str:
        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1-\2", name)
        return re.sub("([a-z0-9])([A-Z])", r"\1-\2", s1).lower()

    @staticmethod
    def _to_pascal_case(name: str) -> str:
        return "".join(word.capitalize() for word in name.replace("-", " ").replace("_", " ").split())

    @staticmethod
    def _to_camel_case(name: str) -> str:
        words = name.replace("-", " ").replace("_", " ").split()
        return words[0].lower() + "".join(w.capitalize() for w in words[1:])


# ===========================================================================
# NestJS Webhook Emitter
# ===========================================================================


@dataclass
class NestJSWebhookEmitter:
    """Emitter de sinh webhook handler cho NestJS."""

    def emit(
        self,
        collection: RouteCollection,
        output_dir: Path,
    ) -> dict[str, str]:
        """Emit webhook handler files."""
        files: dict[str, str] = {}
        if not collection.webhooks:
            return files

        webhooks_dir = output_dir / "webhooks"
        webhooks_dir.mkdir(parents=True, exist_ok=True)

        for webhook in collection.webhooks:
            filename = f"{self._to_kebab_case(webhook.event_type)}-handler.ts"
            content = self._emit_webhook_file(webhook)
            files[str(webhooks_dir / filename)] = content

        return files

    def _emit_webhook_file(self, webhook: WebhookHandler) -> str:
        """Sinh webhook handler file."""
        handler_name = self._to_pascal_case(webhook.event_type) + "WebhookHandler"
        path = webhook.path
        parts = path.split("/")
        controller_path = parts[1] if len(parts) > 1 else ""
        post_path = parts[-1] if len(parts) > 1 else path

        lines = [
            '"""',
            f"Webhook Handler: {webhook.event_type}",
            f"Path: {path}",
            "Auto-generated by Midicoder CE.",
            '"""',
            "",
            "import { Controller, Post, Body, Headers, UnauthorizedException } from '@nestjs/common';",
            "import * as crypto from 'crypto';",
            "",
            f"@Controller('{controller_path}')",
            f"export class {handler_name} {{",
            "",
            f"  @Post('{post_path}')",
            "  async handleWebhook(",
            "    @Body() payload: Record<string, any>,",
        ]

        if webhook.auth_config and webhook.verify_signature:
            lines.append(f"    @Headers('{webhook.auth_config.header_name}') signature: string,")

        lines.append("  ): Promise<{ status: string }> {")

        if webhook.verify_signature:
            lines.append("    // Verify HMAC signature")
            lines.append("    const secret = process.env.WEBHOOK_SECRET || '';")
            lines.append("    const expected = crypto.createHmac('sha256', secret)")
            lines.append("      .update(JSON.stringify(payload))")
            lines.append("      .digest('hex');")
            lines.append("    if (!crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(signature || ''))) {")
            lines.append("      throw new UnauthorizedException('Invalid signature');")
            lines.append("    }")
            lines.append("")

        lines.append(f"    // TODO: Wire to handler: {webhook.handler_id}")
        lines.append('    return { status: "ok" };')
        lines.append("  }")
        lines.append("}")
        lines.append("")

        return "\n".join(lines)

    @staticmethod
    def _to_kebab_case(name: str) -> str:
        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1-\2", name)
        return re.sub("([a-z0-9])([A-Z])", r"\1-\2", s1).lower()

    @staticmethod
    def _to_pascal_case(name: str) -> str:
        return "".join(word.capitalize() for word in name.replace("-", " ").replace("_", " ").split())