# coding: utf-8
"""
FastAPI File Storage Emitter (CP11).

Module này chứa FastAPIFileStorageEmitter để sinh file storage code
cho FastAPI từ FileStorageCollection.

Tạo ra:
- S3 config module với tenant-aware clients (KPI-029)
- FileUploadService với UploadPolicy enforcement
- MediaTransformService sử dụng Pillow cho image resize/thumbnail
- Storage router với /upload, /download, /delete, /presigned-endpoints

KPI-029: Tenant Isolation - tenant_isolation=True mặc định
Obligation: UploadPolicy validation mandatory trên mọi file upload

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.emitters.core.cp11_file_media.models import (
    FileStorageCollection,
    StorageBackend,
    TransformType,
)


@dataclass
class FastAPIFileStorageEmitter:
    """
    Emitter để sinh file storage code cho FastAPI.

    Render storage config, upload service, media transform service,
    và storage router từ FileStorageCollection sang Python files.

    KPI-029: Tenant isolation qua key prefix.
    Obligation: UploadPolicy enforcement mandatory.
    """

    stack_dir: Path

    def generate(
        self,
        collection: FileStorageCollection,
        output_dir: Path,
    ) -> dict[str, str]:
        """
        Sinh tất cả file storage files cho FastAPI.

        Args:
            collection: Collection chứa storage profiles, policies, transforms
            output_dir: Thư mục đầu ra để ghi files

        Returns:
            Dictionary {relative_path: content} của tất cả files được sinh ra
        """
        files: dict[str, str] = {}

        if not collection.profiles:
            return files

        # Xác định backends được sử dụng
        backends = {p.backend_type for p in collection.profiles}

        if StorageBackend.S3 in backends:
            files["storage/s3_config.py"] = self._emit_s3_config(collection)

        files["storage/file_upload_service.py"] = self._emit_file_upload_service(collection)

        has_image_transforms = any(
            t.transform_type in (TransformType.RESIZE, TransformType.THUMBNAIL)
            for t in collection.transforms
        )
        if has_image_transforms or collection.transforms:
            files["storage/media_transform_service.py"] = self._emit_media_transform_service(collection)

        files["storage/storage_router.py"] = self._emit_storage_router(collection)
        files["storage/__init__.py"] = '"""Storage package — Auto-generated by Midicoder CE (CP11)."""\n'

        return files

    # =========================================================================
    # S3 Config
    # =========================================================================

    def _emit_s3_config(self, collection: FileStorageCollection) -> str:
        """Sinh S3 config module với tenant-aware clients."""
        s3_profiles = collection.s3_profiles()
        default_profile = s3_profiles[0] if s3_profiles else None
        default_bucket = default_profile.bucket if default_profile else "uploads"
        default_region = default_profile.region if default_profile else "us-east-1"

        lines: list[str] = [
            "# coding: utf-8",
            '"""',
            "S3 Configuration cho FastAPI - Auto-generated by Midicoder CE.",
            "",
            "Cung cấp:",
            "- S3 client (boto3)",
            "- Upload/download/delete operations",
            "- Presigned URLs",
            "KPI-029: Tenant-specific S3 operations",
            "CP11: File Storage & Media",
            '"""',
            "",
            "import os",
            "from typing import Optional",
            "",
            "import boto3",
            "from botocore.config import Config",
            "",
            "",
            "# AWS S3 settings từ environment",
            'AWS_ACCESS_KEY = os.getenv("AWS_ACCESS_KEY_ID", "")',
            'AWS_SECRET_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "")',
            f'AWS_REGION = os.getenv("AWS_REGION", "{default_region}")',
            'AWS_ENDPOINT_URL = os.getenv("AWS_ENDPOINT_URL", None)',
            "",
            f'DEFAULT_BUCKET = os.getenv("S3_BUCKET", "{default_bucket}")',
            "",
            "# KPI-029: Tenant-specific S3 settings",
            'S3_TENANT_BUCKET_PREFIX = os.getenv("S3_TENANT_BUCKET_PREFIX", "tenant")',
            'S3_TENANT_KEY_PREFIX = os.getenv("S3_TENANT_KEY_PREFIX", "tenant")',
            'S3_TENANT_ISOLATION = os.getenv("S3_TENANT_ISOLATION", "true").lower() == "true"',
            "",
            "S3_CONFIG = Config(",
            '    retries={"max_attempts": 3, "mode": "standard"},',
            "    connect_timeout=30,",
            "    read_timeout=60,",
            ")",
            "",
            "_s3_client = None",
            "_tenant_s3_clients: dict = {}",
            "",
            "",
            "def get_s3_client() -> boto3.client:",
            '    """Tạo hoặc trả về S3 client mặc định."""',
            "    global _s3_client",
            "    if _s3_client is None:",
            "        _s3_client = boto3.client(",
            '            "s3",',
            "            aws_access_key_id=AWS_ACCESS_KEY,",
            "            aws_secret_access_key=AWS_SECRET_KEY,",
            "            region_name=AWS_REGION,",
            "            endpoint_url=AWS_ENDPOINT_URL,",
            "            config=S3_CONFIG,",
            "        )",
            "    return _s3_client",
            "",
            "",
            "def get_tenant_s3_client(tenant_id: str) -> boto3.client:",
            "    global _tenant_s3_clients",
            "    if tenant_id not in _tenant_s3_clients:",
            "        _tenant_s3_clients[tenant_id] = boto3.client(",
            '            "s3",',
            "            aws_access_key_id=AWS_ACCESS_KEY,",
            "            aws_secret_access_key=AWS_SECRET_KEY,",
            "            region_name=AWS_REGION,",
            "            endpoint_url=AWS_ENDPOINT_URL,",
            "            config=S3_CONFIG,",
            "        )",
            "    return _tenant_s3_clients[tenant_id]",
            "",
            "",
            "def get_tenant_key_prefix(tenant_id: str) -> str:",
            "    return f'{S3_TENANT_KEY_PREFIX}/{tenant_id}/'",
            "",
            "",
            "def upload_file(",
            "    file_bytes: bytes,",
            "    key: str,",
            '    content_type: str = "application/octet-stream",',
            "    tenant_id: Optional[str] = None,",
            ") -> dict:",
            '    """Upload file lên S3."""',
            "    if tenant_id and S3_TENANT_ISOLATION:",
            "        client = get_tenant_s3_client(tenant_id)",
            "        prefix = get_tenant_key_prefix(tenant_id)",
            "        if not key.startswith(prefix):",
            "            key = f'{prefix}{key}'",
            "    else:",
            "        client = get_s3_client()",
            "    client.put_object(Bucket=DEFAULT_BUCKET, Key=key, Body=file_bytes, ContentType=content_type)",
            "    return {",
            '        "bucket": DEFAULT_BUCKET, "key": key,',
            '        "url": f"https://{DEFAULT_BUCKET}.s3.{AWS_REGION}.amazonaws.com/{key}",',
            '        "tenant_id": tenant_id,',
            "    }",
            "",
            "",
            "def download_file(key: str, tenant_id: Optional[str] = None) -> bytes:",
            '    """Download file từ S3."""',
            "    if tenant_id and S3_TENANT_ISOLATION:",
            "        client = get_tenant_s3_client(tenant_id)",
            "    else:",
            "        client = get_s3_client()",
            '    return client.get_object(Bucket=DEFAULT_BUCKET, Key=key)["Body"].read()',
            "",
            "",
            "def delete_file(key: str, tenant_id: Optional[str] = None) -> bool:",
            '    """Xóa file từ S3."""',
            "    if tenant_id and S3_TENANT_ISOLATION:",
            "        client = get_tenant_s3_client(tenant_id)",
            "    else:",
            "        client = get_s3_client()",
            "    client.delete_object(Bucket=DEFAULT_BUCKET, Key=key)",
            "    return True",
            "",
            "",
            "def get_presigned_url(",
            "    key: str,",
            "    expiration: int = 3600,",
            "    tenant_id: Optional[str] = None,",
            ") -> str:",
            '    """Generate presigned URL cho object."""',
            "    if tenant_id and S3_TENANT_ISOLATION:",
            "        client = get_tenant_s3_client(tenant_id)",
            "    else:",
            "        client = get_s3_client()",
            "    return client.generate_presigned_url(",
            '        "get_object",',
            "        Params={'Bucket': DEFAULT_BUCKET, 'Key': key},",
            "        ExpiresIn=expiration,",
            "    )",
        ]
        return "\n".join(lines)

    # =========================================================================
    # File Upload Service
    # =========================================================================

    def _emit_file_upload_service(self, collection: FileStorageCollection) -> str:
        """Sinh FileUploadService với UploadPolicy enforcement."""
        # Build policy lines
        policy_const_lines: list[str] = []
        for policy in collection.policies:
            safe_name = policy.name.replace("-", "_").upper()
            policy_const_lines.append(f'{safe_name}_ALLOWED_TYPES = {policy.allowed_content_types}')
            policy_const_lines.append(f'{safe_name}_MAX_SIZE = {policy.max_file_size}')
            policy_const_lines.append(f'{safe_name}_ALLOWED_EXTENSIONS = {policy.allowed_extensions}')
            policy_const_lines.append("")

        policy_dict_lines: list[str] = []
        for policy in collection.policies:
            safe_name = policy.name.replace("-", "_").upper()
            policy_dict_lines.append(f'    "{policy.name}": {{')
            policy_dict_lines.append(f'        "allowed_content_types": {safe_name}_ALLOWED_TYPES,')
            policy_dict_lines.append(f'        "max_file_size": {safe_name}_MAX_SIZE,')
            policy_dict_lines.append(f'        "allowed_extensions": {safe_name}_ALLOWED_EXTENSIONS,')
            policy_dict_lines.append("    },")

        lines: list[str] = [
            "# coding: utf-8",
            '"""',
            "File Upload Service cho FastAPI - Auto-generated by Midicoder CE.",
            "Obligation: UploadPolicy validation mandatory trên mọi file upload",
            "KPI-029: Tenant Isolation - tenant folder prefix",
            "CP11: File Storage & Media",
            '"""',
            "",
            "import uuid",
            "import os",
            "from typing import Optional",
            "",
            "from fastapi import UploadFile, HTTPException",
            "",
            "from .s3_config import upload_file, download_file, delete_file, get_presigned_url",
            "",
            "# KPI-029: Tenant folder prefix settings",
            'STORAGE_TENANT_PREFIX = os.getenv("STORAGE_TENANT_PREFIX", "tenant")',
            'STORAGE_TENANT_ISOLATION = os.getenv("STORAGE_TENANT_ISOLATION", "true").lower() == "true"',
            "",
        ]

        # Add policy constants
        if policy_const_lines:
            lines.extend(["# UploadPolicy constants", *policy_const_lines, ""])

        # Add policy lookup dict
        if policy_dict_lines:
            lines.append("UPLOAD_POLICIES = {")
            lines.extend(policy_dict_lines)
            lines.append("}")
            lines.append("")

        # Default allowed types (fallback)
        lines.extend([
            "# Default allowed types (fallback)",
            'ALLOWED_IMAGE_TYPES = {"image/jpeg", "image/png", "image/gif", "image/webp"}',
            'ALLOWED_VIDEO_TYPES = {"video/mp4", "video/webm"}',
            'ALLOWED_DOCUMENT_TYPES = {"application/pdf"}',
            "",
            "MAX_IMAGE_SIZE = 10 * 1024 * 1024",
            "MAX_VIDEO_SIZE = 100 * 1024 * 1024",
            "MAX_DOCUMENT_SIZE = 10 * 1024 * 1024",
            "",
            "",
            "class FileUploadService:",
            '    """Service cho file upload operations với UploadPolicy enforcement."""',
            "",
            "    def __init__(self, tenant_id: Optional[str] = None) -> None:",
            "        self.tenant_id = tenant_id",
            "",
            "    def _get_tenant_folder(self, folder: str, tenant_id: Optional[str] = None) -> str:",
            "        effective_tid = tenant_id or self.tenant_id",
            "        if STORAGE_TENANT_ISOLATION and effective_tid:",
            "            return f'{STORAGE_TENANT_PREFIX}/{effective_tid}/{folder}'",
            "        return folder",
            "",
            "    def _enforce_policy(self, policy_name: str, file: UploadFile, content_size: int) -> None:",
            '        """Obligation enforcement: validate file theo UploadPolicy."""',
            "        policy = UPLOAD_POLICIES.get(policy_name)",
            "        if policy is None:",
            "            raise HTTPException(status_code=400, detail=f'Policy not found: {policy_name}')",
            "",
            "        if file.content_type and file.content_type not in policy['allowed_content_types']:",
            "            raise HTTPException(status_code=400, detail=f'Content type not allowed: {file.content_type}')",
            "",
            "        if content_size > policy['max_file_size']:",
            "            raise HTTPException(status_code=400, detail=f'File too large: {content_size} bytes')",
            "",
            "        ext = file.filename.rsplit('.', 1)[-1].lower() if file.filename and '.' in file.filename else ''",
            "        if ext and ext not in policy['allowed_extensions']:",
            "            raise HTTPException(status_code=400, detail=f'Extension not allowed: .{ext}')",
            "",
            "    async def upload(",
            "        self,",
            "        file: UploadFile,",
            '        folder: str = "uploads",',
            '        policy_name: str = "",',
            "        tenant_id: Optional[str] = None,",
            "    ) -> dict:",
            '        """Upload file với policy enforcement."""',
            "        content = await file.read()",
            "",
            "        # Obligation: enforce UploadPolicy validation nếu có policy",
            "        if policy_name:",
            "            self._enforce_policy(policy_name, file, len(content))",
            "",
            "        tenant_folder = self._get_tenant_folder(folder, tenant_id)",
            "        file_ext = file.filename.rsplit('.', 1)[-1].lower() if file.filename and '.' in file.filename else 'bin'",
            "        key = f'{tenant_folder}/{uuid.uuid4()}.{file_ext}'",
            "",
            "        result = upload_file(",
            "            content, key,",
            '            content_type=file.content_type or "application/octet-stream",',
            "            tenant_id=tenant_id or self.tenant_id,",
            "        )",
            "",
            "        return {",
            '            "filename": file.filename, "url": result["url"],',
            '            "key": key, "size": len(content), "type": file.content_type,',
            '            "tenant_id": tenant_id or self.tenant_id,',
            "        }",
            "",
            "    async def download(self, key: str, tenant_id: Optional[str] = None) -> bytes:",
            "        return download_file(key, tenant_id=tenant_id or self.tenant_id)",
            "",
            "    async def delete(self, key: str, tenant_id: Optional[str] = None) -> bool:",
            "        return delete_file(key, tenant_id=tenant_id or self.tenant_id)",
            "",
            "    async def get_presigned_url(",
            "        self, key: str, expiration: int = 3600, tenant_id: Optional[str] = None,",
            "    ) -> str:",
            "        return get_presigned_url(key, expiration, tenant_id=tenant_id or self.tenant_id)",
        ])
        return "\n".join(lines)

    # =========================================================================
    # Media Transform Service
    # =========================================================================

    def _emit_media_transform_service(self, collection: FileStorageCollection) -> str:
        """Sinh MediaTransformService — Pillow-based image processing."""
        transform_entries: list[str] = []
        for t in collection.transforms:
            if t.transform_type.value == "resize":
                transform_entries.append(f'    "{t.name}": ("resize", {t.width or 800}, {t.height or 600}, {t.quality}),')
            elif t.transform_type.value == "thumbnail":
                transform_entries.append(f'    "{t.name}": ("thumbnail", {t.width or 100}, {t.height or 100}, {t.quality}),')
            elif t.transform_type.value == "transcode":
                fmt = t.format or "jpeg"
                transform_entries.append(f'    "{t.name}": ("transcode", None, None, {t.quality}, "{fmt}"),')

        lines: list[str] = [
            "# coding: utf-8",
            '"""',
            "Media Transform Service cho FastAPI - Auto-generated by Midicoder CE.",
            "Cung cấp: Image resize/thumbnail (Pillow), format transcode",
            "CP11: File Storage & Media",
            '"""',
            "",
            "import io",
            "from typing import Optional",
            "",
            "from PIL import Image",
            "",
            "",
            "ALLOWED_IMAGE_FORMATS = {'JPEG', 'PNG', 'WEBP', 'GIF'}",
            "DEFAULT_QUALITY = 80",
            "",
            "",
            "TRANSFORMS = {",
        ]
        lines.extend(transform_entries)
        lines.extend([
            "}",
            "",
            "",
            "class MediaTransformService:",
            '    """Service cho media processing operations."""',
            "",
            "    def resize_image(",
            "        self, image_bytes: bytes, width: int, height: int, quality: int = DEFAULT_QUALITY,",
            "    ) -> bytes:",
            '        """Resize image."""',
            "        img = Image.open(io.BytesIO(image_bytes))",
            '        if img.mode in ("RGBA", "P"):',
            '            img = img.convert("RGB")',
            "        img = img.resize((width, height), Image.LANCZOS)",
            "        output = io.BytesIO()",
            "        img.save(output, format='JPEG', quality=quality)",
            "        return output.getvalue()",
            "",
            "    def create_thumbnail(",
            "        self, image_bytes: bytes, size: int = 100, quality: int = DEFAULT_QUALITY,",
            "    ) -> bytes:",
            '        """Tạo thumbnail cố định kích cỡ."""',
            "        img = Image.open(io.BytesIO(image_bytes))",
            '        if img.mode in ("RGBA", "P"):',
            '            img = img.convert("RGB")',
            "        img.thumbnail((size, size), Image.LANCZOS)",
            "        output = io.BytesIO()",
            "        img.save(output, format='JPEG', quality=quality)",
            "        return output.getvalue()",
            "",
            "    def transcode_image(",
            "        self, image_bytes: bytes, output_format: str = 'JPEG', quality: int = DEFAULT_QUALITY,",
            "    ) -> bytes:",
            '        """Chuyển đổi format của image."""',
            "        fmt = output_format.upper()",
            '        if fmt not in ALLOWED_IMAGE_FORMATS:',
            "            raise ValueError(f'Unsupported format: {fmt}')",
            "        img = Image.open(io.BytesIO(image_bytes))",
            '        if fmt == "JPEG" and img.mode in ("RGBA", "P"):',
            '            img = img.convert("RGB")',
            "        output = io.BytesIO()",
            "        save_kwargs = {'format': fmt}",
            '        if fmt in ("JPEG", "WEBP"):',
            "            save_kwargs['quality'] = quality",
            "        img.save(output, **save_kwargs)",
            "        return output.getvalue()",
            "",
            "    def apply_transform(self, image_bytes: bytes, transform_name: str) -> bytes:",
            '        """Apply transform theo config."""',
            "        config = TRANSFORMS.get(transform_name)",
            "        if not config:",
            "            raise ValueError(f'Transform not found: {transform_name}')",
            "        t_type = config[0]",
            '        if t_type == "resize":',
            "            return self.resize_image(image_bytes, config[1], config[2], config[3])",
            '        elif t_type == "thumbnail":',
            "            return self.create_thumbnail(image_bytes, config[1], config[3])",
            '        elif t_type == "transcode":',
            "            return self.transcode_image(image_bytes, config[4], config[3])",
            "        raise ValueError(f'Unknown transform type: {t_type}')",
        ])
        return "\n".join(lines)

    # =========================================================================
    # Storage Router
    # =========================================================================

    def _emit_storage_router(self, collection: FileStorageCollection) -> str:
        """Sinh Storage router với FastAPI routes."""
        policy_names = " / ".join(p.name for p in collection.policies) if collection.policies else "default"

        lines: list[str] = [
            "# coding: utf-8",
            '"""',
            "Storage Router cho FastAPI - Auto-generated by Midicoder CE.",
            "Cung cấp: /upload, /download, /delete, /presigned-endpoints",
            "Obligation: UploadPolicy validation mandatory",
            "KPI-029: Tenant Isolation",
            "CP11: File Storage & Media",
            '"""',
            "",
            "from typing import Optional",
            "",
            "from fastapi import APIRouter, UploadFile, File, Query",
            "",
            "from .file_upload_service import FileUploadService",
            "",
            "",
            'router = APIRouter(prefix="/api/storage", tags=["storage"])',
            "",
            "",
            '@router.post("/upload")',
            "async def upload_file(",
            "    file: UploadFile = File(...),",
            '    folder: str = Query("uploads"),',
            f'    policy: str = Query("{policy_names}"),',
            '    tenant_id: Optional[str] = Query(None),',
            ") -> dict:",
            '    """Upload file với policy enforcement."""',
            "    service = FileUploadService(tenant_id=tenant_id)",
            "    return await service.upload(file, folder=folder, policy_name=policy, tenant_id=tenant_id)",
            "",
            "",
            '@router.get("/download/{key}")',
            "async def download_file(",
            "    key: str,",
            '    tenant_id: Optional[str] = Query(None),',
            ") -> bytes:",
            "    service = FileUploadService(tenant_id=tenant_id)",
            "    return await service.download(key, tenant_id=tenant_id)",
            "",
            "",
            '@router.delete("/delete/{key}")',
            "async def delete_file(",
            "    key: str,",
            '    tenant_id: Optional[str] = Query(None),',
            ") -> dict:",
            "    service = FileUploadService(tenant_id=tenant_id)",
            "    success = await service.delete(key, tenant_id=tenant_id)",
            "    return {'success': success, 'key': key}",
            "",
            "",
            '@router.get("/presigned/{key}")',
            "async def get_presigned_url(",
            "    key: str,",
            "    expiration: int = Query(3600),",
            '    tenant_id: Optional[str] = Query(None),',
            ") -> dict:",
            "    service = FileUploadService(tenant_id=tenant_id)",
            "    url = await service.get_presigned_url(key, expiration, tenant_id=tenant_id)",
            "    return {'url': url, 'key': key, 'expiration': expiration}",
        ]
        return "\n".join(lines)
