# coding: utf-8
"""
NestJS File Storage Emitter (CP11).

Module này chứa NestJSFileStorageEmitter để sinh file storage code
cho NestJS từ FileStorageCollection.

Tạo ra:
- S3Module với tenant-aware S3 client (KPI-029)
- FileUploadService với UploadPolicy enforcement
- MediaTransformService sử dụng Sharp cho image processing
- FileUploadController với REST endpoints

KPI-029: Tenant Isolation - tenant_isolation=True mặc định
Obligation: UploadPolicy validation mandatory trên mọi file upload

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.emitters.core.cp11_file_media.models import (
    FileStorageCollection,
    StorageBackend,
    TransformType,
)


@dataclass
class NestJSFileStorageEmitter:
    """
    Emitter để sinh file storage code cho NestJS.

    Render storage module, upload service, media transform service,
    và file upload controller từ FileStorageCollection sang TypeScript files.

    KPI-029: Tenant isolation qua key prefix.
    Obligation: UploadPolicy enforcement mandatory.
    """

    stack_dir: Path

    def generate(
        self,
        collection: FileStorageCollection,
        output_dir: Path,
    ) -> dict[str, str]:
        """
        Sinh tất cả file storage files cho NestJS.

        Args:
            collection: Collection chứa storage profiles, policies, transforms
            output_dir: Thư mục đầu ra để ghi files

        Returns:
            Dictionary {relative_path: content} của tất cả files được sinh ra
        """
        files: dict[str, str] = {}

        if not collection.profiles:
            return files

        # Xác định backends được sử dụng
        backends = {p.backend_type for p in collection.profiles}

        if StorageBackend.S3 in backends:
            # Sinh S3 module
            files["storage/s3.module.ts"] = self._emit_s3_module(collection)

        # Sinh file upload service
        files["storage/file-upload.service.ts"] = self._emit_file_upload_service(collection)

        # Sinh media transform service
        has_image_transforms = any(
            t.transform_type in (TransformType.RESIZE, TransformType.THUMBNAIL)
            for t in collection.transforms
        )
        if has_image_transforms:
            files["storage/media-transform.service.ts"] = self._emit_media_transform_service(collection)

        # Sinh file upload controller
        files["storage/file-upload.controller.ts"] = self._emit_file_upload_controller(collection)

        # Sinh storage module
        files["storage/storage.module.ts"] = self._emit_storage_module(collection)

        return files

    # =========================================================================
    # S3 Module
    # =========================================================================

    def _emit_s3_module(self, collection: FileStorageCollection) -> str:
        """
        Sinh S3Module với tenant-aware S3 client factory.

        Tạo NestJS module có:
        - S3_CLIENT factory provider (shared cho tất cả tenants)
        - Tenant-specific S3 client factory (optional, KPI-029)
        - Helper functions cho tenant bucket name và key prefix

        Args:
            collection: Collection chứa storage profiles

        Returns:
            Nội dung của s3.module.ts
        """
        s3_profiles = collection.s3_profiles()
        default_profile = s3_profiles[0] if s3_profiles else None

        lines: list[str] = [
            "/**",
            " * S3 Module cho NestJS - Auto-generated by Midicoder CE.",
            " *",
            " * Cấu hình AWS S3 client với tenant-aware configuration.",
            " *",
            " * KPI-029: Tenant Isolation - Support tenant-specific S3 configuration",
            " * CP11: File Storage & Media",
            " */",
            "",
            "import { Global, Module } from '@nestjs/common';",
            "import { config } from 'dotenv';",
            "import * as AWS from '@aws-sdk/client-s3';",
            "",
            "// Load environment variables",
            "config();",
            "",
            "",
            "/**",
            " * S3 Client Factory - shared client cho tất cả tenants.",
            " *",
            " * KPI-029: Tenant-specific logic được xử lý ở service layer",
            " * với folder prefix để isolate data theo tenant.",
            " */",
            "export const s3ClientFactory = {",
            '  provide: "S3_CLIENT",',
            "  useFactory: () => {",
            "    return new AWS.S3Client({",
            '      region: process.env.AWS_REGION || "us-east-1",',
            "      credentials:",
            "        process.env.AWS_ACCESS_KEY_ID && process.env.AWS_SECRET_ACCESS_KEY",
            "          ? {",
            "              accessKeyId: process.env.AWS_ACCESS_KEY_ID,",
            "              secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,",
            "            }",
            "          : undefined,",
            "      endpoint: process.env.AWS_ENDPOINT_URL || undefined,",
            "      maxAttempts: 3,",
            "      requestHandler: new AWS.NodeHttpHandler({",
            "        connectionTimeout: 30000,",
            "        requestTimeout: 60000,",
            "      }),",
            "    });",
            "  },",
            "};",
            "",
            "",
            "/**",
            " * KPI-029: S3 client factory cho tenant cụ thể.",
            " *",
            " * Tạo S3 client riêng cho tenant nếu cần dedicated connection.",
            " *",
            " * @param tenantId - ID của tenant",
            " * @returns S3 client factory",
            " */",
            "export const tenantS3ClientFactory = (tenantId: string) => ({",
            "  provide: `TENANT_S3_CLIENT_${tenantId}`,",
            "  useFactory: () => {",
            "    // KPI-029: Tạo S3 client riêng cho tenant",
            "    return new AWS.S3Client({",
            '      region: process.env.AWS_REGION || "us-east-1",',
            "      credentials:",
            "        process.env.AWS_ACCESS_KEY_ID && process.env.AWS_SECRET_ACCESS_KEY",
            "          ? {",
            "              accessKeyId: process.env.AWS_ACCESS_KEY_ID,",
            "              secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,",
            "            }",
            "          : undefined,",
            "      endpoint: process.env.AWS_ENDPOINT_URL || undefined,",
            "      maxAttempts: 3,",
            "      requestHandler: new AWS.NodeHttpHandler({",
            "        connectionTimeout: 30000,",
            "        requestTimeout: 60000,",
            "      }),",
            "    });",
            "  },",
            "});",
            "",
            "",
            "#region S3 Profile Configuration",
        ]

        # Sinh config cho từng S3 profile
        if s3_profiles:
            for profile in s3_profiles:
                env_prefix = profile.name.upper()
                endpoint_val = repr(profile.endpoint_url) if profile.endpoint_url else "undefined"
                lines.extend([
                    "",
                    f"// Profile: {profile.name} - {profile.description}",
                    f"export const {env_prefix}_BUCKET = process.env.{env_prefix}_BUCKET || '{profile.bucket or ''}';",
                    f"export const {env_prefix}_REGION = process.env.{env_prefix}_REGION || '{profile.region}';",
                    f"export const {env_prefix}_ENDPOINT_URL = process.env.{env_prefix}_ENDPOINT_URL || {endpoint_val};",
                ])

        # Default bucket
        default_bucket = default_profile.bucket if default_profile else "uploads"
        lines.extend([
            "",
            "// Default S3 bucket",
            f'export const DEFAULT_BUCKET = process.env.S3_BUCKET || "{default_bucket}";',
            "",
            "",
            "#endregion",
            "",
            "",
            "/**",
            " * KPI-029: Tenant-specific bucket name helper.",
            " *",
            " * @param tenantId - Tenant ID",
            " * @returns Tenant bucket name với prefix",
            " */",
            "export const getTenantBucketName = (tenantId: string): string => {",
            '  const prefix = process.env.S3_TENANT_BUCKET_PREFIX || "tenant";',
            "  return `${prefix}-${tenantId}`;",
            "};",
            "",
            "",
            "/**",
            " * KPI-029: Tenant-specific key prefix helper.",
            " *",
            " * @param tenantId - Tenant ID",
            " * @returns Tenant key prefix",
            " */",
            "export const getTenantKeyPrefix = (tenantId: string): string => {",
            '  const prefix = process.env.S3_TENANT_KEY_PREFIX || "tenant";',
            "  return `${prefix}/${tenantId}/`;",
            "};",
            "",
            "",
            "/**",
            " * S3 Module - Global module cung cấp S3 client.",
            " *",
            " * KPI-029: Module cung cấp:",
            " * - S3 client (shared cho tất cả tenants)",
            " * - Tenant-specific S3 clients (optional)",
            " * - Tenant-specific bucket/key prefix utilities",
            " */",
            "@Global()",
            "@Module({",
            "  providers: [s3ClientFactory],",
            "  exports: [s3ClientFactory],",
            "})",
            "export class S3Module {",
            "  /**",
            "   * KPI-029: Tạo module cho tenant cụ thể.",
            "   *",
            "   * @param tenantId - ID của tenant",
            "   * @returns Module config cho tenant-specific S3 service",
            "   */",
            "  static forTenant(tenantId: string) {",
            "    return {",
            "      module: S3Module,",
            "      global: false,",
            "      providers: [",
            "        tenantS3ClientFactory(tenantId),",
            "      ],",
            "      exports: [",
            "        tenantS3ClientFactory(tenantId),",
            "      ],",
            "    };",
            "  }",
            "}",
            "",
        ])

        return "\n".join(lines)

    # =========================================================================
    # File Upload Service
    # =========================================================================

    def _emit_file_upload_service(self, collection: FileStorageCollection) -> str:
        """
        Sinh FileUploadService với UploadPolicy enforcement.

        Tạo NestJS service có các phương thức:
        - uploadImage, uploadVideo, uploadDocument với policy validation
        - deleteFile, getFile, getPresignedUrl
        - validateAgainstPolicy (Obligation enforcement)
        - deleteTenantFiles (KPI-029)

        Args:
            collection: Collection chứa storage profiles và upload policies

        Returns:
            Nội dung của file-upload.service.ts
        """
        policies = collection.policies

        lines: list[str] = [
            "/**",
            " * File Upload Service cho NestJS - Auto-generated by Midicoder CE.",
            " *",
            " * Cung cấp:",
            " * - File upload handling với validation",
            " * - UploadPolicy enforcement (Obligation mandatory)",
            " * - S3 integration",
            " *",
            " * Obligation: UploadPolicy validation mandatory trên mọi file upload",
            " * KPI-029: Tenant Isolation - tenant-specific folder prefix",
            " * CP11: File Storage & Media",
            " */",
            "",
            "import {",
            "  Injectable, Inject, BadRequestException, Logger,",
            "} from '@nestjs/common';",
            "import { v4 as uuidv4 } from 'uuid';",
            "import * as AWS from '@aws-sdk/client-s3';",
            "import { PutObjectCommand, DeleteObjectCommand, GetObjectCommand } from '@aws-sdk/client-s3';",
            "import { getSignedUrl } from '@aws-sdk/s3-request-presigner';",
            "",
            "",
            "// Allowed content types",
            'const ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/gif", "image/webp"];',
            'const ALLOWED_VIDEO_TYPES = ["video/mp4", "video/webm"];',
            'const ALLOWED_DOCUMENT_TYPES = ["application/pdf", "application/msword",',
            '  "application/vnd.openxmlformats-officedocument.wordprocessingml.document"];',
            "",
            "// Max file sizes (bytes)",
            "const MAX_IMAGE_SIZE = 10 * 1024 * 1024; // 10MB",
            "const MAX_VIDEO_SIZE = 100 * 1024 * 1024; // 100MB",
            "const MAX_DOCUMENT_SIZE = 10 * 1024 * 1024; // 10MB",
            "",
            "// KPI-029: Tenant folder prefix settings",
            'const STORAGE_TENANT_PREFIX = process.env.STORAGE_TENANT_PREFIX || "tenant";',
            'const STORAGE_TENANT_ISOLATION = (process.env.STORAGE_TENANT_ISOLATION || "true").toLowerCase() === "true";',
            "",
            "",
        ]

        # Sinh UploadPolicy interface và lookup
        if policies:
            lines.extend([
                "/**",
                " * Interface cho upload policy config.",
                " */",
                "export interface UploadPolicyConfig {",
                "  allowedContentTypes: string[];",
                "  maxFileSize: number;",
                "  allowedExtensions: string[];",
                "}",
                "",
                "",
                "// UploadPolicy lookup dictionary - auto-generated",
                "const UPLOAD_POLICIES: Record<string, UploadPolicyConfig> = {",
            ])
            for policy in policies:
                lines.append(f"  \"{policy.name}\": {{")
                lines.append(f"    allowedContentTypes: {policy.allowed_content_types},")
                lines.append(f"    maxFileSize: {policy.max_file_size},")
                lines.append(f"    allowedExtensions: {policy.allowed_extensions},")
                lines.append("  },")
            lines.extend([
                "};",
                "",
                "",
            ])

        lines.extend([
            "/**",
            " * File Upload Service.",
            " *",
            " * Obligation: Mọi file upload PHẢI qua policy validation.",
            " * KPI-029: Hỗ trợ tenant-specific folder prefix để isolate files.",
            " */",
            "@Injectable()",
            "export class FileUploadService {",
            "  private readonly logger = new Logger(FileUploadService.name);",
            "",
            "  private readonly bucket = process.env.S3_BUCKET || 'uploads';",
            "",
            "  constructor(",
            '    @Inject("S3_CLIENT")',
            "    private readonly s3Client: AWS.S3Client,",
            "    private readonly tenantId?: string,",
            "    private readonly defaultPolicy?: string,",
            "  ) {}",
            "",
            "",
            "  /**",
            "   * KPI-029: Tạo folder path với tenant prefix.",
            "   *",
            "   * @param folder - Folder gốc",
            "   * @param tenantId - Tenant ID (override instance tenantId)",
            "   * @returns Folder path với tenant prefix",
            "   */",
            "  private getTenantFolder(folder: string, tenantId?: string): string {",
            "    const effectiveTenantId = tenantId || this.tenantId;",
            "    if (STORAGE_TENANT_ISOLATION && effectiveTenantId) {",
            "      return `${STORAGE_TENANT_PREFIX}/${effectiveTenantId}/${folder}`;",
            "    }",
            "    return folder;",
            "  }",
            "",
            "",
            "  /**",
            "   * Trích xuất extension từ filename.",
            "   *",
            "   * @param filename - Tên file",
            "   * @returns Extension không có dấu chấm",
            "   */",
            "  private getExtension(filename: string): string {",
            "    return filename.includes('.') ? filename.split('.').pop() || '' : '';",
            "  }",
            "",
            "",
            "  /**",
            "   * Obligation: Validate file upload theo UploadPolicy.",
            "   *",
            "   * Mọi file upload PHẢI qua validation này. Nếu policy name không",
            "   * được chỉ định, sẽ dùng defaultPolicy của instance.",
            "   *",
            "   * @param contentType - MIME type của file",
            "   * @param fileSize - Kích thước file (bytes)",
            "   * @param extension - Extension của file",
            "   * @param policyName - Tên UploadPolicy để enforce",
            "   * @throws BadRequestException nếu vi phạm policy",
            "   */",
            "  private validateAgainstPolicy(",
            "    contentType: string,",
            "    fileSize: number,",
            "    extension: string,",
            "    policyName?: string,",
            "  ): void {",
            "    const effectivePolicy = policyName || this.defaultPolicy;",
            "",
            "    // Obligation: Nếu có policy, enforce strict validation",
            "    if (effectivePolicy && UPLOAD_POLICIES[effectivePolicy]) {",
            "      const policy = UPLOAD_POLICIES[effectivePolicy];",
            "",
            "      // Content-type check",
            "      if (!policy.allowedContentTypes.includes(contentType)) {",
            "        throw new BadRequestException(",
            "          `Content type '${contentType}' không được phép theo policy '${effectivePolicy}'.`,",
            "        );",
            "      }",
            "",
            "      // Size check",
            "      if (fileSize > policy.maxFileSize) {",
            "        throw new BadRequestException(",
            "          `File quá lớn: ${fileSize} bytes. Limit theo policy '${effectivePolicy}': ${policy.maxFileSize} bytes`,",
            "        );",
            "      }",
            "",
            "      // Extension check",
            "      if (!policy.allowedExtensions.includes(extension)) {",
            "        throw new BadRequestException(",
            "          `Extension '.${extension}' không được phép theo policy '${effectivePolicy}'.`,",
            "        );",
            "      }",
            "",
            "      this.logger.log(`[UploadPolicy] PASSED: ${effectivePolicy} for ${extension}`);",
            "      return;",
            "    }",
            "",
            "    // Fallback: validate theo content type groups",
            "    if (ALLOWED_IMAGE_TYPES.includes(contentType) && fileSize > MAX_IMAGE_SIZE) {",
            "      throw new BadRequestException(`Image quá lớn. Max: ${MAX_IMAGE_SIZE / 1024 / 1024}MB`);",
            "    }",
            "    if (ALLOWED_VIDEO_TYPES.includes(contentType) && fileSize > MAX_VIDEO_SIZE) {",
            "      throw new BadRequestException(`Video quá lớn. Max: ${MAX_VIDEO_SIZE / 1024 / 1024}MB`);",
            "    }",
            "    if (ALLOWED_DOCUMENT_TYPES.includes(contentType) && fileSize > MAX_DOCUMENT_SIZE) {",
            "      throw new BadRequestException(`Document quá lớn. Max: ${MAX_DOCUMENT_SIZE / 1024 / 1024}MB`);",
            "    }",
            "  }",
            "",
            "",
            "  /**",
            "   * Upload image file với validation và policy enforcement.",
            "   *",
            "   * KPI-029: Support tenant-specific folder prefix.",
            "   *",
            "   * @param buffer - File buffer",
            "   * @param filename - Original filename",
            "   * @param contentType - Content type",
            "   * @param folder - Storage folder",
            "   * @param policyName - Tên UploadPolicy để enforce",
            "   * @param tenantId - KPI-029: Tenant ID",
            "   * @returns Upload result",
            "   */",
            "  async uploadImage(",
            "    buffer: Buffer,",
            "    filename: string,",
            "    contentType: string,",
            "    folder: string = 'images',",
            "    policyName?: string,",
            "    tenantId?: string,",
            "  ): Promise<{ key: string; url: string; size: number; tenantId?: string }> {",
            "    if (!ALLOWED_IMAGE_TYPES.includes(contentType)) {",
            "      throw new BadRequestException(`Unsupported image type: ${contentType}`);",
            "    }",
            "",
            "    // Obligation: Policy validation",
            "    const ext = this.getExtension(filename);",
            "    this.validateAgainstPolicy(contentType, buffer.length, ext, policyName);",
            "",
            "    // KPI-029: Use tenant-specific folder",
            "    const tenantFolder = this.getTenantFolder(folder, tenantId);",
            "    const key = `${tenantFolder}/${uuidv4()}.${ext || 'jpg'}`;",
            "",
            "    await this.s3Client.send(",
            "      new PutObjectCommand({",
            "        Bucket: this.bucket,",
            "        Key: key,",
            "        Body: buffer,",
            "        ContentType: contentType,",
            "      }),",
            "    );",
            "",
            '    const region = process.env.AWS_REGION || "us-east-1";',
            "    const url = `https://${this.bucket}.s3.${region}.amazonaws.com/${key}`;",
            "",
            "    this.logger.log(`[Upload] Image uploaded: ${key} (${buffer.length} bytes)`);",
            "",
            "    return { key, url, size: buffer.length, tenantId: tenantId || this.tenantId };",
            "  }",
            "",
            "",
            "  /**",
            "   * Upload video file với validation và policy enforcement.",
            "   *",
            "   * KPI-029: Support tenant-specific folder prefix.",
            "   *",
            "   * @param buffer - File buffer",
            "   * @param filename - Original filename",
            "   * @param contentType - Content type",
            "   * @param folder - Storage folder",
            "   * @param policyName - Tên UploadPolicy để enforce",
            "   * @param tenantId - KPI-029: Tenant ID",
            "   * @returns Upload result",
            "   */",
            "  async uploadVideo(",
            "    buffer: Buffer,",
            "    filename: string,",
            "    contentType: string,",
            "    folder: string = 'videos',",
            "    policyName?: string,",
            "    tenantId?: string,",
            "  ): Promise<{ key: string; url: string; size: number; tenantId?: string }> {",
            "    if (!ALLOWED_VIDEO_TYPES.includes(contentType)) {",
            "      throw new BadRequestException(`Unsupported video type: ${contentType}`);",
            "    }",
            "",
            "    // Obligation: Policy validation",
            "    const ext = this.getExtension(filename);",
            "    this.validateAgainstPolicy(contentType, buffer.length, ext, policyName);",
            "",
            "    // KPI-029: Use tenant-specific folder",
            "    const tenantFolder = this.getTenantFolder(folder, tenantId);",
            "    const key = `${tenantFolder}/${uuidv4()}.${ext || 'mp4'}`;",
            "",
            "    await this.s3Client.send(",
            "      new PutObjectCommand({",
            "        Bucket: this.bucket,",
            "        Key: key,",
            "        Body: buffer,",
            "        ContentType: contentType,",
            "      }),",
            "    );",
            "",
            '    const region = process.env.AWS_REGION || "us-east-1";',
            "    const url = `https://${this.bucket}.s3.${region}.amazonaws.com/${key}`;",
            "",
            "    this.logger.log(`[Upload] Video uploaded: ${key} (${buffer.length} bytes)`);",
            "",
            "    return { key, url, size: buffer.length, tenantId: tenantId || this.tenantId };",
            "  }",
            "",
            "",
            "  /**",
            "   * Upload document file với validation và policy enforcement.",
            "   *",
            "   * KPI-029: Support tenant-specific folder prefix.",
            "   *",
            "   * @param buffer - File buffer",
            "   * @param filename - Original filename",
            "   * @param contentType - Content type",
            "   * @param folder - Storage folder",
            "   * @param policyName - Tên UploadPolicy để enforce",
            "   * @param tenantId - KPI-029: Tenant ID",
            "   * @returns Upload result",
            "   */",
            "  async uploadDocument(",
            "    buffer: Buffer,",
            "    filename: string,",
            "    contentType: string,",
            "    folder: string = 'documents',",
            "    policyName?: string,",
            "    tenantId?: string,",
            "  ): Promise<{ key: string; url: string; size: number; tenantId?: string }> {",
            "    if (!ALLOWED_DOCUMENT_TYPES.includes(contentType)) {",
            "      throw new BadRequestException(`Unsupported document type: ${contentType}`);",
            "    }",
            "",
            "    // Obligation: Policy validation",
            "    const ext = this.getExtension(filename);",
            "    this.validateAgainstPolicy(contentType, buffer.length, ext, policyName);",
            "",
            "    // KPI-029: Use tenant-specific folder",
            "    const tenantFolder = this.getTenantFolder(folder, tenantId);",
            "    const key = `${tenantFolder}/${uuidv4()}.${ext || 'pdf'}`;",
            "",
            "    await this.s3Client.send(",
            "      new PutObjectCommand({",
            "        Bucket: this.bucket,",
            "        Key: key,",
            "        Body: buffer,",
            "        ContentType: contentType,",
            "      }),",
            "    );",
            "",
            '    const region = process.env.AWS_REGION || "us-east-1";',
            "    const url = `https://${this.bucket}.s3.${region}.amazonaws.com/${key}`;",
            "",
            "    this.logger.log(`[Upload] Document uploaded: ${key} (${buffer.length} bytes)`);",
            "",
            "    return { key, url, size: buffer.length, tenantId: tenantId || this.tenantId };",
            "  }",
            "",
            "",
            "  /**",
            "   * Xóa file từ S3.",
            "   *",
            "   * @param key - File key",
            "   * @param tenantId - KPI-029: Tenant ID (optional)",
            "   * @returns True nếu xóa thành công",
            "   */",
            "  async deleteFile(key: string, tenantId?: string): Promise<boolean> {",
            "    // KPI-029: Add tenant prefix if not present",
            "    const effectiveTenantId = tenantId || this.tenantId;",
            "    let targetKey = key;",
            "    if (STORAGE_TENANT_ISOLATION && effectiveTenantId &&",
            "        !key.startsWith(`${STORAGE_TENANT_PREFIX}/`)) {",
            "      targetKey = `${STORAGE_TENANT_PREFIX}/${effectiveTenantId}/${key}`;",
            "    }",
            "",
            "    await this.s3Client.send(",
            "      new DeleteObjectCommand({",
            "        Bucket: this.bucket,",
            "        Key: targetKey,",
            "      }),",
            "    );",
            "    this.logger.log(`[Delete] File deleted: ${targetKey}`);",
            "    return true;",
            "  }",
            "",
            "",
            "  /**",
            "   * Download file từ S3.",
            "   *",
            "   * @param key - File key",
            "   * @param tenantId - KPI-029: Tenant ID (optional)",
            "   * @returns File buffer",
            "   */",
            "  async getFile(key: string, tenantId?: string): Promise<Buffer> {",
            "    // KPI-029: Add tenant prefix if not present",
            "    const effectiveTenantId = tenantId || this.tenantId;",
            "    let targetKey = key;",
            "    if (STORAGE_TENANT_ISOLATION && effectiveTenantId &&",
            "        !key.startsWith(`${STORAGE_TENANT_PREFIX}/`)) {",
            "      targetKey = `${STORAGE_TENANT_PREFIX}/${effectiveTenantId}/${key}`;",
            "    }",
            "",
            "    const response = await this.s3Client.send(",
            "      new GetObjectCommand({",
            "        Bucket: this.bucket,",
            "        Key: targetKey,",
            "      }),",
            "    );",
            "",
            "    const body = response.Body;",
            "    if (body instanceof Uint8Array) {",
            "      return Buffer.from(body);",
            "    }",
            "",
            "    // Stream to Buffer",
            "    const chunks: Buffer[] = [];",
            "    for await (const chunk of body as AsyncIterable<Buffer>) {",
            "      chunks.push(Buffer.from(chunk));",
            "    }",
            "    return Buffer.concat(chunks);",
            "  }",
            "",
            "",
            "  /**",
            "   * Generate presigned URL cho file.",
            "   *",
            "   * KPI-029: Add tenant prefix nếu key không có.",
            "   *",
            "   * @param key - File key",
            "   * @param expiration - Thời gian hiệu lực (giây)",
            "   * @param tenantId - KPI-029: Tenant ID (optional)",
            "   * @returns Presigned URL string",
            "   */",
            "  async getPresignedUrl(",
            "    key: string,",
            "    expiration: number = 3600,",
            "    tenantId?: string,",
            "  ): Promise<string> {",
            "    // KPI-029: Add tenant prefix if not present",
            "    const effectiveTenantId = tenantId || this.tenantId;",
            "    let targetKey = key;",
            "    if (STORAGE_TENANT_ISOLATION && effectiveTenantId &&",
            "        !key.startsWith(`${STORAGE_TENANT_PREFIX}/`)) {",
            "      targetKey = `${STORAGE_TENANT_PREFIX}/${effectiveTenantId}/${key}`;",
            "    }",
            "",
            "    const command = new GetObjectCommand({",
            "      Bucket: this.bucket,",
            "      Key: targetKey,",
            "    });",
            "",
            "    return getSignedUrl(this.s3Client, command, { expiresIn: expiration });",
            "  }",
            "",
            "",
            "  /**",
            "   * KPI-029: Xóa tất cả files của một tenant.",
            "   *",
            "   * @param tenantId - ID của tenant cần cleanup",
            "   * @param folder - Folder cụ thể (undefined = xóa tất cả)",
            "   * @returns Deletion result",
            "   */",
            "  async deleteTenantFiles(",
            "    tenantId: string,",
            "    folder?: string,",
            "  ): Promise<{ tenantId: string; prefix: string; deletedCount: number }> {",
            "    const prefix = folder",
            "      ? `${STORAGE_TENANT_PREFIX}/${tenantId}/${folder}`",
            "      : `${STORAGE_TENANT_PREFIX}/${tenantId}`;",
            "",
            "    // List and delete all objects with tenant prefix",
            "    const { ListObjectsV2Command } = await import('@aws-sdk/client-s3');",
            "    const { DeleteObjectsCommand } = await import('@aws-sdk/client-s3');",
            "",
            "    let deletedCount = 0;",
            "    let continuationToken: string | undefined;",
            "",
            "    do {",
            "      const listResponse = await this.s3Client.send(",
            "        new ListObjectsV2Command({",
            "          Bucket: this.bucket,",
            "          Prefix: prefix,",
            "          ContinuationToken: continuationToken,",
            "        }),",
            "      );",
            "",
            "      const objects = listResponse.Contents || [];",
            "      if (objects.length > 0) {",
            "        await this.s3Client.send(",
            "          new DeleteObjectsCommand({",
            "            Bucket: this.bucket,",
            "            Delete: { Objects: objects.map(obj => ({ Key: obj.Key })) },",
            "          }),",
            "        );",
            "        deletedCount += objects.length;",
            "      }",
            "",
            "      continuationToken = listResponse.NextContinuationToken;",
            "    } while (continuationToken);",
            "",
            "    this.logger.log(`[DeleteTenant] Deleted ${deletedCount} files for tenant ${tenantId}`);",
            "",
            "    return { tenantId, prefix, deletedCount };",
            "  }",
            "",
            "}",
            "",
        ])

        return "\n".join(lines)

    # =========================================================================
    # Media Transform Service
    # =========================================================================

    def _emit_media_transform_service(self, collection: FileStorageCollection) -> str:
        """
        Sinh MediaTransformService sử dụng Sharp cho image processing.

        Tạo NestJS service có các phương thức:
        - resizeImage: Resize ảnh theo kích thước target
        - createThumbnail: Tạo thumbnail với aspect ratio preserved
        - optimizeImage: Tối ưu hóa ảnh
        - convertFormat: Chuyển đổi format ảnh

        Sử dụng Sharp (thay vì Pillow) vì đây là thư viện xử lý ảnh
        phổ biến và hiệu năng cao cho Node.js.

        Args:
            collection: Collection chứa media transforms

        Returns:
            Nội dung của media-transform.service.ts
        """
        transforms = collection.transforms
        image_transforms = [
            t for t in transforms
            if t.transform_type in (TransformType.RESIZE, TransformType.THUMBNAIL)
        ]

        lines: list[str] = [
            "/**",
            " * Media Transform Service cho NestJS - Auto-generated by Midicoder CE.",
            " *",
            " * Sử dụng Sharp để xử lý ảnh:",
            " * - Resize image theo kích thước target",
            " * - Tạo thumbnail với aspect ratio preserved",
            " * - Chuyển đổi format ảnh",
            " * - Tối ưu hóa chất lượng file",
            " *",
            " * CP11: File Storage & Media",
            " */",
            "",
            "import { Injectable } from '@nestjs/common';",
            "import sharp from 'sharp';",
            "",
            "",
            "// Supported image formats",
            'const SUPPORTED_FORMATS = ["jpeg", "jpg", "png", "gif", "webp", "bmp", "tiff"];',
            "",
            "// Default quality setting",
            "const DEFAULT_QUALITY = 80;",
            "",
            "",
        ]

        # Sinh preset transforms từ collection
        if image_transforms:
            lines.extend([
                "/**",
                " * Interface cho transform preset config.",
                " */",
                "export interface TransformPreset {",
                '  type: "resize" | "thumbnail" | "transcode";',
                "  width?: number;",
                "  height?: number;",
                "  format?: string;",
                "  quality: number;",
                "}",
                "",
                "",
                "// Preset transforms - auto-generated từ MediaTransform collection",
                "export const TRANSFORM_PRESETS: Record<string, TransformPreset> = {",
            ])
            for t in image_transforms:
                lines.append(f"  \"{t.name}\": {{")
                lines.append(f"    type: \"{t.transform_type.value}\" as const,")
                if t.width:
                    lines.append(f"    width: {t.width},")
                if t.height:
                    lines.append(f"    height: {t.height},")
                if t.format:
                    lines.append(f"    format: \"{t.format}\",")
                lines.append(f"    quality: {t.quality},")
                lines.append("  },")
            lines.extend([
                "};",
                "",
                "",
            ])

        lines.extend([
            "/**",
            " * Media Transform Service.",
            " *",
            " * Sử dụng Sharp cho high-performance image operations:",
            " * - Resize: Resize ảnh theo kích thước cụ thể",
            " * - Thumbnail: Tạo thumbnail giữ aspect ratio",
            " * - Transcode: Chuyển đổi format",
            " * - Optimize: Tối ưu hóa chất lượng",
            " */",
            "@Injectable()",
            "export class MediaTransformService {",
            "",
            "  constructor(",
            "    private readonly defaultQuality: number = DEFAULT_QUALITY,",
            "  ) {}",
            "",
            "",
            "  /**",
            "   * Resize image theo kích thước target.",
            "   *",
            "   * @param imageBuffer - Nội dung ảnh dạng Buffer",
            "   * @param width - Width target (pixel)",
            "   * @param height - Height target (pixel)",
            "   * @param quality - Chất lượng output (1-100)",
            "   * @param format - Format output (jpeg, png, webp, v.v.)",
            "   * @param keepAspectRatio - Nếu true, giữ aspect ratio bằng crop center",
            "   * @returns Ảnh đã resize dạng Buffer",
            "   */",
            "  async resizeImage(",
            "    imageBuffer: Buffer,",
            "    width: number,",
            "    height: number,",
            "    quality: number = this.defaultQuality,",
            "    format: string = 'jpeg',",
            "    keepAspectRatio: boolean = false,",
            "  ): Promise<Buffer> {",
            "    let pipeline = sharp(imageBuffer);",
            "",
            "    if (keepAspectRatio) {",
            "      // Giữ aspect ratio: resize để vừa trong bounding box, rồi crop center",
            "      pipeline = pipeline.resize({",
            "        width,",
            "        height,",
            "        fit: 'cover',",
            "        position: 'center',",
            "      });",
            "    } else {",
            "      // Resize trực tiếp theo kích thước target",
            "      pipeline = pipeline.resize(width, height);",
            "    }",
            "",
            "    // Apply format-specific options",
            "    const formatOptions = this.getFormatOptions(format, quality);",
            "",
            "    const [outputBuffer, { format: outputFormat }] = await Promise.all([",
            "      pipeline.toBuffer(),",
            "      pipeline.metadata(),",
            "    ]);",
            "",
            "    // Re-process with correct format",
            "    let finalPipeline = sharp(imageBuffer);",
            "    if (keepAspectRatio) {",
            "      finalPipeline = finalPipeline.resize({ width, height, fit: 'cover', position: 'center' });",
            "    } else {",
            "      finalPipeline = finalPipeline.resize(width, height);",
            "    }",
            "",
            "    return finalPipeline.withMetadata().toFormat(format as any, formatOptions).toBuffer();",
            "  }",
            "",
            "",
            "  /**",
            "   * Tạo thumbnail giữ aspect ratio.",
            "   *",
            "   * Sử dụng Sharp resize với fit: 'inside' để thu nhỏ ảnh",
            "   * mà không phóng to nếu ảnh đã nhỏ hơn kích thước target.",
            "   *",
            "   * @param imageBuffer - Nội dung ảnh dạng Buffer",
            "   * @param maxWidth - Width tối đa (pixel)",
            "   * @param maxHeight - Height tối đa (pixel)",
            "   * @param quality - Chất lượng output (1-100)",
            "   * @param format - Format output",
            "   * @returns Thumbnail dạng Buffer",
            "   */",
            "  async createThumbnail(",
            "    imageBuffer: Buffer,",
            "    maxWidth: number,",
            "    maxHeight: number,",
            "    quality: number = this.defaultQuality,",
            "    format: string = 'jpeg',",
            "  ): Promise<Buffer> {",
            "    const formatOptions = this.getFormatOptions(format, quality);",
            "",
            "    return sharp(imageBuffer)",
            "      .resize({",
            "        width: maxWidth,",
            "        height: maxHeight,",
            "        fit: 'inside',",
            "      })",
            "      .withMetadata()",
            "      .toFormat(format as any, formatOptions)",
            "      .toBuffer();",
            "  }",
            "",
            "",
            "  /**",
            "   * Tối ưu hóa ảnh: resize nếu quá lớn + compression.",
            "   *",
            "   * Nếu ảnh có dimension lớn hơn maxDimension, sẽ resize",
            "   * để vừa với giới hạn trước khi áp dụng compression.",
            "   *",
            "   * @param imageBuffer - Nội dung ảnh dạng Buffer",
            "   * @param maxDimension - Kích thước tối đa cho chiều dài nhất",
            "   * @param quality - Chất lượng compression (1-100)",
            "   * @param format - Format output",
            "   * @returns Ảnh đã tối ưu hóa dạng Buffer",
            "   */",
            "  async optimizeImage(",
            "    imageBuffer: Buffer,",
            "    maxDimension?: number,",
            "    quality: number = this.defaultQuality,",
            "    format: string = 'jpeg',",
            "  ): Promise<Buffer> {",
            "    const metadata = await sharp(imageBuffer).metadata();",
            "    const { width, height } = metadata;",
            "",
            "    let pipeline = sharp(imageBuffer);",
            "",
            "    // Resize nếu quá lớn",
            "    if (maxDimension && (width! > maxDimension || height! > maxDimension)) {",
            "      const ratio = Math.min(maxDimension / width!, maxDimension / height!);",
            "      pipeline = pipeline.resize({",
            "        width: Math.round(width! * ratio),",
            "        height: Math.round(height! * ratio),",
            "      });",
            "    }",
            "",
            "    const formatOptions = this.getFormatOptions(format, quality);",
            "    return pipeline.toFormat(format as any, formatOptions).toBuffer();",
            "  }",
            "",
            "",
            "  /**",
            "   * Chuyển đổi format của ảnh.",
            "   *",
            "   * @param imageBuffer - Nội dung ảnh dạng Buffer",
            "   * @param targetFormat - Format đích (jpeg, png, webp, v.v.)",
            "   * @param quality - Chất lượng output (1-100)",
            "   * @returns Ảnh đã chuyển format dạng Buffer",
            "   */",
            "  async convertFormat(",
            "    imageBuffer: Buffer,",
            "    targetFormat: string = 'jpeg',",
            "    quality: number = this.defaultQuality,",
            "  ): Promise<Buffer> {",
            "    const formatOptions = this.getFormatOptions(targetFormat, quality);",
            "    return sharp(imageBuffer)",
            "      .toFormat(targetFormat as any, formatOptions)",
            "      .toBuffer();",
            "  }",
            "",
            "",
            "  /**",
            "   * Lấy thông tin metadata của ảnh.",
            "   *",
            "   * @param imageBuffer - Nội dung ảnh dạng Buffer",
            "   * @returns Dict chứa width, height, format, space, density",
            "   */",
            "  async getImageInfo(imageBuffer: Buffer): Promise<{",
            "    width: number;",
            "    height: number;",
            "    format: string | undefined;",
            "    space: string | undefined;",
            "    density: number;",
            "    size: number;",
            "  }> {",
            "    const metadata = await sharp(imageBuffer).metadata();",
            "    return {",
            "      width: metadata.width!,",
            "      height: metadata.height!,",
            "      format: metadata.format,",
            "      space: metadata.space,",
            "      density: metadata.density || 72,",
            "      size: imageBuffer.length,",
            "    };",
            "  }",
            "",
            "",
            "  /**",
            "   * Tạo format-specific options cho Sharp.",
            "   *",
            "   * @param format - Format output",
            "   * @param quality - Chất lượng (1-100)",
            "   * @returns Sharp format options",
            "   */",
            "  private getFormatOptions(",
            "    format: string,",
            "    quality: number,",
            "  ): Record<string, any> {",
            "    const lowerFormat = format.toLowerCase();",
            "",
            "    if (lowerFormat === 'jpeg' || lowerFormat === 'jpg') {",
            "      return { quality, mozjpeg: true } as any;",
            "    }",
            "    if (lowerFormat === 'webp') {",
            "      return { quality } as any;",
            "    }",
            "    if (lowerFormat === 'png') {",
            "      return { compressionLevel: 6 } as any;",
            "    }",
            "    return { quality } as any;",
            "  }",
            "",
            "}",
            "",
        ])

        return "\n".join(lines)

    # =========================================================================
    # File Upload Controller
    # =========================================================================

    def _emit_file_upload_controller(self, collection: FileStorageCollection) -> str:
        """
        Sinh FileUploadController với REST endpoints.

        Tạo NestJS controller có các routes:
        - POST /storage/upload/image - Upload ảnh
        - POST /storage/upload/video - Upload video
        - POST /storage/upload/document - Upload tài liệu
        - GET /storage/download/:key - Download file
        - DELETE /storage/delete/:key - Xóa file
        - GET /storage/presigned/:key - Lấy presigned URL
        - POST /storage/transform/resize - Resize ảnh
        - POST /storage/transform/thumbnail - Tạo thumbnail

        Args:
            collection: Collection chứa storage profiles, policies, transforms

        Returns:
            Nội dung của file-upload.controller.ts
        """
        policies = collection.policies
        transforms = collection.transforms
        has_image_transforms = any(
            t.transform_type in (TransformType.RESIZE, TransformType.THUMBNAIL)
            for t in transforms
        )

        lines: list[str] = [
            "/**",
            " * File Upload Controller cho NestJS - Auto-generated by Midicoder CE.",
            " *",
            " * Cung cấp các REST endpoints:",
            " * - POST /storage/upload/image - Upload ảnh",
            " * - POST /storage/upload/video - Upload video",
            " * - POST /storage/upload/document - Upload tài liệu",
            " * - GET /storage/download/:key - Download file",
            " * - DELETE /storage/delete/:key - Xóa file",
            " * - GET /storage/presigned/:key - Lấy presigned URL để download",
        ]

        if has_image_transforms:
            lines.extend([
                " * - POST /storage/transform/resize - Resize ảnh",
                " * - POST /storage/transform/thumbnail - Tạo thumbnail",
            ])

        lines.extend([
            " *",
            " * Obligation: UploadPolicy validation mandatory trên mọi upload",
            " * KPI-029: Tenant Isolation - tenantId qua header x-tenant-id",
            " * CP11: File Storage & Media",
            " */",
            "",
            "import {",
            "  Controller,",
            "  Post,",
            "  Get,",
            "  Delete,",
            "  Body,",
            "  Param,",
            "  Query,",
            "  UploadedFile,",
            "  UseInterceptors,",
            "  BadRequestException,",
            "  Headers,",
            "  Res,",
            "  NotFoundException,",
            "} from '@nestjs/common';",
            "import { FileInterceptor } from '@nestjs/platform-express';",
            "import { Response } from 'express';",
            "import { FileUploadService } from './file-upload.service';",
        ])

        if has_image_transforms:
            lines.append("import { MediaTransformService } from './media-transform.service';")

        lines.extend([
            "",
            "",
            "@Controller('storage')",
            "export class FileUploadController {",
            "",
            "  constructor(",
            "    private readonly fileUploadService: FileUploadService,",
        ])

        if has_image_transforms:
            lines.append("    private readonly mediaTransformService: MediaTransformService,")

        lines.extend([
            "  ) {}",
            "",
            "",
            "  /**",
            "   * KPI-029: Lấy tenantId từ HTTP header.",
            "   *",
            "   * @param xTenantId - Header x-tenant-id",
            "   * @param tenantId - Query param tenantId",
            "   * @returns Tenant ID hoặc undefined",
            "   */",
            "  private getTenantId(",
            '    @Headers("x-tenant-id") xTenantId?: string,',
            "    @Query('tenantId') tenantId?: string,",
            "  ): string | undefined {",
            "    return xTenantId || tenantId;",
            "  }",
            "",
            "",
            "  // =========================================================================",
            "  // Upload Endpoints",
            "  // =========================================================================",
            "",
            "",
            "  /**",
            "   * Upload ảnh với validation và policy enforcement.",
            "   *",
            "   * Obligation: File sẽ được validate theo UploadPolicy.",
            "   * KPI-029: File được lưu với tenant-specific folder prefix.",
            "   */",
            '  @Post("upload/image")',
            '  @UseInterceptors(FileInterceptor("file"))',
            "  async uploadImage(",
            "    @UploadedFile() file: Express.Multer.File,",
            "    @Query('policy') policy?: string,",
            "    @Query('tenantId') tenantId?: string,",
            '    @Headers("x-tenant-id") xTenantId?: string,',
            "  ): Promise<{ key: string; url: string; size: number; tenantId?: string }> {",
            "    if (!file) {",
            "      throw new BadRequestException('Không có file được upload');",
            "    }",
            "    const effectiveTenantId = xTenantId || tenantId;",
            "    return this.fileUploadService.uploadImage(",
            "      file.buffer,",
            "      file.originalname,",
            "      file.mimetype,",
            "      'images',",
            "      policy,",
            "      effectiveTenantId,",
            "    );",
            "  }",
            "",
            "",
            "  /**",
            "   * Upload video với validation và policy enforcement.",
            "   */",
            '  @Post("upload/video")',
            '  @UseInterceptors(FileInterceptor("file"))',
            "  async uploadVideo(",
            "    @UploadedFile() file: Express.Multer.File,",
            "    @Query('policy') policy?: string,",
            "    @Query('tenantId') tenantId?: string,",
            '    @Headers("x-tenant-id") xTenantId?: string,',
            "  ): Promise<{ key: string; url: string; size: number; tenantId?: string }> {",
            "    if (!file) {",
            "      throw new BadRequestException('Không có file được upload');",
            "    }",
            "    const effectiveTenantId = xTenantId || tenantId;",
            "    return this.fileUploadService.uploadVideo(",
            "      file.buffer,",
            "      file.originalname,",
            "      file.mimetype,",
            "      'videos',",
            "      policy,",
            "      effectiveTenantId,",
            "    );",
            "  }",
            "",
            "",
            "  /**",
            "   * Upload tài liệu với validation và policy enforcement.",
            "   */",
            '  @Post("upload/document")',
            '  @UseInterceptors(FileInterceptor("file"))',
            "  async uploadDocument(",
            "    @UploadedFile() file: Express.Multer.File,",
            "    @Query('policy') policy?: string,",
            "    @Query('tenantId') tenantId?: string,",
            '    @Headers("x-tenant-id") xTenantId?: string,',
            "  ): Promise<{ key: string; url: string; size: number; tenantId?: string }> {",
            "    if (!file) {",
            "      throw new BadRequestException('Không có file được upload');",
            "    }",
            "    const effectiveTenantId = xTenantId || tenantId;",
            "    return this.fileUploadService.uploadDocument(",
            "      file.buffer,",
            "      file.originalname,",
            "      file.mimetype,",
            "      'documents',",
            "      policy,",
            "      effectiveTenantId,",
            "    );",
            "  }",
            "",
            "",
            "  // =========================================================================",
            "  // Download Endpoint",
            "  // =========================================================================",
            "",
            "",
            "  /**",
            "   * Download file từ storage theo key.",
            "   *",
            "   * KPI-029: Tự động thêm tenant prefix nếu key không có.",
            "   */",
            '  @Get("download/:key")',
            "  async downloadFile(",
            "    @Param('key') key: string,",
            "    @Query('tenantId') tenantId?: string,",
            '    @Headers("x-tenant-id") xTenantId?: string,',
            "    @Res() res: Response,",
            "  ): Promise<void> {",
            "    const effectiveTenantId = xTenantId || tenantId;",
            "    const buffer = await this.fileUploadService.getFile(key, effectiveTenantId);",
            "    res.setHeader('Content-Type', 'application/octet-stream');",
            "    res.setHeader('Content-Length', buffer.length);",
            "    res.send(buffer);",
            "  }",
            "",
            "",
            "  // =========================================================================",
            "  // Delete Endpoint",
            "  // =========================================================================",
            "",
            "",
            "  /**",
            "   * Xóa file từ storage theo key.",
            "   *",
            "   * KPI-029: Tự động thêm tenant prefix nếu key không có.",
            "   */",
            '  @Delete("delete/:key")',
            "  async deleteFile(",
            "    @Param('key') key: string,",
            "    @Query('tenantId') tenantId?: string,",
            '    @Headers("x-tenant-id") xTenantId?: string,',
            "  ): Promise<{ status: string; key: string }> {",
            "    const effectiveTenantId = xTenantId || tenantId;",
            "    const success = await this.fileUploadService.deleteFile(key, effectiveTenantId);",
            "    return {",
            '      status: success ? "deleted" : "not_found",',
            "      key,",
            "    };",
            "  }",
            "",
            "",
            "  // =========================================================================",
            "  // Presigned URL Endpoints",
            "  // =========================================================================",
            "",
            "",
            "  /**",
            "   * Generate presigned URL để download file.",
            "   *",
            "   * URL có thời gian hiệu lực hạn chế, phù hợp cho việc chia sẻ",
            "   * file tạm thời mà không cần expose trực tiếp storage.",
            "   */",
            '  @Get("presigned/:key")',
            "  async getPresignedDownloadUrl(",
            "    @Param('key') key: string,",
            "    @Query('expiration') expiration?: string,",
            "    @Query('tenantId') tenantId?: string,",
            '    @Headers("x-tenant-id") xTenantId?: string,',
            "  ): Promise<{ key: string; presignedUrl: string; expiration: number }> {",
            "    const exp = expiration ? parseInt(expiration, 10) : 3600;",
            "    const effectiveTenantId = xTenantId || tenantId;",
            "    const url = await this.fileUploadService.getPresignedUrl(",
            "      key, exp, effectiveTenantId,",
            "    );",
            "    return { key, presignedUrl: url, expiration: exp };",
            "  }",
            "",
        ])

        # Sinh transform endpoints nếu có image transforms
        if has_image_transforms:
            lines.extend([
                "",
                "  // =========================================================================",
                "  // Media Transform Endpoints",
                "  // =========================================================================",
                "",
                "",
                "  /**",
                "   * Resize ảnh theo kích thước target.",
                "   */",
                '  @Post("transform/resize")',
                '  @UseInterceptors(FileInterceptor("file"))',
                "  async resizeImage(",
                "    @UploadedFile() file: Express.Multer.File,",
                "    @Query('width') width: string,",
                "    @Query('height') height: string,",
                "    @Query('quality') quality?: string,",
                "    @Query('format') format?: string,",
                "    @Query('keepRatio') keepRatio?: string,",
                "    @Res() res: Response,",
                "  ): Promise<void> {",
                "    if (!file) {",
                "      throw new BadRequestException('Không có file được upload');",
                "    }",
                "    const resized = await this.mediaTransformService.resizeImage(",
                "      file.buffer,",
                "      parseInt(width, 10),",
                "      parseInt(height, 10),",
                "      quality ? parseInt(quality, 10) : 80,",
                "      format || 'jpeg',",
                "      keepRatio === 'true',",
                "    );",
                "    const contentType = format",
                "      ? `image/${format.toLowerCase() === 'jpg' ? 'jpeg' : format.toLowerCase()}`",
                "      : 'image/jpeg';",
                "    res.setHeader('Content-Type', contentType);",
                "    res.setHeader('Content-Length', resized.length);",
                "    res.send(resized);",
                "  }",
                "",
                "",
                "  /**",
                "   * Tạo thumbnail giữ aspect ratio.",
                "   */",
                '  @Post("transform/thumbnail")',
                '  @UseInterceptors(FileInterceptor("file"))',
                "  async createThumbnail(",
                "    @UploadedFile() file: Express.Multer.File,",
                "    @Query('maxWidth') maxWidth: string,",
                "    @Query('maxHeight') maxHeight: string,",
                "    @Query('quality') quality?: string,",
                "    @Query('format') format?: string,",
                "    @Res() res: Response,",
                "  ): Promise<void> {",
                "    if (!file) {",
                "      throw new BadRequestException('Không có file được upload');",
                "    }",
                "    const thumbnail = await this.mediaTransformService.createThumbnail(",
                "      file.buffer,",
                "      parseInt(maxWidth, 10),",
                "      parseInt(maxHeight, 10),",
                "      quality ? parseInt(quality, 10) : 80,",
                "      format || 'jpeg',",
                "    );",
                "    const contentType = format",
                "      ? `image/${format.toLowerCase() === 'jpg' ? 'jpeg' : format.toLowerCase()}`",
                "      : 'image/jpeg';",
                "    res.setHeader('Content-Type', contentType);",
                "    res.setHeader('Content-Length', thumbnail.length);",
                "    res.send(thumbnail);",
                "  }",
                "",
            ])

        lines.extend([
            "  // =========================================================================",
            "  // Health Check",
            "  // =========================================================================",
            "",
            "",
            '  @Get("health")',
            "  async healthCheck(): Promise<{ status: string; component: string }> {",
            '    return { status: "ok", component: "storage" };',
            "  }",
            "",
            "}",
            "",
        ])

        return "\n".join(lines)

    # =========================================================================
    # Storage Module
    # =========================================================================

    def _emit_storage_module(self, collection: FileStorageCollection) -> str:
        """
        Sinh StorageModule - NestJS module chính để import tất cả storage components.

        Tạo NestJS module có:
        - Import S3Module (nếu có S3 backend)
        - Provide FileUploadService và các dependencies
        - Provide MediaTransformService (nếu có image transforms)
        - Export các service cho module khác dùng

        Args:
            collection: Collection chứa storage config

        Returns:
            Nội dung của storage.module.ts
        """
        has_s3 = StorageBackend.S3 in {p.backend_type for p in collection.profiles}
        has_image_transforms = any(
            t.transform_type in (TransformType.RESIZE, TransformType.THUMBNAIL)
            for t in collection.transforms
        )

        lines: list[str] = [
            "/**",
            " * Storage Module - Auto-generated by Midicoder CE.",
            " *",
            " * Module chính để import tất cả storage components cho NestJS.",
            " *",
            " * KPI-029: Tenant Isolation",
            " * CP11: File Storage & Media",
            " */",
            "",
            "import { Global, Module } from '@nestjs/common';",
            "import { FileUploadService } from './file-upload.service';",
        ]

        if has_s3:
            lines.append("import { S3Module, s3ClientFactory } from './s3.module';")

        if has_image_transforms:
            lines.append("import { MediaTransformService } from './media-transform.service';")

        lines.extend([
            "import { FileUploadController } from './file-upload.controller';",
            "",
            "",
            "@Global()",
            "@Module({",
            "  imports: [",
        ])

        if has_s3:
            lines.append("    S3Module,")

        lines.extend([
            "  ],",
            "  controllers: [",
            "    FileUploadController,",
            "  ],",
            "  providers: [",
            "    FileUploadService,",
        ])

        if has_image_transforms:
            lines.append("    MediaTransformService,")

        lines.extend([
            "  ],",
            "  exports: [",
            "    FileUploadService,",
        ])

        if has_image_transforms:
            lines.append("    MediaTransformService,")

        lines.extend([
            "  ],",
            "})",
            "export class StorageModule {}",
            "",
        ])

        return "\n".join(lines)
