# coding: utf-8
"""
Unit tests cho recipes của CP26.

Author: Midicoder Team
Version: 1.0.0
"""

from midicoder.packs.cp_full_documentation.recipes import (
    auto_generate_docs_from_mir,
    generate_api_docs,
    generate_component_docs,
    generate_project_docs,
)
from midicoder.packs.cp_full_documentation.models import DocPortalType


class TestAutoGenerateDocs:
    """Test auto_generate_docs_from_mir."""

    def test_generate_from_entities(self) -> None:
        metadata = {"entities": [{"id": "User"}], "commands": [{"id": "CreateUser"}]}
        result = auto_generate_docs_from_mir(metadata, stack="fastapi")
        assert len(result.portals) == 1
        assert len(result.portals[0].sections) >= 2

    def test_empty_metadata(self) -> None:
        result = auto_generate_docs_from_mir({}, stack="fastapi")
        assert len(result.portals) == 0

    def test_frontend_stack(self) -> None:
        metadata = {"entities": [{"id": "Widget"}]}
        result = auto_generate_docs_from_mir(metadata, stack="react")
        assert result.portals[0].type == DocPortalType.STORYBOOK


class TestGenerateApiDocs:
    """Test generate_api_docs."""

    def test_basic(self) -> None:
        result = generate_api_docs(title="Test API", version="2.0.0")
        assert len(result.api_configs) == 1
        assert result.api_configs[0].title == "Test API"


class TestGenerateComponentDocs:
    """Test generate_component_docs."""

    def test_basic(self) -> None:
        result = generate_component_docs(components=["Button", "Input"], stack="react")
        assert len(result.portals) == 1
        assert len(result.portals[0].sections) == 2


class TestGenerateProjectDocs:
    """Test generate_project_docs."""

    def test_basic(self) -> None:
        result = generate_project_docs(title="My Project", stack="fastapi")
        assert len(result.portals) == 1
        assert result.portals[0].title == "My Project"
