# coding: utf-8
"""
Angular Tenant Emitter — Sinh TenantService, TenantGuard, TenantInterceptor cho Angular.

Module nay chua AngularTenantEmitter de emit cac file:
- src/app/core/tenant/tenant.service.ts: Tenant management service
- src/app/core/tenant/tenant.guard.ts: Route guard (verify tenant before navigation)
- src/app/core/tenant/tenant.interceptor.ts: HTTP interceptor (inject tenant header)

KPI-029: Tenant Isolation — bat buoc tenant context cho moi request.

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from midicoder.packs.cp_core_multi_tenant.models import TenantConfig, TenantMode

_TRIPLE = "'''"


class AngularTenantEmitter:
    """
    Emitter de sinh tenant-related files cho Angular frontend.

    Generate Service, Guard, va Interceptor theo TenantMode.
    """

    def emit(self, config: TenantConfig) -> dict[str, str]:
        """
        Emit tat ca tenant files cho Angular.

        Args:
            config: TenantConfig chua cau hinh isolation strategy

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}
        files["src/app/core/tenant/tenant.service.ts"] = self._emit_service(config)
        files["src/app/core/tenant/tenant.guard.ts"] = self._emit_guard(config)
        files["src/app/core/tenant/tenant.interceptor.ts"] = self._emit_interceptor(config)
        return files

    def _emit_service(self, config: TenantConfig) -> str:
        """Sinh tenant.service.ts — Angular Service."""
        return f'''{_TRIPLE}
Tenant Service — Auto-generated by Midicoder CE.

Service quan ly tenant state trong Angular application.
Mode: {config.mode.value} | KPI-029: Tenant Isolation.
{_TRIPLE}

import {{ Injectable }} from '@angular/core';
import {{ BehaviorSubject, Observable }} from 'rxjs';

export interface TenantInfo {{
  id: string;
  name?: string;
  mode: '{config.mode.value}' | 'schema' | 'row' | 'subdomain';
}}

@Injectable({{
  providedIn: 'root',
}})
export class TenantService {{
  private readonly STORAGE_KEY = 'midicoder_tenant_id';
  private tenantSubject = new BehaviorSubject<TenantInfo | null>(null);

  /** Lay tenant hien tai */
  getCurrentTenant(): Observable<TenantInfo | null> {{
    return this.tenantSubject.asObservable();
  }}

  /** Lay tenant ID */
  getTenantId(): string | null {{
    return this.tenantSubject.value?.id || localStorage.getItem(this.STORAGE_KEY);
  }}

  /** Set tenant hien tai */
  setTenant(tenant: TenantInfo): void {{
    this.tenantSubject.next(tenant);
    localStorage.setItem(this.STORAGE_KEY, tenant.id);
  }}

  /** Xoa tenant context (logout) */
  clearTenant(): void {{
    this.tenantSubject.next(null);
    localStorage.removeItem(this.STORAGE_KEY);
  }}

  /** Kiem tra da co tenant chua */
  hasTenant(): boolean {{
    return this.getTenantId() !== null;
  }}
}}
'''

    def _emit_guard(self, config: TenantConfig) -> str:
        """Sinh tenant.guard.ts — Route Guard."""
        return f'''{_TRIPLE}
Tenant Guard — Auto-generated by Midicoder CE.

Route guard de bat buoc tenant truoc khi navigation.
Mode: {config.mode.value} | KPI-029: Tenant Isolation.
{_TRIPLE}

import {{ Injectable }} from '@angular/core';
import {{
  CanActivate,
  Router,
  ActivatedRouteSnapshot,
  RouterStateSnapshot,
}} from '@angular/router';
import {{ TenantService }} from './tenant.service';

@Injectable({{
  providedIn: 'root',
}})
export class TenantGuard implements CanActivate {{
  constructor(
    private tenantService: TenantService,
    private router: Router,
  ) {{}}

  async canActivate(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot,
  ): Promise<boolean> {{
    // Cac duong khong can tenant
    const publicPaths = ['/login', '/register', '/health', '/tenant-select'];
    if (publicPaths.some((p) => state.url.startsWith(p))) {{
      return true;
    }}

    // Kiem tra co tenant ID
    const tenantId = this.tenantService.getTenantId();
    if (!tenantId) {{
      // Chua chon tenant -> redirect den tenant selection
      await this.router.navigate(['/tenant-select'], {{
        queryParams: {{ redirect: state.url }},
      }});
      return false;
    }}

    return true;
  }}
}}
'''

    def _emit_interceptor(self, config: TenantConfig) -> str:
        """Sinh tenant.interceptor.ts — HTTP Interceptor."""
        return f'''{_TRIPLE}
Tenant Interceptor — Auto-generated by Midicoder CE.

HTTP interceptor de inject X-Tenant-ID header vao moi request.
Mode: {config.mode.value} | KPI-029: Tenant Isolation.
{_TRIPLE}

import {{ Injectable }} from '@angular/core';
import {{
  HttpInterceptor,
  HttpRequest,
  HttpHandler,
  HttpEvent,
}} from '@angular/common/http';
import {{ Observable }} from 'rxjs';
import {{ TenantService }} from './tenant.service';

@Injectable()
export class TenantInterceptor implements HttpInterceptor {{
  constructor(private tenantService: TenantService) {{}}

  intercept(
    request: HttpRequest<unknown>,
    next: HttpHandler,
  ): Observable<HttpEvent<unknown>> {{
    const tenantId = this.tenantService.getTenantId();

    // Khong inject cho cac request public
    const publicUrls = ['/auth', '/health', '/docs', '/openapi'];
    if (publicUrls.some((url) => request.url.includes(url))) {{
      return next.handle(request);
    }}

    // Clone request voi header X-Tenant-ID
    const cloned = request.clone({{
      setHeaders: {{
        'X-Tenant-ID': tenantId || '',
      }},
    }});

    return next.handle(cloned);
  }}
}}
'''