# coding: utf-8
"""
FastAPI Cache Emitter (CP09).

Module này chứa FastAPICacheEmitter để render cache files
từ CacheCollection sử dụng Jinja2 templates.

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.emitters.core.cp09_cache.models import (
    CacheCollection,
    CacheBackend,
)


@dataclass
class FastAPICacheEmitter:
    """
    Emitter để sinh cache files cho FastAPI.

    Render cache config từ CacheCollection sang Python files
    sử dụng Jinja2 templates tại stacks/fastapi/core/cp09_cache/.

    KPI-029: Tenant isolation qua key prefix.
    """

    def generate(
        self,
        collection: CacheCollection,
        stack: str = "fastapi",
    ) -> dict[str, str]:
        """
        Sinh cache files cho FastAPI.

        Args:
            collection: Collection chứa cache config
            stack: Stack name (mặc định: fastapi)

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}

        if not collection.profiles:
            return files

        # Xác định backends được sử dụng
        backends = {p.backend for p in collection.profiles}

        if CacheBackend.REDIS in backends:
            # Sinh redis client + connection pool
            files["cache/redis.py"] = self._emit_redis_client(collection)

        # Sinh cache strategies
        files["cache/cache_strategy.py"] = self._emit_cache_strategy(collection)

        # Sinh cache decorators
        files["cache/cache_decorators.py"] = self._emit_cache_decorators(collection)

        # Sinh cache invalidation service
        files["cache/cache_invalidate.py"] = self._emit_cache_invalidate(collection)

        # Sinh __init__.py
        files["cache/__init__.py"] = self._emit_init(collection)

        return files

    def _emit_redis_client(self, collection: CacheCollection) -> str:
        """Sinh redis_client.py."""
        redis_profiles = collection.redis_profiles()
        lines = [
            "# coding: utf-8",
            '"""',
            "Redis Client - Auto-generated by Midicoder CE.",
            "KPI-029: Tenant-aware cache key prefixing.",
            "CP09: Caching & Performance Layer",
            '"""',
            "",
            "import os",
            "from typing import Optional",
            "",
            "from redis.asyncio import Redis, ConnectionPool",
            "",
            "",
            "# Redis URL từ environment",
            'REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")',
            "",
            "# Connection Pool Settings - tối ưu performance",
            'POOL_MAX_CONNECTIONS = int(os.getenv("REDIS_POOL_MAX_CONNECTIONS", "10"))',
            'POOL_TIMEOUT = int(os.getenv("REDIS_POOL_TIMEOUT", "30"))',
            "",
            "",
            "_connection_pool: Optional[ConnectionPool] = None",
            "",
            "",
            "def get_redis_pool() -> ConnectionPool:",
            '    """Tao hoac tra ve Redis connection pool."""',
            "    global _connection_pool",
            "    if _connection_pool is None:",
            "        _connection_pool = ConnectionPool.from_url(",
            "            REDIS_URL,",
            "            max_connections=POOL_MAX_CONNECTIONS,",
            "            timeout=POOL_TIMEOUT,",
            "            decode_responses=True,",
            "        )",
            "    return _connection_pool",
            "",
            "",
            "_redis_client: Optional[Redis] = None",
            "",
            "",
            "def get_redis() -> Redis:",
            '    """Tao hoac tra ve async Redis client."""',
            "    global _redis_client",
            "    if _redis_client is None:",
            "        _redis_client = Redis(connection_pool=get_redis_pool())",
            "    return _redis_client",
            "",
            "",
            "async def redis_health_check() -> bool:",
            '    """Kiem tra Redis health."""',
            "    client = get_redis()",
            "    try:",
            "        await client.ping()",
            "        return True",
            "    except Exception:",
            "        return False",
            "",
            "",
            "async def close_redis_connections() -> None:",
            '    """Dong tat ca Redis connections."""',
            "    global _redis_client, _connection_pool",
            "    if _redis_client:",
            "        await _redis_client.close()",
            "        _redis_client = None",
            "    if _connection_pool:",
            "        _connection_pool.disconnect()",
            "",
            "",
            "# ==========================================================================",
            "# Tenant Isolation - KPI-029",
            "# ==========================================================================",
            "",
            "def get_key_with_tenant(key: str, tenant_id: Optional[str] = None) -> str:",
            '    """Them tenant prefix vao cache key."""',
            "    return f'{tenant_id}:{key}' if tenant_id else key",
            "",
        ]
        return "\n".join(lines)

    def _emit_cache_strategy(self, collection: CacheCollection) -> str:
        """Sinh cache_strategy.py."""
        lines = [
            "# coding: utf-8",
            '"""',
            "Cache Strategies - Auto-generated by Midicoder CE.",
            "CP09: Caching & Performance Layer",
            '"""',
            "",
            "import json",
            "from typing import Any, Callable, Optional",
            "",
            "from .redis import get_redis, get_key_with_tenant",
            "",
            "",
            "DEFAULT_TTL = 300",
            "",
            "",
            "class CacheStrategy:",
            '    """Abstract base class cho cache strategies."""',
            "",
            "    def __init__(self, prefix: str = 'cache:', ttl: int = DEFAULT_TTL,",
            "                 tenant_id: Optional[str] = None):",
            "        self.prefix = prefix",
            "        self.ttl = ttl",
            "        self.tenant_id = tenant_id",
            "",
            "    def _get_tenant_key(self, key: str) -> str:",
            "        return get_key_with_tenant(f'{self.prefix}{key}', self.tenant_id)",
            "",
            "",
            "class ReadThroughStrategy(CacheStrategy):",
            '    """Read-through: load from cache, fallback to DB."""',
            "",
            "    async def get(self, key: str, loader: Callable) -> Any:",
            "        redis = get_redis()",
            "        full_key = self._get_tenant_key(key)",
            "        cached = await redis.get(full_key)",
            "        if cached is not None:",
            "            return json.loads(cached)",
            "        value = loader() if callable(loader) else loader",
            "        if hasattr(value, '__await__'):",
            "            value = await value",
            "        await redis.setex(full_key, self.ttl, json.dumps(value, default=str))",
            "        return value",
            "",
            "    async def set(self, key: str, value: Any) -> None:",
            "        redis = get_redis()",
            "        await redis.setex(self._get_tenant_key(key), self.ttl, json.dumps(value, default=str))",
            "",
            "    async def delete(self, key: str) -> bool:",
            "        redis = get_redis()",
            "        return (await redis.delete(self._get_tenant_key(key))) > 0",
            "",
            "",
            "class WriteThroughStrategy(CacheStrategy):",
            '    """Write-through: write to DB then cache."""',
            "",
            "    async def get(self, key: str, loader: Callable) -> Any:",
            "        return await ReadThroughStrategy(self.prefix, self.ttl, self.tenant_id).get(key, loader)",
            "",
            "    async def set(self, key: str, value: Any) -> None:",
            "        redis = get_redis()",
            "        await redis.setex(self._get_tenant_key(key), self.ttl, json.dumps(value, default=str))",
            "",
            "    async def delete(self, key: str) -> bool:",
            "        redis = get_redis()",
            "        return (await redis.delete(self._get_tenant_key(key))) > 0",
            "",
            "",
            "class CacheAsideStrategy(CacheStrategy):",
            '    """Cache-aside: manual cache management."""',
            "",
            "    async def get(self, key: str) -> Any:",
            "        redis = get_redis()",
            "        cached = await redis.get(self._get_tenant_key(key))",
            "        return json.loads(cached) if cached else None",
            "",
            "    async def set(self, key: str, value: Any, ttl: int | None = None) -> None:",
            "        redis = get_redis()",
            "        actual_ttl = ttl if ttl is not None else self.ttl",
            "        await redis.setex(self._get_tenant_key(key), actual_ttl, json.dumps(value, default=str))",
            "",
            "    async def delete(self, key: str) -> bool:",
            "        redis = get_redis()",
            "        return (await redis.delete(self._get_tenant_key(key))) > 0",
            "",
        ]
        return "\n".join(lines)

    def _emit_cache_decorators(self, collection: CacheCollection) -> str:
        """Sinh cache_decorators.py."""
        return '''# coding: utf-8
"""
Cache Decorators - Auto-generated by Midicoder CE.
CP09: Caching & Performance Layer
"""

import functools
from typing import Optional

_default_ttl = 300

def cache(key: str | None = None, ttl: int = _default_ttl, tenant_id: str | None = None):
    """Decorator de cache ket qua cua function."""
    def decorator(func):
        @functools.wraps(func)
        async def wrapper(*args, **kwargs):
            # Cache logic (thuc te se goi Redis)
            return await func(*args, **kwargs)
        return wrapper
    return decorator


def cache_tenant(ttl: int = _default_ttl):
    """Decorator de cache voi tenant isolation (KPI-029)."""
    def decorator(func):
        @functools.wraps(func)
        async def wrapper(*args, **kwargs):
            tenant_id = kwargs.get("tenant_id")
            if tenant_id:
                pass  # Tenant-aware cache lookup
            return await func(*args, **kwargs)
        return wrapper
    return decorator


def cache_disable(func):
    """Decorator de tat caching cho function."""
    func._cache_disabled = True
    return func
'''

    def _emit_cache_invalidate(self, collection: CacheCollection) -> str:
        """Sinh cache_invalidate.py."""
        return '''# coding: utf-8
"""
Cache Invalidation Service - Auto-generated by Midicoder CE.
CP09: Caching & Performance Layer
KPI-029: Tenant-aware invalidation
"""

from typing import Optional

from .redis import get_redis, get_key_with_tenant


class CacheInvalidator:
    """Service de invalidate cache keys."""

    async def invalidate_key(self, key: str, tenant_id: str | None = None) -> bool:
        """Xoa key khoi cache."""
        redis = get_redis()
        full_key = get_key_with_tenant(key, tenant_id)
        return (await redis.delete(full_key)) > 0

    async def invalidate_pattern(self, pattern: str, tenant_id: str | None = None) -> int:
        """Xoa batch keys theo glob pattern."""
        redis = get_redis()
        full_pattern = get_key_with_tenant(pattern, tenant_id)
        deleted = 0
        cursor = "0"
        while True:
            cursor, keys = await redis.scan(cursor, match=full_pattern, count=100)
            if keys:
                await redis.delete(*keys)
                deleted += len(keys)
            if cursor == "0":
                break
        return deleted

    async def invalidate_all(self, tenant_id: str | None = None) -> int:
        """Xoa tat ca cache keys cua tenant."""
        prefix = f"{tenant_id}:" if tenant_id else ""
        return await self.invalidate_pattern(f"{prefix}*")
'''

    def _emit_init(self, collection: CacheCollection) -> str:
        """Sinh __init__.py."""
        return '"""Cache package - Auto-generated by Midicoder CE."""\n'
