# coding: utf-8
"""
FastAPI Cache Emitter (CP09).

Module này chứa FastAPICacheEmitter để render cache files
từ CacheCollection sử dụng Jinja2 templates.

Author: Midicoder Team
Version: 1.1.0
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.packs.cp_backend_cache.models import (
    CacheCollection,
    CacheBackend,
)


@dataclass
class FastAPICacheEmitter:
    """
    Emitter để sinh cache files cho FastAPI.

    Render cache config từ CacheCollection sang Python files
    sử dụng Jinja2 templates tại stacks/fastapi/cp_backend_cache/.

    KPI-029: Tenant isolation qua key prefix.
    """

    def generate(
        self,
        collection: CacheCollection,
        stack: str = "fastapi",
    ) -> dict[str, str]:
        """
        Sinh cache files cho FastAPI.

        Args:
            collection: Collection chứa cache config
            stack: Stack name (mặc định: fastapi)

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}

        if not collection.profiles:
            return files

        # Xác định backends được sử dụng
        backends = {p.backend for p in collection.profiles}

        if CacheBackend.REDIS in backends:
            # Sinh redis client + connection pool
            files["cache/redis.py"] = self._emit_redis_client(collection)

        if CacheBackend.MEMCACHED in backends:
            files["cache/memcached.py"] = self._emit_memcached_client(collection)

        # Sinh cache strategies
        files["cache/cache_strategy.py"] = self._emit_cache_strategy(collection)

        # Sinh cache decorators
        files["cache/cache_decorators.py"] = self._emit_cache_decorators(collection)

        # Sinh cache invalidation service
        files["cache/cache_invalidate.py"] = self._emit_cache_invalidate(collection)

        # Sinh CDN cache middleware (nếu có CDN config)
        if collection.cdn_layers:
            files["cache/cdn_cache.py"] = self._emit_cdn_cache(collection)

        # Sinh stampede prevention (nếu có config)
        if collection.stampede_prevention:
            files["cache/stampede_prevention.py"] = self._emit_stampede_prevention(collection)

        # Sinh cache warmup (nếu có warmup config)
        if collection.warmup_config:
            files["cache/cache_warmup.py"] = self._emit_cache_warmup(collection)

        # Sinh multi-tier cache (nếu có tiers)
        if collection.tiers:
            files["cache/multi_tier.py"] = self._emit_multi_tier(collection)

        # Sinh __init__.py
        files["cache/__init__.py"] = self._emit_init(collection)

        return files

    def _emit_redis_client(self, collection: CacheCollection) -> str:
        """Sinh redis_client.py."""
        redis_profiles = collection.redis_profiles()
        lines = [
            "# coding: utf-8",
            '"""',
            "Redis Client - Auto-generated by Midicoder CE.",
            "KPI-029: Tenant-aware cache key prefixing.",
            "CP09: Caching & Performance Layer",
            '"""',
            "",
            "import os",
            "from typing import Optional",
            "",
            "from redis.asyncio import Redis, ConnectionPool",
            "",
            "",
            "# Redis URL từ environment",
            'REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")',
            "",
            "# Connection Pool Settings - tối ưu performance",
            'POOL_MAX_CONNECTIONS = int(os.getenv("REDIS_POOL_MAX_CONNECTIONS", "10"))',
            'POOL_TIMEOUT = int(os.getenv("REDIS_POOL_TIMEOUT", "30"))',
            "",
            "",
            "_connection_pool: Optional[ConnectionPool] = None",
            "",
            "",
            "def get_redis_pool() -> ConnectionPool:",
            '    """Tao hoac tra ve Redis connection pool."""',
            "    global _connection_pool",
            "    if _connection_pool is None:",
            "        _connection_pool = ConnectionPool.from_url(",
            "            REDIS_URL,",
            "            max_connections=POOL_MAX_CONNECTIONS,",
            "            timeout=POOL_TIMEOUT,",
            "            decode_responses=True,",
            "        )",
            "    return _connection_pool",
            "",
            "",
            "_redis_client: Optional[Redis] = None",
            "",
            "",
            "def get_redis() -> Redis:",
            '    """Tao hoac tra ve async Redis client."""',
            "    global _redis_client",
            "    if _redis_client is None:",
            "        _redis_client = Redis(connection_pool=get_redis_pool())",
            "    return _redis_client",
            "",
            "",
            "async def redis_health_check() -> bool:",
            '    """Kiem tra Redis health."""',
            "    client = get_redis()",
            "    try:",
            "        await client.ping()",
            "        return True",
            "    except Exception:",
            "        return False",
            "",
            "",
            "async def close_redis_connections() -> None:",
            '    """Dong tat ca Redis connections."""',
            "    global _redis_client, _connection_pool",
            "    if _redis_client:",
            "        await _redis_client.close()",
            "        _redis_client = None",
            "    if _connection_pool:",
            "        _connection_pool.disconnect()",
            "",
            "",
            "# ==========================================================================",
            "# Tenant Isolation - KPI-029",
            "# ==========================================================================",
            "",
            "def get_key_with_tenant(key: str, tenant_id: Optional[str] = None) -> str:",
            '    """Them tenant prefix vao cache key."""',
            "    return f'{tenant_id}:{key}' if tenant_id else key",
            "",
        ]
        return "\n".join(lines)

    def _emit_cache_strategy(self, collection: CacheCollection) -> str:
        """Sinh cache_strategy.py."""
        lines = [
            "# coding: utf-8",
            '"""',
            "Cache Strategies - Auto-generated by Midicoder CE.",
            "CP09: Caching & Performance Layer",
            '"""',
            "",
            "import json",
            "from typing import Any, Callable, Optional",
            "",
            "from .redis import get_redis, get_key_with_tenant",
            "",
            "",
            "DEFAULT_TTL = 300",
            "",
            "",
            "class CacheStrategy:",
            '    """Abstract base class cho cache strategies."""',
            "",
            "    def __init__(self, prefix: str = 'cache:', ttl: int = DEFAULT_TTL,",
            "                 tenant_id: Optional[str] = None):",
            "        self.prefix = prefix",
            "        self.ttl = ttl",
            "        self.tenant_id = tenant_id",
            "",
            "    def _get_tenant_key(self, key: str) -> str:",
            "        return get_key_with_tenant(f'{self.prefix}{key}', self.tenant_id)",
            "",
            "",
            "class ReadThroughStrategy(CacheStrategy):",
            '    """Read-through: load from cache, fallback to DB."""',
            "",
            "    async def get(self, key: str, loader: Callable) -> Any:",
            "        redis = get_redis()",
            "        full_key = self._get_tenant_key(key)",
            "        cached = await redis.get(full_key)",
            "        if cached is not None:",
            "            return json.loads(cached)",
            "        value = loader() if callable(loader) else loader",
            "        if hasattr(value, '__await__'):",
            "            value = await value",
            "        await redis.setex(full_key, self.ttl, json.dumps(value, default=str))",
            "        return value",
            "",
            "    async def set(self, key: str, value: Any) -> None:",
            "        redis = get_redis()",
            "        await redis.setex(self._get_tenant_key(key), self.ttl, json.dumps(value, default=str))",
            "",
            "    async def delete(self, key: str) -> bool:",
            "        redis = get_redis()",
            "        return (await redis.delete(self._get_tenant_key(key))) > 0",
            "",
            "",
            "class WriteThroughStrategy(CacheStrategy):",
            '    """Write-through: write to DB then cache."""',
            "",
            "    async def get(self, key: str, loader: Callable) -> Any:",
            "        return await ReadThroughStrategy(self.prefix, self.ttl, self.tenant_id).get(key, loader)",
            "",
            "    async def set(self, key: str, value: Any) -> None:",
            "        redis = get_redis()",
            "        await redis.setex(self._get_tenant_key(key), self.ttl, json.dumps(value, default=str))",
            "",
            "    async def delete(self, key: str) -> bool:",
            "        redis = get_redis()",
            "        return (await redis.delete(self._get_tenant_key(key))) > 0",
            "",
            "",
            "class CacheAsideStrategy(CacheStrategy):",
            '    """Cache-aside: manual cache management."""',
            "",
            "    async def get(self, key: str) -> Any:",
            "        redis = get_redis()",
            "        cached = await redis.get(self._get_tenant_key(key))",
            "        return json.loads(cached) if cached else None",
            "",
            "    async def set(self, key: str, value: Any, ttl: int | None = None) -> None:",
            "        redis = get_redis()",
            "        actual_ttl = ttl if ttl is not None else self.ttl",
            "        await redis.setex(self._get_tenant_key(key), actual_ttl, json.dumps(value, default=str))",
            "",
            "    async def delete(self, key: str) -> bool:",
            "        redis = get_redis()",
            "        return (await redis.delete(self._get_tenant_key(key))) > 0",
            "",
        ]
        return "\n".join(lines)

    def _emit_cache_decorators(self, collection: CacheCollection) -> str:
        """Sinh cache_decorators.py."""
        return '''# coding: utf-8
"""
Cache Decorators - Auto-generated by Midicoder CE.
CP09: Caching & Performance Layer
"""

import functools
from typing import Optional

_default_ttl = 300

def cache(key: str | None = None, ttl: int = _default_ttl, tenant_id: str | None = None):
    """Decorator de cache ket qua cua function."""
    def decorator(func):
        @functools.wraps(func)
        async def wrapper(*args, **kwargs):
            # Cache logic (thuc te se goi Redis)
            return await func(*args, **kwargs)
        return wrapper
    return decorator


def cache_tenant(ttl: int = _default_ttl):
    """Decorator de cache voi tenant isolation (KPI-029)."""
    def decorator(func):
        @functools.wraps(func)
        async def wrapper(*args, **kwargs):
            tenant_id = kwargs.get("tenant_id")
            if tenant_id:
                pass  # Tenant-aware cache lookup
            return await func(*args, **kwargs)
        return wrapper
    return decorator


def cache_disable(func):
    """Decorator de tat caching cho function."""
    func._cache_disabled = True
    return func
'''

    def _emit_cache_invalidate(self, collection: CacheCollection) -> str:
        """Sinh cache_invalidate.py."""
        return '''# coding: utf-8
"""
Cache Invalidation Service - Auto-generated by Midicoder CE.
CP09: Caching & Performance Layer
KPI-029: Tenant-aware invalidation
"""

from typing import Optional

from .redis import get_redis, get_key_with_tenant


class CacheInvalidator:
    """Service de invalidate cache keys."""

    async def invalidate_key(self, key: str, tenant_id: str | None = None) -> bool:
        """Xoa key khoi cache."""
        redis = get_redis()
        full_key = get_key_with_tenant(key, tenant_id)
        return (await redis.delete(full_key)) > 0

    async def invalidate_pattern(self, pattern: str, tenant_id: str | None = None) -> int:
        """Xoa batch keys theo glob pattern."""
        redis = get_redis()
        full_pattern = get_key_with_tenant(pattern, tenant_id)
        deleted = 0
        cursor = "0"
        while True:
            cursor, keys = await redis.scan(cursor, match=full_pattern, count=100)
            if keys:
                await redis.delete(*keys)
                deleted += len(keys)
            if cursor == "0":
                break
        return deleted

    async def invalidate_all(self, tenant_id: str | None = None) -> int:
        """Xoa tat ca cache keys cua tenant."""
        prefix = f"{tenant_id}:" if tenant_id else ""
        return await self.invalidate_pattern(f"{prefix}*")
'''

    def _emit_memcached_client(self, collection: CacheCollection) -> str:
        """Sinh memcached.py."""
        return '''# coding: utf-8
"""
Memcached Client - Auto-generated by Midicoder CE.
CP09: Caching & Performance Layer
KPI-029: Tenant-aware cache key prefixing.
"""

import os
from typing import Optional

_memcached_servers = [
    s.strip()
    for s in os.getenv("MEMCACHED_SERVERS", "localhost:11211").split(",")
]

_client: Optional[Any] = None


def get_memcached():
    """Tao hoac tra ve Memcached client."""
    global _client
    if _client is None:
        try:
            from pymemcache.client.hash import HashClient
            _client = HashClient(
                _memcached_servers,
                connect_timeout=3,
                timeout=5,
                no_block=True,
            )
        except ImportError:
            raise RuntimeError(
                "pymemcache chưa được cài đặt. "
                "Chạy: pip install pymemcache"
            )
    return _client


async def memcached_health_check() -> bool:
    """Kiem tra Memcached health."""
    client = get_memcached()
    try:
        client.version()
        return True
    except Exception:
        return False


async def close_memcached_connections() -> None:
    """Dong tat ca Memcached connections."""
    global _client
    if _client:
        _client.close()
        _client = None


# KPI-029: Tenant Isolation
def get_key_with_tenant(key: str, tenant_id: Optional[str] = None) -> str:
    """Them tenant prefix vao cache key."""
    return f"{tenant_id}:{key}" if tenant_id else key
'''

    def _emit_cdn_cache(self, collection: CacheCollection) -> str:
        """Sinh cdn_cache.py — CDN cache middleware."""
        layers = collection.cdn_layers
        provider = layers[0].provider if layers else "cloudflare"
        default_ttl = layers[0].default_ttl if layers else 3600

        return f'''# coding: utf-8
"""
CDN Cache Middleware - Auto-generated by Midicoder CE.
CP09: Caching & Performance Layer
Provider: {provider}
"""

import os
from typing import Optional

from fastapi import Request, Response
from fastapi.responses import JSONResponse


CDN_PROVIDER = os.getenv("CDN_PROVIDER", "{provider}")
CDN_ZONE_ID = os.getenv("CDN_ZONE_ID", "")
CDN_API_KEY = os.getenv("CDN_API_KEY", "")
DEFAULT_CDN_TTL = {default_ttl}


def get_cache_control_headers(
    public: bool = True,
    ttl: int | None = None,
    stale_while_revalidate: int = 60,
    stale_if_error: int = 300,
) -> dict[str, str]:
    """Xay dung Cache-Control headers cho CDN responses."""
    actual_ttl = ttl if ttl is not None else DEFAULT_CDN_TTL
    directives = ["public" if public else "private", f"max-age={{actual_ttl}}"]
    directives.append(f"stale-while-revalidate={{stale_while_revalidate}}")
    directives.append(f"stale-if-error={{stale_if_error}}")
    return {{"Cache-Control": ", ".join(directives)}}


async def cdn_cache_middleware(request: Request, call_next):
    """FastAPI middleware để add CDN cache headers."""
    response = await call_next(request)

    # Chỉ cache GET requests
    if request.method == "GET":
        response.headers["Cache-Control"] = ", ".join([
            "public",
            f"max-age={{DEFAULT_CDN_TTL}}",
            "stale-while-revalidate=60",
            "stale-if-error=300",
        ])
        response.headers["Vary"] = "Accept-Encoding"

    return response


async def purge_cdn_cache(path: str) -> bool:
    """Purge cache trên CDN cho 1 path cụ thể."""
    import httpx

    if not CDN_ZONE_ID or not CDN_API_KEY:
        return False

    if CDN_PROVIDER == "cloudflare":
        url = f"https://api.cloudflare.com/client/v4/zones/{{CDN_ZONE_ID}}/purge_cache"
        headers = {{"Authorization": f"Bearer {{CDN_API_KEY}}"}}
        async with httpx.AsyncClient() as client:
            resp = await client.post(url, json={{"files": [path]}}, headers=headers)
            return resp.status_code == 200

    return False


async def purge_cdn_all() -> bool:
    """Purge toàn bộ cache trên CDN."""
    import httpx

    if not CDN_ZONE_ID or not CDN_API_KEY:
        return False

    if CDN_PROVIDER == "cloudflare":
        url = f"https://api.cloudflare.com/client/v4/zones/{{CDN_ZONE_ID}}/purge_cache"
        headers = {{"Authorization": f"Bearer {{CDN_API_KEY}}"}}
        async with httpx.AsyncClient() as client:
            resp = await client.post(url, json={{"purge_everything": True}}, headers=headers)
            return resp.status_code == 200

    return False
'''

    def _emit_stampede_prevention(self, collection: CacheCollection) -> str:
        """Sinh stampede_prevention.py."""
        config = collection.stampede_prevention
        strategy = config.strategy.value if config else "mutex"
        lock_ttl = config.lock_ttl if config else 10
        lock_timeout = config.lock_timeout if config else 5

        return f'''# coding: utf-8
"""
Cache Stampede Prevention - Auto-generated by Midicoder CE.
CP09: Caching & Performance Layer
Strategy: {strategy}
"""

import asyncio
from typing import Any, Callable

from .redis import get_redis, get_key_with_tenant


_lock_prefix = "__cache_lock:"
_DEFAULT_LOCK_TTL = {lock_ttl}
_DEFAULT_LOCK_TIMEOUT = {lock_timeout}


async def _acquire_lock(
    key: str,
    tenant_id: str | None = None,
    ttl: int = _DEFAULT_LOCK_TTL,
) -> bool:
    """Acquire distributed mutex lock trên Redis."""
    redis = get_redis()
    lock_key = get_key_with_tenant(f"{{_lock_prefix}}{{key}}", tenant_id)
    acquired = await redis.set(lock_key, "1", nx=True, ex=ttl)
    return bool(acquired)


async def _release_lock(
    key: str,
    tenant_id: str | None = None,
) -> None:
    """Release distributed mutex lock."""
    redis = get_redis()
    lock_key = get_key_with_tenant(f"{{_lock_prefix}}{{key}}", tenant_id)
    await redis.delete(lock_key)


async def stampede_safe_get(
    cache_get: Callable,
    cache_set: Callable,
    loader: Callable,
    key: str,
    tenant_id: str | None = None,
    ttl: int = 300,
) -> Any:
    """
    Lấy giá trị từ cache với stampede prevention (strategy: {strategy}).

    Khi cache miss, chỉ 1 request thực sự load data, các request khác wait.
    """
    cached = await cache_get(key, tenant_id=tenant_id)
    if cached is not None:
        return cached

    # Thử acquire lock
    acquired = await _acquire_lock(key, tenant_id)

    if acquired:
        try:
            # Double-check sau khi acquire lock
            cached = await cache_get(key, tenant_id=tenant_id)
            if cached is not None:
                return cached

            # Load data và set vào cache
            value = loader() if callable(loader) else loader
            if hasattr(value, "__await__"):
                value = await value
            await cache_set(key, value, ttl, tenant_id=tenant_id)
            return value
        finally:
            await _release_lock(key, tenant_id)
    else:
        # Không acquire được lock — wait và retry với stale data
        await asyncio.sleep(0.1)
        retry_count = 0
        while retry_count < {{_DEFAULT_LOCK_TIMEOUT * 10}}:
            cached = await cache_get(key, tenant_id=tenant_id)
            if cached is not None:
                return cached
            await asyncio.sleep(0.1)
            retry_count += 1

        # Timeout — fallback: load data trực tiếp (không cache)
        value = loader() if callable(loader) else loader
        if hasattr(value, "__await__"):
            value = await value
        return value
'''

    def _emit_cache_warmup(self, collection: CacheCollection) -> str:
        """Sinh cache_warmup.py."""
        warmup = collection.warmup_config
        strategy = warmup.strategy.value if warmup else "on_startup"
        batch_size = warmup.batch_size if warmup else 100
        parallelism = warmup.parallelism if warmup else 4
        warmup_keys = "\n    ".join(repr(k) for k in warmup.warmup_keys) if warmup and warmup.warmup_keys else "''"

        return f'''# coding: utf-8
"""
Cache Warmup - Auto-generated by Midicoder CE.
CP09: Caching & Performance Layer
Strategy: {strategy}
"""

import asyncio
import logging
from typing import Any, Callable

from .redis import get_redis, get_key_with_tenant

logger = logging.getLogger(__name__)

_BATCH_SIZE = {batch_size}
_PARALLELISM = {parallelism}

WARMUP_KEYS = [
    {warmup_keys},
]


async def warm_key(
    key: str,
    loader: Callable,
    ttl: int = 300,
    tenant_id: str | None = None,
) -> bool:
    """Warm 1 key: check if exists, nếu không thì load và set."""
    redis = get_redis()
    full_key = get_key_with_tenant(key, tenant_id)

    existing = await redis.get(full_key)
    if existing is not None:
        return True

    try:
        value = loader(key) if callable(loader) else loader
        if hasattr(value, "__await__"):
            value = await value
        await redis.setex(full_key, ttl, str(value))
        return True
    except Exception as e:
        logger.error(f"[CacheWarmup] Failed to warm key {{key}}: {{e}}")
        return False


async def warm_batch(
    keys: list[str],
    loader: Callable,
    ttl: int = 300,
    tenant_id: str | None = None,
) -> dict[str, bool]:
    """Warm batch keys với semaphore để limit concurrency."""
    semaphore = asyncio.Semaphore(_PARALLELISM)
    results: dict[str, bool] = {{}}

    async def _warm_with_semaphore(key: str) -> tuple[str, bool]:
        async with semaphore:
            success = await warm_key(key, loader, ttl, tenant_id)
            return (key, success)

    tasks = [asyncio.create_task(_warm_with_semaphore(k)) for k in keys]
    for task in asyncio.as_completed(tasks):
        key, success = await task
        results[key] = success

    return results


async def warm_on_startup(
    loader: Callable,
    ttl: int = 300,
    tenant_id: str | None = None,
) -> dict[str, bool]:
    """Warm cache khi service khởi động."""
    logger.info("[CacheWarmup] Starting warmup on startup...")
    results = await warm_batch(WARMUP_KEYS, loader, ttl, tenant_id)
    success_count = sum(1 for v in results.values() if v)
    logger.info(
        f"[CacheWarmup] Warmed {{success_count}}/{{len(results)}} keys"
    )
    return results
'''

    def _emit_multi_tier(self, collection: CacheCollection) -> str:
        """Sinh multi_tier.py — multi-tier cache."""
        tiers = sorted(collection.tiers, key=lambda t: t.tier_order)
        tier_lines = ""
        for t in tiers:
            tier_lines += f"""    TierConfig(
        tier_name="{t.tier_name}",
        tier_order={t.tier_order},
        backend="{t.backend}",
        max_size={t.max_size},
        ttl={t.ttl},
        eviction_policy="{t.eviction_policy}",
    ),
"""

        return f'''# coding: utf-8
"""
Multi-Tier Cache - Auto-generated by Midicoder CE.
CP09: Caching & Performance Layer
"""

from dataclasses import dataclass
from typing import Any, Optional

from .redis import get_redis, get_key_with_tenant


@dataclass
class TierConfig:
    tier_name: str
    tier_order: int
    backend: str
    max_size: int
    ttl: int
    eviction_policy: str


_TIERS = [
{tier_lines}
]

# L1: in-memory
_l1_store: dict[str, tuple[Any, float]] = {{}}
_l1_max = next((t.max_size for t in _TIERS if t.tier_order == 1), 1000)


async def multi_tier_get(
    key: str,
    tenant_id: str | None = None,
) -> Any:
    """Lấy từ multi-tier cache: L1 → L2 (Redis) → L3 (DB)."""
    full_key = get_key_with_tenant(key, tenant_id)

    # L1: Memory
    import time
    entry = _l1_store.get(full_key)
    if entry:
        value, expiry = entry
        if expiry == 0 or time.time() < expiry:
            return value
        else:
            del _l1_store[full_key]

    # L2: Redis
    redis = get_redis()
    cached = await redis.get(full_key)
    if cached is not None:
        # Set vào L1
        l1_ttl = next((t.ttl for t in _TIERS if t.tier_order == 1), 60)
        _l1_store[full_key] = (cached, time.time() + l1_ttl)
        return cached

    # L3: return None, caller sẽ load từ DB và set
    return None


async def multi_tier_set(
    key: str,
    value: Any,
    tenant_id: str | None = None,
) -> None:
        """Set vào cả L1 và L2."""
    full_key = get_key_with_tenant(key, tenant_id)
    import time

    # L1
    if len(_l1_store) >= _l1_max:
        oldest = next(iter(_l1_store))
        del _l1_store[oldest]
    l1_ttl = next((t.ttl for t in _TIERS if t.tier_order == 1), 60)
    _l1_store[full_key] = (value, time.time() + l1_ttl)

    # L2
    redis = get_redis()
    l2_ttl = next((t.ttl for t in _TIERS if t.tier_order == 2), 300)
    await redis.setex(full_key, l2_ttl, str(value))


async def multi_tier_delete(
    key: str,
    tenant_id: str | None = None,
) -> None:
    """Xóa khỏi cả L1 và L2."""
    full_key = get_key_with_tenant(key, tenant_id)
    _l1_store.pop(full_key, None)
    redis = get_redis()
    await redis.delete(full_key)
'''

    def _emit_init(self, collection: CacheCollection) -> str:
        """Sinh __init__.py."""
        return '"""Cache package - Auto-generated by Midicoder CE."""\n'
