# coding: utf-8
"""
NestJS Cache Emitter (CP09).

Module này chứa NestJSCacheEmitter để render NestJS cache module
từ CacheCollection sử dụng Jinja2 templates.

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.packs.cp_backend_cache.models import (
    CacheCollection,
    CacheBackend,
)


@dataclass
class NestJSCacheEmitter:
    """
    Emitter để sinh cache files cho NestJS.

    Render cache module từ CacheCollection sang TypeScript files.
    KPI-029: Tenant isolation qua key prefix.
    """

    def generate(
        self,
        collection: CacheCollection,
        stack: str = "nestjs",
    ) -> dict[str, str]:
        """
        Sinh cache module files cho NestJS.

        Args:
            collection: Collection chứa cache config
            stack: Stack name (mặc định: nestjs)

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}

        if not collection.profiles:
            return files

        # Xác định backends
        backends = {p.backend for p in collection.profiles}

        if CacheBackend.REDIS in backends:
            files["cache/cache.module.ts"] = self._emit_cache_module(collection)

        # Sinh cache service
        files["cache/cache.service.ts"] = self._emit_cache_service(collection)

        # Sinh cache interceptor
        files["cache/cache.interceptor.ts"] = self._emit_cache_interceptor(collection)

        # CDN cache
        if collection.cdn_layers:
            files["cache/cdn_cache.ts"] = self._emit_cdn_cache(collection)

        # Stampede prevention
        if collection.stampede_prevention:
            files["cache/stampede_prevention.ts"] = self._emit_stampede_prevention(collection)

        # Multi-tier cache
        if collection.tiers:
            files["cache/multi_tier.ts"] = self._emit_multi_tier(collection)

        # Cache warmup
        if collection.warmup_config:
            files["cache/cache_warmup.ts"] = self._emit_cache_warmup(collection)

        return files

    def _emit_cache_module(self, collection: CacheCollection) -> str:
        """Sinh cache.module.ts."""
        lines = [
            "// CacheModule - Auto-generated by Midicoder CE",
            "// CP09: Caching & Performance Layer",
            "// KPI-029: Tenant-aware caching",
            "",
            "import { Module, Global } from '@nestjs/common';",
            "import { CacheService } from './cache.service';",
            "",
            "@Global()",
            "@Module({",
            "  providers: [CacheService],",
            "  exports: [CacheService],",
            "})",
            "export class CacheModule {}",
            "",
        ]
        return "\n".join(lines)

    def _emit_cache_service(self, collection: CacheCollection) -> str:
        """Sinh cache.service.ts."""
        lines = [
            "// CacheService - Auto-generated by Midicoder CE",
            "// CP09: Caching & Performance Layer",
            "// KPI-029: Tenant-aware caching",
            "",
            "import { Injectable, Logger } from '@nestjs/common';",
            "import { Redis } from 'ioredis';",
            "",
            "@Injectable()",
            "export class CacheService {",
            "  private readonly redis: Redis;",
            "  private readonly logger = new Logger(CacheService.name);",
            "",
            "  constructor() {",
            "    this.redis = new Redis(process.env.REDIS_URL || 'redis://localhost:6379');",
            "  }",
            "",
            "  // KPI-029: Tenant-aware key building",
            "  private buildKey(key: string, tenantId?: string): string {",
            "    return tenantId ? `${tenantId}:${key}` : key;",
            "  }",
            "",
            "  async get(key: string, tenantId?: string): Promise<any | null> {",
            "    const raw = await this.redis.get(this.buildKey(key, tenantId));",
            "    if (!raw) return null;",
            "    try { return JSON.parse(raw); } catch { return raw; }",
            "  }",
            "",
            "  async set(key: string, value: any, ttl?: number, tenantId?: string): Promise<void> {",
            "    const fullKey = this.buildKey(key, tenantId);",
            "    const serialized = JSON.stringify(value);",
            "    if (ttl && ttl > 0) {",
            "      await this.redis.set(fullKey, serialized, 'EX', ttl);",
            "    } else {",
            "      await this.redis.set(fullKey, serialized);",
            "    }",
            "  }",
            "",
            "  async delete(key: string, tenantId?: string): Promise<boolean> {",
            "    const deleted = await this.redis.del(this.buildKey(key, tenantId));",
            "    return deleted > 0;",
            "  }",
            "",
            "  async invalidate(pattern: string, tenantId?: string): Promise<number> {",
            "    const fullPattern = this.buildKey(pattern, tenantId);",
            "    let deleted = 0;",
            "    let cursor = '0';",
            "    do {",
            "      const [nextCursor, keys] = await this.redis.scan(",
            "        cursor, 'MATCH', fullPattern, 'COUNT', '100',",
            "      );",
            "      cursor = nextCursor;",
            "      if (keys.length > 0) {",
            "        await this.redis.del(...keys);",
            "        deleted += keys.length;",
            "      }",
            "    } while (cursor !== '0');",
            "    return deleted;",
            "  }",
            "",
            "  async healthCheck(): Promise<boolean> {",
            "    try {",
            "      await this.redis.ping();",
            "      return true;",
            "    } catch { return false; }",
            "  }",
            "}",
            "",
        ]
        return "\n".join(lines)

    def _emit_cache_interceptor(self, collection: CacheCollection) -> str:
        """Sinh cache.interceptor.ts."""
        lines = [
            "// CacheInterceptor - Auto-generated by Midicoder CE",
            "// CP09: Caching & Performance Layer",
            "// KPI-029: Tenant Isolation",
            "",
            "import {",
            "  Injectable, NestInterceptor, ExecutionContext, CallHandler, Logger,",
            "} from '@nestjs/common';",
            "import { Reflector } from '@nestjs/core';",
            "import { Observable, of } from 'rxjs';",
            "import { tap, catchError } from 'rxjs/operators';",
            "import { CacheService } from './cache.service';",
            "",
            "export const CACHE_TTL = 'cacheTtl';",
            "export const CACHE_KEY = 'cacheKey';",
            "export const CACHE_DISABLE = 'cacheDisable';",
            "const DEFAULT_TTL = 300;",
            "",
            "export function CacheTTL(ttl: number) {",
            "  return Reflect.metadata(CACHE_TTL, ttl);",
            "}",
            "",
            "export function CacheKey(key: string) {",
            "  return Reflect.metadata(CACHE_KEY, key);",
            "}",
            "",
            "export function CacheDisable() {",
            "  return Reflect.metadata(CACHE_DISABLE, true);",
            "}",
            "",
            "@Injectable()",
            "export class CacheInterceptor implements NestInterceptor {",
            "  private readonly logger = new Logger(CacheInterceptor.name);",
            "",
            "  constructor(",
            "    private readonly reflector: Reflector,",
            "    private readonly cacheService: CacheService,",
            "  ) {}",
            "",
            "  intercept(context: ExecutionContext, next: CallHandler): Observable<unknown> {",
            "    const isDisabled = this.reflector.getAllAndOverride<boolean>(",
            "      CACHE_DISABLE, [context.getHandler(), context.getClass()],",
            "    );",
            "    if (isDisabled) return next.handle();",
            "",
            "    const ttl = this.reflector.getAllAndOverride<number>(",
            "      CACHE_TTL, [context.getHandler(), context.getClass()],",
            "    ) || DEFAULT_TTL;",
            "",
            "    const customKey = this.reflector.getAllAndOverride<string>(",
            "      CACHE_KEY, [context.getHandler(), context.getClass()],",
            "    );",
            "",
            "    // KPI-029: Tenant Isolation",
            "    const request = context.switchToHttp().getRequest();",
            "    const tenantId = request.headers['x-tenant-id'] || request.tenantId;",
            "",
            "    const key = customKey || `${request.method}:${request.url}`;",
            "",
            "    if (!tenantId) {",
            "      this.logger.debug('[Cache] SKIP: Missing tenantId');",
            "      return next.handle();",
            "    }",
            "",
            "    return this.cacheService.get(key, tenantId).then((cached) => {",
            "      if (cached !== null) {",
            "        this.logger.debug(`[Cache] HIT: ${key}`);",
            "        return of(cached);",
            "      }",
            "",
            "      this.logger.debug(`[Cache] MISS: ${key}`);",
            "      return next.handle().pipe(",
            "        tap((response) => {",
            "          this.cacheService.set(key, response, ttl, tenantId);",
            "        }),",
            "        catchError((error) => {",
            "          this.logger.error(`[Cache] Error: ${key}`, error.stack);",
            "          throw error;",
            "        }),",
            "      );",
            "    });",
            "  }",
            "}",
            "",
        ]
        return "\n".join(lines)

    def _emit_cdn_cache(self, collection: CacheCollection) -> str:
        """Sinh cdn_cache.ts."""
        cdn = collection.cdn_layers[0] if collection.cdn_layers else None
        provider = cdn.provider if cdn else "cloudflare"
        default_ttl = cdn.default_ttl if cdn else 3600

        lines = [
            "// CdnCacheService - Auto-generated by Midicoder CE",
            "// CP09: Caching & Performance Layer",
            f"// Provider: {provider}",
            "",
            "import { Injectable, Logger } from '@nestjs/common';",
            "",
            "const CDN_PROVIDER = process.env.CDN_PROVIDER || 'cloudflare';",
            "const CDN_ZONE_ID = process.env.CDN_ZONE_ID || '';",
            "const CDN_API_KEY = process.env.CDN_API_KEY || '';",
            f"const DEFAULT_CDN_TTL = {default_ttl};",
            "",
            "export function getCacheControlHeaders(",
            "  publicFlag: boolean = true,",
            "  ttl: number | null = null,",
            "  staleWhileRevalidate: number = 60,",
            "  staleIfError: number = 300,",
            "): Record<string, string> {",
            "  const actualTtl = ttl !== null ? ttl : DEFAULT_CDN_TTL;",
            "  const directives = [",
            "    publicFlag ? 'public' : 'private',",
            "    `max-age=${actualTtl}`,",
            "    `stale-while-revalidate=${staleWhileRevalidate}`,",
            "    `stale-if-error=${staleIfError}`,",
            "  ];",
            "  return { 'Cache-Control': directives.join(', ') };",
            "}",
            "",
            "@Injectable()",
            "export class CdnCacheService {",
            "  private readonly logger = new Logger(CdnCacheService.name);",
            "",
            "  async purgePath(path: string): Promise<boolean> {",
            "    if (!CDN_ZONE_ID || !CDN_API_KEY) return false;",
            "    const url = `https://api.cloudflare.com/client/v4/zones/${CDN_ZONE_ID}/purge_cache`;",
            "    try {",
            "      const resp = await fetch(url, {",
            "        method: 'POST',",
            "        headers: { Authorization: `Bearer ${CDN_API_KEY}`, 'Content-Type': 'application/json' },",
            "        body: JSON.stringify({ files: [path] }),",
            "      });",
            "      return resp.status === 200;",
            "    } catch { return false; }",
            "  }",
            "",
            "  async purgeAll(): Promise<boolean> {",
            "    if (!CDN_ZONE_ID || !CDN_API_KEY) return false;",
            "    const url = `https://api.cloudflare.com/client/v4/zones/${CDN_ZONE_ID}/purge_cache`;",
            "    try {",
            "      const resp = await fetch(url, {",
            "        method: 'POST',",
            "        headers: { Authorization: `Bearer ${CDN_API_KEY}`, 'Content-Type': 'application/json' },",
            "        body: JSON.stringify({ purge_everything: true }),",
            "      });",
            "      return resp.status === 200;",
            "    } catch { return false; }",
            "  }",
            "}",
            "",
        ]
        return "\n".join(lines)

    def _emit_stampede_prevention(self, collection: CacheCollection) -> str:
        """Sinh stampede_prevention.ts."""
        lock_ttl = collection.stampede_prevention.lock_ttl if collection.stampede_prevention else 10

        lines = [
            "// StampedePreventionService - Auto-generated by Midicoder CE",
            "// CP09: Caching & Performance Layer",
            "",
            "import { Injectable, Logger } from '@nestjs/common';",
            "import { Redis } from 'ioredis';",
            "",
            "const LOCK_PREFIX = '__cache_lock:';",
            f"const DEFAULT_LOCK_TTL = {lock_ttl};",
            "",
            "@Injectable()",
            "export class StampedePreventionService {",
            "  private readonly logger = new Logger(StampedePreventionService.name);",
            "  private readonly redis: Redis;",
            "",
            "  constructor(redisClient: Redis) { this.redis = redisClient; }",
            "",
            "  async stampedeSafeGet<T>(",
            "    key: string,",
            "    loader: () => Promise<T>,",
            "    ttl: number = 300,",
            "    tenantId?: string,",
            "  ): Promise<T> {",
            "    const fullKey = tenantId ? `${tenantId}:${key}` : key;",
            "    const cached = await this.redis.get(fullKey);",
            "    if (cached !== null) {",
            "      try { return JSON.parse(cached) as T; } catch { return cached as unknown as T; }",
            "    }",
            "    const lockKey = `${LOCK_PREFIX}${fullKey}`;",
            "    const acquired = await this.redis.set(lockKey, '1', 'NX', 'EX', DEFAULT_LOCK_TTL) === 'OK';",
            "    if (acquired) {",
            "      try {",
            "        const rechecked = await this.redis.get(fullKey);",
            "        if (rechecked !== null) {",
            "          try { return JSON.parse(rechecked) as T; } catch { return rechecked as unknown as T; }",
            "        }",
            "        const value = await loader();",
            "        await this.redis.set(fullKey, JSON.stringify(value), 'EX', ttl);",
            "        return value;",
            "      } finally { await this.redis.del(lockKey); }",
            "    }",
            "    for (let i = 0; i < 50; i++) {",
            "      await new Promise(r => setTimeout(r, 100));",
            "      const retry = await this.redis.get(fullKey);",
            "      if (retry !== null) {",
            "        try { return JSON.parse(retry) as T; } catch { return retry as unknown as T; }",
            "      }",
            "    }",
            "    return loader();",
            "  }",
            "}",
            "",
        ]
        return "\n".join(lines)

    def _emit_cache_warmup(self, collection: CacheCollection) -> str:
        """Sinh cache_warmup.ts."""
        parallelism = collection.warmup_config.parallelism if collection.warmup_config else 4

        lines = [
            "// CacheWarmupService - Auto-generated by Midicoder CE",
            "// CP09: Caching & Performance Layer",
            "",
            "import { Injectable, Logger } from '@nestjs/common';",
            "import { Redis } from 'ioredis';",
            "",
            f"const PARALLELISM = {parallelism};",
            "",
            "@Injectable()",
            "export class CacheWarmupService {",
            "  private readonly logger = new Logger(CacheWarmupService.name);",
            "  private readonly redis: Redis;",
            "",
            "  constructor(redisClient: Redis) { this.redis = redisClient; }",
            "",
            "  async warmKey(",
            "    key: string,",
            "    loader: () => Promise<any>,",
            "    ttl: number = 300,",
            "    tenantId?: string,",
            "  ): Promise<boolean> {",
            "    const fullKey = tenantId ? `${tenantId}:${key}` : key;",
            "    const existing = await this.redis.get(fullKey);",
            "    if (existing !== null) return true;",
            "    try {",
            "      const value = await loader();",
            "      await this.redis.set(fullKey, JSON.stringify(value), 'EX', ttl);",
            "      return true;",
            "    } catch (error) {",
            "      this.logger.error(`[CacheWarmup] Failed to warm key ${key}: ${error}`);",
            "      return false;",
            "    }",
            "  }",
            "",
            "  async warmBatch(",
            "    keys: string[],",
            "    loader: (key: string) => Promise<any>,",
            "    ttl: number = 300,",
            "    tenantId?: string,",
            "  ): Promise<Record<string, boolean>> {",
            "    const results: Record<string, boolean> = {};",
            "    const tasks = keys.map(async (key) => {",
            "      results[key] = await this.warmKey(key, () => loader(key), ttl, tenantId);",
            "    });",
            "    await Promise.all(tasks);",
            "    return results;",
            "  }",
            "}",
            "",
        ]
        return "\n".join(lines)

    def _emit_multi_tier(self, collection: CacheCollection) -> str:
        """Sinh multi_tier.ts."""
        max_l1 = collection.tiers[0].max_size if collection.tiers else 1000

        lines = [
            "// MultiTierCacheService - Auto-generated by Midicoder CE",
            "// CP09: Caching & Performance Layer",
            "",
            "import { Injectable, Logger } from '@nestjs/common';",
            "import { Redis } from 'ioredis';",
            "",
            "interface CacheEntry { value: string; expiresAt: number; }",
            "",
            "@Injectable()",
            "export class MultiTierCacheService {",
            "  private readonly logger = new Logger(MultiTierCacheService.name);",
            "  private readonly l1: Map<string, CacheEntry> = new Map();",
            "  private readonly redis: Redis | null;",
            f"  private readonly maxL1Size: number = {max_l1};",
            "",
            "  constructor(redisClient?: Redis) { this.redis = redisClient || null; }",
            "",
            "  async get<T>(key: string, loader: () => Promise<T>, ttl: number = 300, tenantId?: string): Promise<T> {",
            "    const fullKey = tenantId ? `${tenantId}:${key}` : key;",
            "    const entry = this.l1.get(fullKey);",
            "    if (entry && entry.expiresAt > Date.now()) {",
            "      try { return JSON.parse(entry.value) as T; } catch { return entry.value as unknown as T; }",
            "    }",
            "    if (this.redis) {",
            "      const l2 = await this.redis.get(fullKey);",
            "      if (l2 !== null) {",
            "        this.l1.set(fullKey, { value: l2, expiresAt: Date.now() + ttl * 1000 });",
            "        try { return JSON.parse(l2) as T; } catch { return l2 as unknown as T; }",
            "      }",
            "    }",
            "    const value = await loader();",
            "    const serialized = JSON.stringify(value);",
            "    this.l1.set(fullKey, { value: serialized, expiresAt: Date.now() + ttl * 1000 });",
            "    if (this.redis) await this.redis.set(fullKey, serialized, 'EX', ttl);",
            "    return value;",
            "  }",
            "",
            "  async set(key: string, value: any, ttl: number = 300, tenantId?: string): Promise<void> {",
            "    const fullKey = tenantId ? `${tenantId}:${key}` : key;",
            "    const serialized = JSON.stringify(value);",
            "    this.l1.set(fullKey, { value: serialized, expiresAt: Date.now() + ttl * 1000 });",
            "    if (this.redis) await this.redis.set(fullKey, serialized, 'EX', ttl);",
            "  }",
            "",
            "  async delete(key: string, tenantId?: string): Promise<boolean> {",
            "    const fullKey = tenantId ? `${tenantId}:${key}` : key;",
            "    this.l1.delete(fullKey);",
            "    if (this.redis) await this.redis.del(fullKey);",
            "    return true;",
            "  }",
            "}",
            "",
        ]
        return "\n".join(lines)
