# coding: utf-8
"""
Redis Emitter - Sinh Redis client + cache files cho FastAPI backend.

Module nay chua RedisEmitter de render cache files
tu CacheCollection su dung Jinja2 templates.

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.emitters.core.cache.models import (
    CacheCollection,
    CacheProfile,
)


@dataclass
class RedisEmitter:
    """
    Emitter de sinh Redis client + cache files cho FastAPI.

    Render cache config tu CacheCollection sang Python files.
    KPI-029: Tenant isolation qua key prefix.
    """

    def emit(
        self,
        collection: CacheCollection,
        output_dir: Path,
    ) -> dict[str, str]:
        """
        Emit cache files tu CacheCollection.

        Args:
            collection: Collection chua cache config
            output_dir: Directory de luu files

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}
        cache_dir = output_dir / "cache"
        cache_dir.mkdir(parents=True, exist_ok=True)

        if not collection.profiles:
            return files

        # Sinh redis_client.py
        content = self._emit_redis_client(collection)
        file_key = str((cache_dir / "redis_client.py").relative_to(output_dir)).replace("\\", "/")
        files[file_key] = content

        # Sinh cache_config.py
        content = self._emit_cache_config(collection)
        file_key = str((cache_dir / "cache_config.py").relative_to(output_dir)).replace("\\", "/")
        files[file_key] = content

        # Sinh __init__.py
        init_key = str((cache_dir / "__init__.py").relative_to(output_dir)).replace("\\", "/")
        files[init_key] = '"""Cache package - auto-generated by Midicoder CE."""\n'

        return files

    def _emit_redis_client(self, collection: CacheCollection) -> str:
        """Sinh redis_client.py."""
        lines = [
            "# coding: utf-8",
            '"""',
            "Redis Client - Auto-generated by Midicoder CE.",
            "KPI-029: Tenant-aware cache key prefixing.",
            '"""',
            "",
            "import os",
            "from redis.asyncio import Redis",
            "",
            "",
            "# KPI-029: Tenant-aware cache key prefixing",
            "def get_key_with_tenant(key: str, tenant_id: str | None = None) -> str:",
            '    """Xay dung cache key co tenant prefix."""',
            "    if tenant_id:",
            '        return f"{tenant_id}:{key}"',
            "    return key",
            "",
            "",
            "async def get_redis() -> Redis:",
            '    """Tao Redis client async."""',
            '    url = os.getenv("REDIS_URL", "redis://localhost:6379/0")',
            "    return Redis.from_url(url, decode_responses=True)",
            "",
        ]
        return "\n".join(lines)

    def _emit_cache_config(self, collection: CacheCollection) -> str:
        """Sinh cache_config.py."""
        lines = [
            "# coding: utf-8",
            '"""',
            "Cache Configuration - Auto-generated by Midicoder CE.",
            '"""',
            "",
        ]

        for profile in collection.profiles:
            lines.append(f"# Profile: {profile.id}")
            lines.append(f"CACHE_{profile.id.upper()}_TTL = {profile.ttl}")
            if profile.max_size:
                lines.append(f"CACHE_{profile.id.upper()}_MAX_SIZE = {profile.max_size}")
            if profile.key_prefix:
                lines.append(f"CACHE_{profile.id.upper()}_PREFIX = '{profile.key_prefix}'")
            if profile.tenant_isolated:
                lines.append("# KPI-029: Tenant isolated = True")
            lines.append("")

        return "\n".join(lines)