# coding: utf-8
"""
NestJS Cache Emitter (CP09).

Module này chứa NestJSCacheEmitter để render NestJS cache module
từ CacheCollection sử dụng Jinja2 templates.

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.emitters.core.cache.models import (
    CacheCollection,
    CacheBackend,
)


@dataclass
class NestJSCacheEmitter:
    """
    Emitter để sinh cache files cho NestJS.

    Render cache module từ CacheCollection sang TypeScript files.
    KPI-029: Tenant isolation qua key prefix.
    """

    def generate(
        self,
        collection: CacheCollection,
        stack: str = "nestjs",
    ) -> dict[str, str]:
        """
        Sinh cache module files cho NestJS.

        Args:
            collection: Collection chứa cache config
            stack: Stack name (mặc định: nestjs)

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}

        if not collection.profiles:
            return files

        # Xác định backends
        backends = {p.backend for p in collection.profiles}

        if CacheBackend.REDIS in backends:
            files["cache/cache.module.ts"] = self._emit_cache_module(collection)

        # Sinh cache service
        files["cache/cache.service.ts"] = self._emit_cache_service(collection)

        # Sinh cache interceptor
        files["cache/cache.interceptor.ts"] = self._emit_cache_interceptor(collection)

        return files

    def _emit_cache_module(self, collection: CacheCollection) -> str:
        """Sinh cache.module.ts."""
        lines = [
            "// CacheModule - Auto-generated by Midicoder CE",
            "// CP09: Caching & Performance Layer",
            "// KPI-029: Tenant-aware caching",
            "",
            "import { Module, Global } from '@nestjs/common';",
            "import { CacheService } from './cache.service';",
            "",
            "@Global()",
            "@Module({",
            "  providers: [CacheService],",
            "  exports: [CacheService],",
            "})",
            "export class CacheModule {}",
            "",
        ]
        return "\n".join(lines)

    def _emit_cache_service(self, collection: CacheCollection) -> str:
        """Sinh cache.service.ts."""
        lines = [
            "// CacheService - Auto-generated by Midicoder CE",
            "// CP09: Caching & Performance Layer",
            "// KPI-029: Tenant-aware caching",
            "",
            "import { Injectable, Logger } from '@nestjs/common';",
            "import { Redis } from 'ioredis';",
            "",
            "@Injectable()",
            "export class CacheService {",
            "  private readonly redis: Redis;",
            "  private readonly logger = new Logger(CacheService.name);",
            "",
            "  constructor() {",
            "    this.redis = new Redis(process.env.REDIS_URL || 'redis://localhost:6379');",
            "  }",
            "",
            "  // KPI-029: Tenant-aware key building",
            "  private buildKey(key: string, tenantId?: string): string {",
            "    return tenantId ? `${tenantId}:${key}` : key;",
            "  }",
            "",
            "  async get(key: string, tenantId?: string): Promise<any | null> {",
            "    const raw = await this.redis.get(this.buildKey(key, tenantId));",
            "    if (!raw) return null;",
            "    try { return JSON.parse(raw); } catch { return raw; }",
            "  }",
            "",
            "  async set(key: string, value: any, ttl?: number, tenantId?: string): Promise<void> {",
            "    const fullKey = this.buildKey(key, tenantId);",
            "    const serialized = JSON.stringify(value);",
            "    if (ttl && ttl > 0) {",
            "      await this.redis.set(fullKey, serialized, 'EX', ttl);",
            "    } else {",
            "      await this.redis.set(fullKey, serialized);",
            "    }",
            "  }",
            "",
            "  async delete(key: string, tenantId?: string): Promise<boolean> {",
            "    const deleted = await this.redis.del(this.buildKey(key, tenantId));",
            "    return deleted > 0;",
            "  }",
            "",
            "  async invalidate(pattern: string, tenantId?: string): Promise<number> {",
            "    const fullPattern = this.buildKey(pattern, tenantId);",
            "    let deleted = 0;",
            "    let cursor = '0';",
            "    do {",
            "      const [nextCursor, keys] = await this.redis.scan(",
            "        cursor, 'MATCH', fullPattern, 'COUNT', '100',",
            "      );",
            "      cursor = nextCursor;",
            "      if (keys.length > 0) {",
            "        await this.redis.del(...keys);",
            "        deleted += keys.length;",
            "      }",
            "    } while (cursor !== '0');",
            "    return deleted;",
            "  }",
            "",
            "  async healthCheck(): Promise<boolean> {",
            "    try {",
            "      await this.redis.ping();",
            "      return true;",
            "    } catch { return false; }",
            "  }",
            "}",
            "",
        ]
        return "\n".join(lines)

    def _emit_cache_interceptor(self, collection: CacheCollection) -> str:
        """Sinh cache.interceptor.ts."""
        lines = [
            "// CacheInterceptor - Auto-generated by Midicoder CE",
            "// CP09: Caching & Performance Layer",
            "// KPI-029: Tenant Isolation",
            "",
            "import {",
            "  Injectable, NestInterceptor, ExecutionContext, CallHandler, Logger,",
            "} from '@nestjs/common';",
            "import { Reflector } from '@nestjs/core';",
            "import { Observable, of } from 'rxjs';",
            "import { tap, catchError } from 'rxjs/operators';",
            "import { CacheService } from './cache.service';",
            "",
            "export const CACHE_TTL = 'cacheTtl';",
            "export const CACHE_KEY = 'cacheKey';",
            "export const CACHE_DISABLE = 'cacheDisable';",
            "const DEFAULT_TTL = 300;",
            "",
            "export function CacheTTL(ttl: number) {",
            "  return Reflect.metadata(CACHE_TTL, ttl);",
            "}",
            "",
            "export function CacheKey(key: string) {",
            "  return Reflect.metadata(CACHE_KEY, key);",
            "}",
            "",
            "export function CacheDisable() {",
            "  return Reflect.metadata(CACHE_DISABLE, true);",
            "}",
            "",
            "@Injectable()",
            "export class CacheInterceptor implements NestInterceptor {",
            "  private readonly logger = new Logger(CacheInterceptor.name);",
            "",
            "  constructor(",
            "    private readonly reflector: Reflector,",
            "    private readonly cacheService: CacheService,",
            "  ) {}",
            "",
            "  intercept(context: ExecutionContext, next: CallHandler): Observable<unknown> {",
            "    const isDisabled = this.reflector.getAllAndOverride<boolean>(",
            "      CACHE_DISABLE, [context.getHandler(), context.getClass()],",
            "    );",
            "    if (isDisabled) return next.handle();",
            "",
            "    const ttl = this.reflector.getAllAndOverride<number>(",
            "      CACHE_TTL, [context.getHandler(), context.getClass()],",
            "    ) || DEFAULT_TTL;",
            "",
            "    const customKey = this.reflector.getAllAndOverride<string>(",
            "      CACHE_KEY, [context.getHandler(), context.getClass()],",
            "    );",
            "",
            "    // KPI-029: Tenant Isolation",
            "    const request = context.switchToHttp().getRequest();",
            "    const tenantId = request.headers['x-tenant-id'] || request.tenantId;",
            "",
            "    const key = customKey || `${request.method}:${request.url}`;",
            "",
            "    if (!tenantId) {",
            "      this.logger.debug('[Cache] SKIP: Missing tenantId');",
            "      return next.handle();",
            "    }",
            "",
            "    return this.cacheService.get(key, tenantId).then((cached) => {",
            "      if (cached !== null) {",
            "        this.logger.debug(`[Cache] HIT: ${key}`);",
            "        return of(cached);",
            "      }",
            "",
            "      this.logger.debug(`[Cache] MISS: ${key}`);",
            "      return next.handle().pipe(",
            "        tap((response) => {",
            "          this.cacheService.set(key, response, ttl, tenantId);",
            "        }),",
            "        catchError((error) => {",
            "          this.logger.error(`[Cache] Error: ${key}`, error.stack);",
            "          throw error;",
            "        }),",
            "      );",
            "    });",
            "  }",
            "}",
            "",
        ]
        return "\n".join(lines)
