# coding: utf-8
"""
CacheModule Emitter - Sinh CacheModule cho NestJS backend.

Module nay chua CacheModuleEmitter de render NestJS cache module
tu CacheCollection su dung Jinja2 templates.

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.emitters.core.cache.models import (
    CacheCollection,
    CacheProfile,
)


@dataclass
class CacheModuleEmitter:
    """
    Emitter de sinh CacheModule files cho NestJS.

    Render cache module tu CacheCollection sang TypeScript files.
    KPI-029: Tenant isolation qua key prefix.
    """

    def emit(
        self,
        collection: CacheCollection,
        output_dir: Path,
    ) -> dict[str, str]:
        """
        Emit cache module files tu CacheCollection.

        Args:
            collection: Collection chua cache config
            output_dir: Directory de luu files

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}
        cache_dir = output_dir / "cache"
        cache_dir.mkdir(parents=True, exist_ok=True)

        if not collection.profiles:
            return files

        # Sinh cache.module.ts
        content = self._emit_cache_module(collection)
        file_key = str((cache_dir / "cache.module.ts").relative_to(output_dir)).replace("\\", "/")
        files[file_key] = content

        # Sinh cache.service.ts
        content = self._emit_cache_service(collection)
        file_key = str((cache_dir / "cache.service.ts").relative_to(output_dir)).replace("\\", "/")
        files[file_key] = content

        return files

    def _emit_cache_module(self, collection: CacheCollection) -> str:
        """Sinh cache.module.ts."""
        lines = [
            "// CacheModule - Auto-generated by Midicoder CE",
            "// KPI-029: Tenant-aware caching",
            "",
            "import { Module, Global } from '@nestjs/common';",
            "import { CacheService } from './cache.service';",
            "",
            "@Global()",
            "@Module({",
            "  providers: [CacheService],",
            "  exports: [CacheService],",
            "})",
            "export class CacheModule {}",
            "",
        ]
        return "\n".join(lines)

    def _emit_cache_service(self, collection: CacheCollection) -> str:
        """Sinh cache.service.ts."""
        lines = [
            "// CacheService - Auto-generated by Midicoder CE",
            "// KPI-029: Tenant-aware caching",
            "",
            "import { Injectable } from '@nestjs/common';",
            "import { Redis } from 'ioredis';",
            "",
            "@Injectable()",
            "export class CacheService {",
            "  private redis: Redis;",
            "",
            "  constructor() {",
            "    this.redis = new Redis(process.env.REDIS_URL || 'redis://localhost:6379');",
            "  }",
            "",
            "  // KPI-029: Tenant-aware key building",
            "  private buildKey(key: string, tenantId?: string): string {",
            "    return tenantId ? `${tenantId}:${key}` : key;",
            "  }",
            "",
            "  async get(key: string, tenantId?: string): Promise<string | null> {",
            "    return this.redis.get(this.buildKey(key, tenantId));",
            "  }",
            "",
            "  async set(key: string, value: string, ttl?: number, tenantId?: string): Promise<void> {",
            "    const fullKey = this.buildKey(key, tenantId);",
            "    if (ttl) {",
            "      await this.redis.set(fullKey, value, 'EX', ttl);",
            "    } else {",
            "      await this.redis.set(fullKey, value);",
            "    }",
            "  }",
            "",
            "  async delete(key: string, tenantId?: string): Promise<void> {",
            "    await this.redis.del(this.buildKey(key, tenantId));",
            "  }",
            "}",
            "",
        ]
        return "\n".join(lines)