# coding: utf-8
"""
NestJS Tenant Emitter — Sinh TenantModule, Middleware, Interceptor cho NestJS.

Module này chứa NestJSTenantEmitter để emit các file:
- src/core/tenant/tenant.module.ts: NestJS module
- src/core/tenant/tenant.middleware.ts: Tenant identification middleware
- src/core/tenant/tenant.interceptor.ts: Response interceptor (filter non-tenant data)

KPI-029: Tenant Isolation — bắt buộc tenant context cho mọi request.

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from midicoder.packs.cp02_multi_tenant.models import TenantConfig, TenantMode

_TRIPLE = "'''"


class NestJSTenantEmitter:
    """
    Emitter để sinh tenant-related files cho NestJS.

    Generate Module, Middleware, và Interceptor theo TenantMode.
    """

    def emit(self, config: TenantConfig) -> dict[str, str]:
        """
        Emit tất cả tenant files cho NestJS.

        Args:
            config: TenantConfig chứa cấu hình isolation strategy

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}
        files["src/core/tenant/tenant.module.ts"] = self._emit_module(config)
        files["src/core/tenant/tenant.middleware.ts"] = self._emit_middleware(config)
        files["src/core/tenant/tenant.interceptor.ts"] = self._emit_interceptor(config)
        return files

    def _emit_module(self, config: TenantConfig) -> str:
        """Sinh tenant.module.ts — NestJS Module."""
        return f'''{_TRIPLE}
Tenant Module — Auto-generated by Midicoder CE.

Module cung cấp tenant isolation cho NestJS application.
Mode: {config.mode.value} | KPI-029: Tenant Isolation.
{_TRIPLE}

import {{ Module, Global, DynamicModule }} from '@nestjs/common';
import {{ TenantMiddleware }} from './tenant.middleware';
import {{ TenantInterceptor }} from './tenant.interceptor';

@Global()
@Module({{
  providers: [
    TenantMiddleware,
    TenantInterceptor,
  ],
  exports: [
    TenantMiddleware,
    TenantInterceptor,
  ],
}})
export class TenantModule {{
  static forConfig({{
    mode,
    tenantIdColumn,
    defaultTenantId,
    schemaPrefix,
    domain,
  }}: TenantModuleConfig): DynamicModule {{
    return {{
      module: TenantModule,
    }};
  }}
}}

export interface TenantModuleConfig {{
  mode: '{config.mode.value}' | 'schema' | 'row' | 'subdomain';
  tenantIdColumn?: string;
  defaultTenantId?: string;
  schemaPrefix?: string;
  domain?: string;
}}
'''

    def _emit_middleware(self, config: TenantConfig) -> str:
        """Sinh tenant.middleware.ts — NestJS Middleware."""
        return f'''{_TRIPLE}
Tenant Middleware — Auto-generated by Midicoder CE.

Trích tenant ID từ request (header/JWT/subdomain) và set vào request context.
Mode: {config.mode.value} | KPI-029: Tenant Isolation.
{_TRIPLE}

import {{
  Injectable,
  NestMiddleware,
  HttpStatus,
  BadRequestException,
}} from '@nestjs/common';
import {{ Request, Response, NextFunction }} from 'express';

export interface TenantRequest extends Request {{
  tenantId?: string;
  tenantMode?: string;
}}

@Injectable()
export class TenantMiddleware implements NestMiddleware {{
  private readonly domain = '{config.domain}';
  private readonly defaultTenantId = '{config.default_tenant_id}';

  use(req: TenantRequest, res: Response, next: NextFunction) {{
    // Bypass cho health check va docs
    if (['/health', '/docs', '/'].includes(req.path)) {{
      return next();
    }}

    let tenantId: string | undefined;

    // 1. Lay tu header X-Tenant-ID
    tenantId = req.headers['x-tenant-id'] as string;

    // 2. Lay tu JWT claims (neu co auth middleware chay truoc)
    if (!tenantId) {{
      tenantId = (req as any).user?.tenant_id;
    }}

    // 3. Lay tu subdomain (cho SUBDOMAIN mode)
    if (!tenantId && this.domain) {{
      const host = req.headers.host?.split(':')[0] || '';
      if (host.endsWith('.' + this.domain)) {{
        tenantId = host.substring(0, host.indexOf('.' + this.domain));
      }}
    }}

    if (!tenantId) {{
      throw new BadRequestException(
        'Tenant ID khong the resolve. Cung cap X-Tenant-ID header hoac JWT claim.'
      );
    }}

    // Set vao request
    req.tenantId = tenantId;
    req.tenantMode = '{config.mode.value}';

    // Add header vao response de trace
    res.setHeader('X-Tenant-ID', tenantId);

    next();
  }}
}}
'''

    def _emit_interceptor(self, config: TenantConfig) -> str:
        """Sinh tenant.interceptor.ts — Response Interceptor."""
        col = config.tenant_id_column
        return f'''{_TRIPLE}
Tenant Interceptor — Auto-generated by Midicoder CE.

Filter response để loại bỏ data không thuộc tenant hiện tại.
Mode: {config.mode.value} | KPI-029: Tenant Isolation.
{_TRIPLE}

import {{
  Injectable,
  NestInterceptor,
  ExecutionContext,
  CallHandler,
}} from '@nestjs/common';
import {{ Observable }} from 'rxjs';
import {{ map }} from 'rxjs/operators';

export interface TenantResponse<T> {{
  data: T;
  tenant_id: string;
  meta?: Record<string, unknown>;
}}

@Injectable()
export class TenantInterceptor implements NestInterceptor {{
  intercept(context: ExecutionContext, next: CallHandler): Observable<unknown> {{
    return next.handle().pipe(
      map((data) => {{
        const req = context.switchToHttp().getRequest();
        const tenantId = req['tenantId'];

        // Neu data la array, filter theo tenant_id column
        if (Array.isArray(data)) {{
          return data.filter((item) =>
            !item['{col}'] || item['{col}'] === tenantId
          );
        }}

        // Neu la object don le, kiem tra tenant_id
        if (data && typeof data === 'object' && '{col}' in data) {{
          if (data['{col}'] !== tenantId) {{
            throw new Error('Cross-tenant access detected: MDC-CP02-003');
          }}
        }}

        return data;
      }}),
    );
  }}
}}
'''