# coding: utf-8
"""
FastAPI API Client Emitter (CP20).

Module này chứa FastAPIApiEmitter để emit OpenAPI endpoint
và WebSocket gateway cho FastAPI backend.

Templates (inline Jinja2):
  - openapi_endpoint.py
  - websocket_gateway.py

Usage:
    from midicoder.emitters.core.api_client.fastapi import FastAPIApiEmitter
    emitter = FastAPIApiEmitter()
    files = emitter.generate(api_spec)

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from midicoder.emitters.core.cp20_api_client.models import ApiSpec


@dataclass
class FastAPIApiEmitter:
    """Emitter cho FastAPI API endpoints (CP20).

    Sinh ra:
    - openapi_endpoint.py — OpenAPI spec endpoint
    - websocket_gateway.py — WebSocket gateway cho realtime bridge

    KPI: Type safety client↔backend, OpenAPI spec exposure.
    """

    def generate(self, spec: ApiSpec) -> dict[str, str]:
        """Sinh FastAPI API files từ ApiSpec.

        Args:
            spec: ApiSpec chứa base_url, auth_mode, bridge

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}

        files["openapi_endpoint.py"] = self._emit_openapi_endpoint(spec)
        files["websocket_gateway.py"] = self._emit_websocket_gateway(spec)

        return files

    def _emit_openapi_endpoint(self, spec: ApiSpec) -> str:
        """Sinh openapi_endpoint.py."""
        lines = [
            '# coding: utf-8',
            '"""',
            "OpenAPI Spec Endpoint — Auto-generated by Midicoder CE.",
            "CP20: API Client & Integration Generator",
            '"""',
            "",
            "from fastapi import APIRouter",
            "",
            "",
            'router = APIRouter(prefix="/openapi", tags=["openapi"])',
            "",
            "",
            "@router.get('/spec.json')",
            "async def get_openapi_spec():",
            '    """Tra ve OpenAPI 3.x spec JSON cho client generation."""',
            "    return {",
            '        "openapi": "3.0.3",',
            '        "info": {',
            '            "title": "API Specification",',
            '            "version": "1.0.0",',
            "        },",
            '        "servers": [{"url": "' + spec.base_url + '"}],',
            '        "paths": {},',
            "    }",
            "",
            "",
            "@router.get('/swagger.json')",
            "async def get_swagger_spec():",
            "    return await get_openapi_spec()",
            "",
        ]
        return "\n".join(lines)

    def _emit_websocket_gateway(self, spec: ApiSpec) -> str:
        """Sinh websocket_gateway.py."""
        lines = [
            '# coding: utf-8',
            '"""',
            "WebSocket Gateway — Auto-generated by Midicoder CE.",
            "CP20: API Client & Integration Generator",
            '"""',
            "",
            "from fastapi import APIRouter, WebSocket, WebSocketDisconnect, Query",
            "from typing import Dict, Set",
            "",
            "",
            'router = APIRouter(prefix="/ws", tags=["websocket"])',
            "",
            "",
            "class ConnectionManager:",
            '    """Quan ly WebSocket connections."""',
            "",
            "    def __init__(self):",
            "        self.active_connections: Dict[str, WebSocket] = {}",
            "        self.subscriptions: Dict[str, Set[str]] = {}",
            "",
            "    async def connect(self, websocket: WebSocket, client_id: str):",
            "        await websocket.accept()",
            "        self.active_connections[client_id] = websocket",
            "",
            "    def disconnect(self, client_id: str):",
            "        self.active_connections.pop(client_id, None)",
            "        for clients in self.subscriptions.values():",
            "            clients.discard(client_id)",
            "",
            "    async def subscribe(self, client_id: str, channel: str):",
            "        self.subscriptions.setdefault(channel, set()).add(client_id)",
            "",
            "    async def broadcast(self, channel: str, data: dict):",
            "        for cid in list(self.subscriptions.get(channel, set())):",
            "            ws = self.active_connections.get(cid)",
            "            if ws:",
            "                try:",
            "                    await ws.send_json(data)",
            "                except Exception:",
            "                    self.disconnect(cid)",
            "",
            "",
            "manager = ConnectionManager()",
            "",
            "",
            '@router.websocket("/{client_id}")',
            "async def websocket_endpoint(",
            "    websocket: WebSocket,",
            '    client_id: str,',
            '    token: str = Query(None),',
            "):",
            '    """WebSocket endpoint voi channel-based messaging."""',
            "    await manager.connect(websocket, client_id)",
            "    try:",
            "        while True:",
            "            data = await websocket.receive_json()",
            '            if data.get("type") == "subscribe":',
            '                await manager.subscribe(client_id, data["channel"])',
            '            elif data.get("type") == "message":',
            '                await manager.broadcast(data["channel"], data["data"])',
            "    except WebSocketDisconnect:",
            "        manager.disconnect(client_id)",
            "",
        ]
        return "\n".join(lines)


__all__ = ["FastAPIApiEmitter"]
