# coding: utf-8
"""
NestJS API Client Emitter (CP20).

Module này chứa NestJSApiEmitter để emit OpenAPI module
và WebSocket gateway cho NestJS backend.

Templates (inline Jinja2):
  - openapi.module.ts
  - websocket.gateway.ts

Usage:
    from midicoder.emitters.core.api_client.nestjs import NestJSApiEmitter
    emitter = NestJSApiEmitter()
    files = emitter.generate(api_spec)

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from dataclasses import dataclass

from midicoder.emitters.core.cp20_api_client.models import ApiSpec


@dataclass
class NestJSApiEmitter:
    """Emitter cho NestJS API endpoints (CP20).

    Sinh ra:
    - openapi.module.ts — NestJS OpenAPI module
    - websocket.gateway.ts — Socket.IO gateway cho realtime bridge

    KPI: Type safety client↔backend, OpenAPI spec exposure.
    """

    def generate(self, spec: ApiSpec) -> dict[str, str]:
        """Sinh NestJS API files từ ApiSpec.

        Args:
            spec: ApiSpec chứa base_url, auth_mode, bridge

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}

        files["openapi.module.ts"] = self._emit_openapi_module(spec)
        files["websocket.gateway.ts"] = self._emit_websocket_gateway(spec)

        return files

    def _emit_openapi_module(self, spec: ApiSpec) -> str:
        """Sinh openapi.module.ts."""
        lines = [
            '/** OpenAPI Module — Auto-generated by Midicoder CE. */',
            "import { Module } from '@nestjs/common';",
            "import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';",
            "",
            "@Module({})",
            "export class OpenApiModule {",
            "  public setup(app: any): void {",
            '    const config = new DocumentBuilder()',
            '      .setTitle("API Specification")',
            '      .setDescription("Auto-generated by Midicoder CE")',
            '      .setVersion("1.0.0")',
            '      .build();',
            "    const document = SwaggerModule.createDocument(app, config);",
            '    SwaggerModule.setup("api/docs", app, document);',
            "  }",
            "}",
            "",
            "export default OpenApiModule;",
            "",
        ]
        return "\n".join(lines)

    def _emit_websocket_gateway(self, spec: ApiSpec) -> str:
        """Sinh websocket.gateway.ts."""
        lines = [
            '/** WebSocket Gateway — Auto-generated by Midicoder CE. */',
            "import {",
            "  WebSocketGateway,",
            "  WebSocketServer,",
            "  SubscribeMessage,",
            "  OnGatewayConnection,",
            "  OnGatewayDisconnect,",
            "} from '@nestjs/websockets';",
            "import { Server, Socket } from 'socket.io';",
            "",
            '@WebSocketGateway({ cors: { origin: "*" } })',
            "export class WsGateway implements OnGatewayConnection, OnGatewayDisconnect {",
            "  @WebSocketServer() server: Server;",
            "",
            "  handleConnection(client: Socket) {",
            "    console.log('Client connected:', client.id);",
            "  }",
            "",
            "  handleDisconnect(client: Socket) {",
            "    console.log('Client disconnected:', client.id);",
            "  }",
            "",
            '  @SubscribeMessage("subscribe")',
            "  handleSubscribe(client: Socket, payload: { channel: string }) {",
            '    client.join(payload.channel);',
            '    return { type: "subscribed", channel: payload.channel };',
            "  }",
            "",
            '  @SubscribeMessage("message")',
            "  handleMessage(client: Socket, payload: { channel: string; data: any }) {",
            '    this.server.to(payload.channel).emit("message", payload.data);',
            "  }",
            "}",
            "",
            "export default WsGateway;",
            "",
        ]
        return "\n".join(lines)


__all__ = ["NestJSApiEmitter"]
