# coding: utf-8
"""
Mô-đun FastAPI emitter cho Domain Pack Runtime Bridge (CP53).

Emit code FastAPI cho runtime bridge infrastructure:
- domain_registry.py: Đăng ký và discover domain packs
- bridge_bindings.py: Cấu hình binding từ CP capability → DP handler
- runtime_invoker.py: Dispatch engine để invoke DP tại runtime

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from typing import Any, Dict

from midicoder.emitters.core.domain_bridge.models import (
    BridgeBinding,
    DomainPackDescriptor,
    RuntimeInvoker,
)


# ============================================================================
# FastAPI Templates
# ============================================================================

FASTAPI_DOMAIN_REGISTRY = '''\
"""
Domain Pack Registry — Auto-generated by Midicoder CP53.

Quản lý đăng ký và discover domain packs tại runtime.
Mỗi domain pack được register với metadata đầy đủ để
runtime bridge có thể invoke đúng handler.
"""

from typing import Any, Dict, Optional


class DomainPackRegistry:
    """
    Singleton registry để discover và manage domain packs.

    Responsibility:
    - Register domain packs với metadata
    - Query packs theo ID hoặc capability
    - Validate pack existence trước khi invoke
    """

    _instance: Optional["DomainPackRegistry"] = None
    _packs: Dict[str, Dict[str, Any]]

    def __new__(cls) -> "DomainPackRegistry":
        """Pattern singleton — chỉ một registry instance trong app."""
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance._packs = {}
        return cls._instance

    def register(self, pack_id: str, descriptor: Dict[str, Any]) -> None:
        """
        Đăng ký domain pack vào registry.

        Args:
            pack_id: ID duy nhất của domain pack (vd: DP01)
            descriptor: Metadata của pack (capabilities, dependencies)

        Raises:
            ValueError: Nếu pack_id đã tồn tại
        """
        if pack_id in self._packs:
            raise ValueError(f"Domain pack {pack_id} đã được đăng ký")
        self._packs[pack_id] = descriptor

    def get(self, pack_id: str) -> Optional[Dict[str, Any]]:
        """
        Lấy descriptor của domain pack.

        Args:
            pack_id: ID của domain pack

        Returns:
            Descriptor dict hoặc None nếu không tìm thấy
        """
        return self._packs.get(pack_id)

    def has(self, pack_id: str) -> bool:
        """
        Kiểm tra domain pack đã được đăng ký chưa.

        Args:
            pack_id: ID của domain pack

        Returns:
            True nếu pack đã register
        """
        return pack_id in self._packs

    def find_by_capability(self, capability: str) -> list[str]:
        """
        Tìm các domain packs cung cấp capability cụ thể.

        Args:
            capability: Tên capability cần tìm

        Returns:
            Danh sách pack IDs cung cấp capability
        """
        result = []
        for pack_id, descriptor in self._packs.items():
            caps = descriptor.get("capabilities", [])
            if capability in caps:
                result.append(pack_id)
        return result

    def list_packs(self) -> list[str]:
        """
        Lấy danh sách tất cả pack IDs đã đăng ký.

        Returns:
            Danh sách pack IDs
        """
        return list(self._packs.keys())

    def clear(self) -> None:
        """Xóa tất cả packs đã đăng ký — dùng cho testing."""
        self._packs.clear()


# Instance mặc định cho toàn app
registry = DomainPackRegistry()
'''


FASTAPI_BRIDGE_BINDINGS = '''\
"""
Bridge Bindings Configuration — Auto-generated by Midicoder CP53.

Cấu hình ánh xạ từ CP capability (generic) đến DP handler
(domain-specific). Đây là cầu nối giữa generic CPs và
domain-specific implementations.
"""

from typing import Any, Callable, Dict, List, Optional
from .domain_registry import registry


class BridgeBindingConfig:
    """
    Configuration cho một bridge binding.

    Attributes:
        binding_id: ID duy nhất của binding
        cp_capability: CP capability cần bind
        dp_pack_id: Domain pack target
        dp_handler: Tên handler trong domain pack
        priority: Ưu tiên resolve (cao hơn = ưu tiên hơn)
    """

    def __init__(
        self,
        binding_id: str,
        cp_capability: str,
        dp_pack_id: str,
        dp_handler: str,
        priority: int = 0,
    ) -> None:
        self.binding_id = binding_id
        self.cp_capability = cp_capability
        self.dp_pack_id = dp_pack_id
        self.dp_handler = dp_handler
        self.priority = priority

    def to_dict(self) -> Dict[str, Any]:
        """Serialize thành dictionary."""
        return {
            "binding_id": self.binding_id,
            "cp_capability": self.cp_capability,
            "dp_pack_id": self.dp_pack_id,
            "dp_handler": self.dp_handler,
            "priority": self.priority,
        }


class BridgeBindingManager:
    """
    Quản lý bridge bindings giữa CPs và DPs.

    Responsibility:
    - Register bindings từ CP capability → DP handler
    - Resolve binding cho capability cụ thể
    - Validate DP target tồn tại trong registry
    """

    _instance: Optional["BridgeBindingManager"] = None
    _bindings: List[BridgeBindingConfig]

    def __new__(cls) -> "BridgeBindingManager":
        """Pattern singleton."""
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance._bindings = []
        return cls._instance

    def register_binding(self, config: BridgeBindingConfig) -> None:
        """
        Đăng ký bridge binding.

        Args:
            config: BridgeBindingConfig chứa binding info

        Raises:
            ValueError: Nếu DP target không tồn tại trong registry
        """
        if not registry.has(config.dp_pack_id):
            raise ValueError(
                f"Domain pack {config.dp_pack_id} chưa được đăng ký. "
                f"Hãy register pack trước khi tạo binding."
            )
        self._bindings.append(config)

    def resolve(self, cp_capability: str) -> Optional[BridgeBindingConfig]:
        """
        Resolve binding cho CP capability.

        Tìm binding có ưu tiên cao nhất cho capability.

        Args:
            cp_capability: CP capability cần resolve

        Returns:
            BridgeBindingConfig hoặc None nếu không tìm thấy
        """
        matches = [
            b for b in self._bindings if b.cp_capability == cp_capability
        ]
        if not matches:
            return None
        # Sort theo priority, cao hơn = ưu tiên hơn
        matches.sort(key=lambda b: b.priority, reverse=True)
        return matches[0]

    def list_bindings(self) -> List[BridgeBindingConfig]:
        """
        Lấy tất cả bindings đã đăng ký.

        Returns:
            Danh sách BridgeBindingConfig
        """
        return list(self._bindings)

    def clear(self) -> None:
        """Xóa tất cả bindings — dùng cho testing."""
        self._bindings.clear()


# Instance mặc định
binding_manager = BridgeBindingManager()
'''


FASTAPI_RUNTIME_INVOKER = '''\
"""
Runtime Invoker — Auto-generated by Midicoder CP53.

Dispatch engine để invoke DP capabilities tại runtime.
Invoker resolve binding từ CP capability, validate DP target,
và execute handler method.
"""

import asyncio
import time
from typing import Any, Callable, Dict, Optional

from .bridge_bindings import binding_manager
from .domain_registry import registry


class InvocationResult:
    """
    Kết quả của một runtime invocation.

    Attributes:
        success: Invocation thành công hay không
        data: Dữ liệu trả về từ handler
        error: Error message nếu fail
        latency_ms: Thời gian thực hiện (ms)
    """

    def __init__(
        self,
        success: bool,
        data: Any = None,
        error: Optional[str] = None,
        latency_ms: float = 0.0,
    ) -> None:
        self.success = success
        self.data = data
        self.error = error
        self.latency_ms = latency_ms

    def to_dict(self) -> Dict[str, Any]:
        """Serialize thành dictionary."""
        return {
            "success": self.success,
            "data": self.data,
            "error": self.error,
            "latency_ms": round(self.latency_ms, 2),
        }


class RuntimeInvoker:
    """
    Dispatch engine để invoke DP capabilities.

    Responsibility:
    - Resolve binding từ CP capability → DP handler
    - Validate DP target tồn tại
    - Execute handler với context và timeout
    - Handle retry nếu cấu hình

    Usage:
        invoker = RuntimeInvoker()
        result = invoker.invoke("create_record", {"entity": "Order", "data": {...}})
    """

    def __init__(self) -> None:
        """Khởi tạo RuntimeInvoker."""
        self._handlers: Dict[str, Callable] = {}

    def register_handler(self, handler_key: str, handler: Callable) -> None:
        """
        Đăng ký handler function.

        Args:
            handler_key: Key để lookup handler (format: "{dp_pack_id}:{handler_method}")
            handler: Callable function
        """
        self._handlers[handler_key] = handler

    def invoke(
        self,
        capability: str,
        context: Dict[str, Any],
        timeout_ms: int = 30000,
        retry_count: int = 0,
    ) -> InvocationResult:
        """
        Invoke DP capability thông qua bridge binding.

        Flow:
        1. Resolve binding cho capability
        2. Validate DP target trong registry
        3. Lookup handler
        4. Execute với timeout
        5. Return result

        Args:
            capability: CP capability cần invoke
            context: Context data cho handler
            timeout_ms: Timeout (ms) cho invocation
            retry_count: Số lần retry nếu fail

        Returns:
            InvocationResult chứa kết quả
        """
        start_time = time.time()
        attempts = 0
        last_error: Optional[str] = None

        while attempts <= retry_count:
            attempts += 1
            try:
                # Resolve binding
                binding = binding_manager.resolve(capability)
                if binding is None:
                    return InvocationResult(
                        success=False,
                        error=f"Không tìm thấy binding cho capability: {capability}",
                        latency_ms=self._elapsed(start_time),
                    )

                # Validate DP target
                if not registry.has(binding.dp_pack_id):
                    return InvocationResult(
                        success=False,
                        error=f"Domain pack {binding.dp_pack_id} chưa được đăng ký",
                        latency_ms=self._elapsed(start_time),
                    )

                # Lookup và execute handler
                handler_key = f"{binding.dp_pack_id}:{binding.dp_handler}"
                handler = self._handlers.get(handler_key)

                if handler is None:
                    # Handler chưa register — return result cho biết cần implement
                    return InvocationResult(
                        success=False,
                        error=f"Handler {handler_key} chưa được đăng ký",
                        latency_ms=self._elapsed(start_time),
                    )

                # Execute handler
                data = handler(context)
                return InvocationResult(
                    success=True,
                    data=data,
                    latency_ms=self._elapsed(start_time),
                )

            except Exception as e:
                last_error = str(e)
                if attempts <= retry_count:
                    continue

        return InvocationResult(
            success=False,
            error=f"Invocation fail sau {attempts} attempts: {last_error}",
            latency_ms=self._elapsed(start_time),
        )

    async def invoke_async(
        self,
        capability: str,
        context: Dict[str, Any],
        timeout_ms: int = 30000,
    ) -> InvocationResult:
        """
        Invoke DP capability (async version).

        Args:
            capability: CP capability cần invoke
            context: Context data cho handler
            timeout_ms: Timeout (ms)

        Returns:
            InvocationResult
        """
        start_time = time.time()
        try:
            binding = binding_manager.resolve(capability)
            if binding is None:
                return InvocationResult(
                    success=False,
                    error=f"Không tìm thấy binding cho capability: {capability}",
                    latency_ms=self._elapsed(start_time),
                )

            handler_key = f"{binding.dp_pack_id}:{binding.dp_handler}"
            handler = self._handlers.get(handler_key)

            if handler is None:
                return InvocationResult(
                    success=False,
                    error=f"Handler {handler_key} chưa được đăng ký",
                    latency_ms=self._elapsed(start_time),
                )

            data = await handler(context)
            return InvocationResult(
                success=True,
                data=data,
                latency_ms=self._elapsed(start_time),
            )

        except Exception as e:
            return InvocationResult(
                success=False,
                error=str(e),
                latency_ms=self._elapsed(start_time),
            )

    @staticmethod
    def _elapsed(start_time: float) -> float:
        """Tính thời gian đã trôi qua (ms)."""
        return (time.time() - start_time) * 1000


# Instance mặc định
invoker = RuntimeInvoker()
'''


# ============================================================================
# FastAPIDomainBridgeEmitter
# ============================================================================


class FastAPIDomainBridgeEmitter:
    """
    Emitter sinh code FastAPI cho Domain Pack Runtime Bridge.

    Emit:
    - app/bridge/domain_registry.py: Domain pack registry
    - app/bridge/bridge_bindings.py: Bridge binding configuration
    - app/bridge/runtime_invoker.py: Runtime dispatch engine

    Usage:
        emitter = FastAPIDomainBridgeEmitter()
        code = emitter.generate()
    """

    def generate(self) -> Dict[str, str]:
        """
        Generate toàn bộ files FastAPI cho CP53.

        Returns:
            Dict {file_path: source_code}
        """
        result: Dict[str, str] = {}
        result["app/bridge/__init__.py"] = self._emit_init()
        result["app/bridge/domain_registry.py"] = FASTAPI_DOMAIN_REGISTRY
        result["app/bridge/bridge_bindings.py"] = FASTAPI_BRIDGE_BINDINGS
        result["app/bridge/runtime_invoker.py"] = FASTAPI_RUNTIME_INVOKER
        return result

    def _emit_init(self) -> str:
        """Sinh __init__.py cho bridge package."""
        return '''\
"""
Domain Pack Runtime Bridge — Auto-generated by Midicoder CP53.

Runtime glue code để CP-generated code invoke DP-specific semantics.
"""

from .domain_registry import registry, DomainPackRegistry
from .bridge_bindings import (
    binding_manager,
    BridgeBindingManager,
    BridgeBindingConfig,
)
from .runtime_invoker import invoker, RuntimeInvoker, InvocationResult

__all__ = [
    "registry",
    "DomainPackRegistry",
    "binding_manager",
    "BridgeBindingManager",
    "BridgeBindingConfig",
    "invoker",
    "RuntimeInvoker",
    "InvocationResult",
]
'''
