# coding: utf-8
"""
Mô-đun NestJS emitter cho Domain Pack Runtime Bridge (CP53).

Emit code NestJS cho runtime bridge infrastructure:
- domain-registry.ts: Đăng ký và discover domain packs
- bridge-bindings.ts: Cấu hình binding từ CP capability → DP handler
- runtime-invoker.ts: Dispatch engine để invoke DP tại runtime

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

from typing import Any, Dict

from midicoder.packs.domain_bridge.models import (
    BridgeBinding,
    DomainPackDescriptor,
    RuntimeInvoker,
)


# ============================================================================
# NestJS Templates
# ============================================================================

NESTJS_DOMAIN_REGISTRY = '''\
/**
 * Domain Pack Registry — Auto-generated by Midicoder CP53.
 *
 * Quản lý đăng ký và discover domain packs tại runtime.
 * Mỗi domain pack được register với metadata đầy đủ để
 * runtime bridge có thể invoke đúng handler.
 */

export interface DomainPackDescriptor {
  packId: string;
  internalId: string;
  name: string;
  capabilities: string[];
  dependsOn?: string[];
  metadata?: Record<string, any>;
}

export class DomainPackRegistry {
  private static instance: DomainPackRegistry;
  private packs: Map<string, DomainPackDescriptor> = new Map();

  private constructor() {}

  /**
   * Singleton instance — chỉ một registry trong app.
   */
  static getInstance(): DomainPackRegistry {
    if (!DomainPackRegistry.instance) {
      DomainPackRegistry.instance = new DomainPackRegistry();
    }
    return DomainPackRegistry.instance;
  }

  /**
   * Đăng ký domain pack vào registry.
   *
   * @param packId - ID duy nhất của domain pack
   * @param descriptor - Metadata của pack
   * @throws Error nếu packId đã tồn tại
   */
  register(packId: string, descriptor: DomainPackDescriptor): void {
    if (this.packs.has(packId)) {
      throw new Error(`Domain pack ${packId} đã được đăng ký`);
    }
    this.packs.set(packId, descriptor);
  }

  /**
   * Lấy descriptor của domain pack.
   *
   * @param packId - ID của domain pack
   * @returns Descriptor hoặc undefined nếu không tìm thấy
   */
  get(packId: string): DomainPackDescriptor | undefined {
    return this.packs.get(packId);
  }

  /**
   * Kiểm tra domain pack đã được đăng ký chưa.
   *
   * @param packId - ID của domain pack
   * @returns True nếu pack đã register
   */
  has(packId: string): boolean {
    return this.packs.has(packId);
  }

  /**
   * Tìm các domain packs cung cấp capability cụ thể.
   *
   * @param capability - Tên capability cần tìm
   * @returns Danh sách pack IDs
   */
  findByCapability(capability: string): string[] {
    const result: string[] = [];
    for (const [packId, descriptor] of this.packs.entries()) {
      if (descriptor.capabilities.includes(capability)) {
        result.push(packId);
      }
    }
    return result;
  }

  /**
   * Lấy danh sách tất cả pack IDs đã đăng ký.
   */
  listPacks(): string[] {
    return Array.from(this.packs.keys());
  }

  /**
   * Xóa tất cả packs — dùng cho testing.
   */
  clear(): void {
    this.packs.clear();
  }
}

// Export singleton instance
export const registry = DomainPackRegistry.getInstance();
'''


NESTJS_BRIDGE_BINDINGS = '''\
/**
 * Bridge Bindings Configuration — Auto-generated by Midicoder CP53.
 *
 * Cấu hình ánh xạ từ CP capability (generic) đến DP handler
 * (domain-specific). Đây là cầu nối giữa generic CPs và
 * domain-specific implementations.
 */

import { registry } from "./domain-registry";

export interface BridgeBindingConfig {
  bindingId: string;
  cpCapability: string;
  dpPackId: string;
  dpHandler: string;
  priority?: number;
}

export class BridgeBindingManager {
  private static instance: BridgeBindingManager;
  private bindings: BridgeBindingConfig[] = [];

  private constructor() {}

  /**
   * Singleton instance.
   */
  static getInstance(): BridgeBindingManager {
    if (!BridgeBindingManager.instance) {
      BridgeBindingManager.instance = new BridgeBindingManager();
    }
    return BridgeBindingManager.instance;
  }

  /**
   * Đăng ký bridge binding.
   *
   * @param config - BridgeBindingConfig chứa binding info
   * @throws Error nếu DP target không tồn tại trong registry
   */
  registerBinding(config: BridgeBindingConfig): void {
    if (!registry.has(config.dpPackId)) {
      throw new Error(
        `Domain pack ${config.dpPackId} chưa được đăng ký. ` +
        `Hãy register pack trước khi tạo binding.`
      );
    }
    this.bindings.push(config);
  }

  /**
   * Resolve binding cho CP capability.
   *
   * Tìm binding có ưu tiên cao nhất cho capability.
   *
   * @param cpCapability - CP capability cần resolve
   * @returns BridgeBindingConfig hoặc null
   */
  resolve(cpCapability: string): BridgeBindingConfig | null {
    const matches = this.bindings.filter(
      (b) => b.cpCapability === cpCapability
    );
    if (matches.length === 0) {
      return null;
    }
    // Sort theo priority, cao hơn = ưu tiên hơn
    matches.sort((a, b) => (b.priority || 0) - (a.priority || 0));
    return matches[0];
  }

  /**
   * Lấy tất cả bindings đã đăng ký.
   */
  listBindings(): BridgeBindingConfig[] {
    return [...this.bindings];
  }

  /**
   * Xóa tất cả bindings — dùng cho testing.
   */
  clear(): void {
    this.bindings = [];
  }
}

// Export singleton instance
export const bindingManager = BridgeBindingManager.getInstance();
'''


NESTJS_RUNTIME_INVOKER = '''\
/**
 * Runtime Invoker — Auto-generated by Midicoder CP53.
 *
 * Dispatch engine để invoke DP capabilities tại runtime.
 * Invoker resolve binding từ CP capability, validate DP target,
 * và execute handler method.
 */

import { bindingManager } from "./bridge-bindings";
import { registry } from "./domain-registry";

export interface InvocationContext {
  [key: string]: any;
}

export interface InvocationResult {
  success: boolean;
  data?: any;
  error?: string;
  latencyMs: number;
}

export type HandlerFn = (context: InvocationContext) => any | Promise<any>;

export class RuntimeInvoker {
  private handlers: Map<string, HandlerFn> = new Map();

  /**
   * Đăng ký handler function.
   *
   * @param handlerKey - Key để lookup (format: "{dpPackId}:{handlerMethod}")
   * @param handler - Callable function
   */
  registerHandler(handlerKey: string, handler: HandlerFn): void {
    this.handlers.set(handlerKey, handler);
  }

  /**
   * Invoke DP capability thông qua bridge binding.
   *
   * Flow:
   * 1. Resolve binding cho capability
   * 2. Validate DP target trong registry
   * 3. Lookup handler
   * 4. Execute với timeout
   * 5. Return result
   *
   * @param capability - CP capability cần invoke
   * @param context - Context data cho handler
   * @param timeoutMs - Timeout (ms) cho invocation
   * @param retryCount - Số lần retry nếu fail
   * @returns InvocationResult
   */
  async invoke(
    capability: string,
    context: InvocationContext,
    timeoutMs: number = 30000,
    retryCount: number = 0,
  ): Promise<InvocationResult> {
    const startTime = Date.now();
    let attempts = 0;
    let lastError: string | null = null;

    while (attempts <= retryCount) {
      attempts++;
      try {
        // Resolve binding
        const binding = bindingManager.resolve(capability);
        if (!binding) {
          return {
            success: false,
            error: `Không tìm thấy binding cho capability: ${capability}`,
            latencyMs: Date.now() - startTime,
          };
        }

        // Validate DP target
        if (!registry.has(binding.dpPackId)) {
          return {
            success: false,
            error: `Domain pack ${binding.dpPackId} chưa được đăng ký`,
            latencyMs: Date.now() - startTime,
          };
        }

        // Lookup và execute handler
        const handlerKey = `${binding.dpPackId}:${binding.dpHandler}`;
        const handler = this.handlers.get(handlerKey);

        if (!handler) {
          return {
            success: false,
            error: `Handler ${handlerKey} chưa được đăng ký`,
            latencyMs: Date.now() - startTime,
          };
        }

        // Execute handler với timeout
        const data = await Promise.race([
          handler(context),
          new Promise((_, reject) =>
            setTimeout(() => reject(new Error("Timeout")), timeoutMs)
          ),
        ]);

        return {
          success: true,
          data,
          latencyMs: Date.now() - startTime,
        };
      } catch (error: any) {
        lastError = error.message || String(error);
        if (attempts <= retryCount) {
          continue;
        }
      }
    }

    return {
      success: false,
      error: `Invocation fail sau ${attempts} attempts: ${lastError}`,
      latencyMs: Date.now() - startTime,
    };
  }

  /**
   * Invoke đồng bộ (sync) — không await handler.
   *
   * @param capability - CP capability cần invoke
   * @param context - Context data cho handler
   * @returns InvocationResult
   */
  invokeSync(
    capability: string,
    context: InvocationContext,
  ): InvocationResult {
    const startTime = Date.now();
    try {
      const binding = bindingManager.resolve(capability);
      if (!binding) {
        return {
          success: false,
          error: `Không tìm thấy binding cho capability: ${capability}`,
          latencyMs: Date.now() - startTime,
        };
      }

      const handlerKey = `${binding.dpPackId}:${binding.dpHandler}`;
      const handler = this.handlers.get(handlerKey);

      if (!handler) {
        return {
          success: false,
          error: `Handler ${handlerKey} chưa được đăng ký`,
          latencyMs: Date.now() - startTime,
        };
      }

      const data = handler(context);
      return {
        success: true,
        data,
        latencyMs: Date.now() - startTime,
      };
    } catch (error: any) {
      return {
        success: false,
        error: error.message || String(error),
        latencyMs: Date.now() - startTime,
      };
    }
  }
}

// Export singleton instance
export const invoker = new RuntimeInvoker();
'''


# ============================================================================
# NestJSDomainBridgeEmitter
# ============================================================================


class NestJSDomainBridgeEmitter:
    """
    Emitter sinh code NestJS cho Domain Pack Runtime Bridge.

    Emit:
    - src/bridge/domain-registry.ts: Domain pack registry
    - src/bridge/bridge-bindings.ts: Bridge binding configuration
    - src/bridge/runtime-invoker.ts: Runtime dispatch engine

    Usage:
        emitter = NestJSDomainBridgeEmitter()
        code = emitter.generate()
    """

    def generate(self) -> Dict[str, str]:
        """
        Generate toàn bộ files NestJS cho CP53.

        Returns:
            Dict {file_path: source_code}
        """
        result: Dict[str, str] = {}
        result["src/bridge/domain-registry.ts"] = NESTJS_DOMAIN_REGISTRY
        result["src/bridge/bridge-bindings.ts"] = NESTJS_BRIDGE_BINDINGS
        result["src/bridge/runtime-invoker.ts"] = NESTJS_RUNTIME_INVOKER
        return result
