# coding: utf-8
"""
SQLAlchemy Emitter - Sinh SQLAlchemy models cho FastAPI backend.

Module nay chua SQLAlchemyEmitter de render SQLAlchemy model files
tu DataModelCollection su dung Jinja2 templates.

Author: Midicoder Team
Version: 1.0.0
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from midicoder.packs.cp_backend_database.models import (
    DataModel,
    DataModelCollection,
    ColumnType,
    Datasource,
    DatabaseEngine,
    SpatialColumn,
    SpatialIndex,
    TimeSeriesModel,
    RetentionPolicy,
    ReadModel,
    DistributedTransaction,
    TransactionParticipant,
    JSONBColumn,
    JSONBIndex,
)


# Mapping tu ColumnType sang SQLAlchemy type
_SQLALCHEMY_TYPE_MAP = {
    ColumnType.STRING: "String",
    ColumnType.INTEGER: "Integer",
    ColumnType.BOOLEAN: "Boolean",
    ColumnType.DECIMAL: "Numeric",
    ColumnType.TEXT: "Text",
    ColumnType.JSON: "JSON",
    ColumnType.DATETIME: "DateTime",
    ColumnType.UUID: "String",
    ColumnType.ARRAY: "String",
    ColumnType.BYTES: "LargeBinary",
    ColumnType.TIME: "Time",
}

# Chuoi docstring 3 dau gach dau
_TRIPLE_DQ = '"""'
# Chuoi docstring 3 dau gach dau dan
_TRIPLE_SQ = "'''"


@dataclass
class SQLAlchemyEmitter:
    """
    Emitter de sinh SQLAlchemy model files cho FastAPI.

    Render models tu DataModelCollection sang SQLAlchemy classes.
    KPI-029: Tenant isolation qua tenant_id column.
    """

    def emit(
        self,
        collection: DataModelCollection,
        output_dir: Path,
    ) -> dict[str, str]:
        """
        Emit SQLAlchemy model files tu DataModelCollection.

        Args:
            collection: Collection chua cac data models
            output_dir: Directory de luu files

        Returns:
            Dictionary {file_path: content}
        """
        files: dict[str, str] = {}
        models_dir = output_dir / "models"
        models_dir.mkdir(parents=True, exist_ok=True)

        if not collection.models:
            return files

        for model in collection.models:
            filename = f"{self._to_snake_case(model.id)}.py"
            content = self._emit_model_file(model)
            file_key = str((models_dir / filename).relative_to(output_dir)).replace("\\", "/")
            files[file_key] = content

        # Sinh __init__.py
        init_key = str((models_dir / "__init__.py").relative_to(output_dir)).replace("\\", "/")
        files[init_key] = self._emit_models_init(collection)

        return files

    def _emit_model_file(self, model: DataModel) -> str:
        """Sinh SQLAlchemy model file cho mot model."""
        lines: list[str] = []
        class_name = model.id

        lines.append(_TRIPLE_DQ)
        lines.append(f"SQLAlchemy Model: {class_name}")
        lines.append(f"Table: {model.table_name}")
        if model.description:
            lines.append(f"Description: {model.description}")
        lines.append("")
        lines.append("Auto-generated by Midicoder CE.")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from __future__ import annotations")
        lines.append("")
        lines.append("from sqlalchemy import String, Integer, Boolean, Numeric, Text, DateTime, Index")
        lines.append("from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship")
        lines.append("from typing import Optional")
        lines.append("")
        lines.append("")

        # KPI-029: Tenant mixin
        if model.tenant_isolated:
            lines.append("# KPI-029: Tenant Isolation enforced")
            lines.append("")

        lines.append(f"class {class_name}(Base):")
        lines.append(f"    {_TRIPLE_DQ}{model.description or model.table_name}{_TRIPLE_DQ}")
        lines.append(f"    __tablename__ = '{model.table_name}'")
        lines.append("")

        # Columns
        for col in model.columns:
            sa_type = _SQLALCHEMY_TYPE_MAP.get(col.column_type, "String")
            col_options = []

            if col.primary_key:
                col_options.append("primary_key=True")
            if col.required and not col.primary_key:
                col_options.append("nullable=False")
            if col.unique:
                col_options.append("unique=True")
            if col.max_length and sa_type == "String":
                col_options.append(f"length={col.max_length}")
            if col.precision and sa_type == "Numeric":
                col_options.append(f"precision={col.precision}")
                if col.scale:
                    col_options.append(f"scale={col.scale}")
            if col.tenant_aware:
                col_options.append("# KPI-029: Tenant isolation")

            options_str = ", ".join(col_options)
            if options_str:
                lines.append(f"    {col.name}: Mapped[{sa_type}] = mapped_column({options_str})")
            else:
                lines.append(f"    {col.name}: Mapped[{sa_type}] = mapped_column()")

        # Relationships
        for rel in model.relationships:
            rel_name = self._to_snake_case(rel.target_model) + "_rel"
            lines.append(f"    {rel_name} = relationship('{rel.target_model}')")

        lines.extend(["", ""])
        return "\n".join(lines)

    def _emit_models_init(self, collection: DataModelCollection) -> str:
        """Sinh __init__.py cho models directory."""
        lines = [f'{_TRIPLE_DQ}Models package - auto-generated by Midicoder CE.{_TRIPLE_DQ}', ""]
        for model in collection.models:
            import_name = self._to_snake_case(model.id)
            lines.append(f"from .{import_name} import {model.id}")
        lines.append("")
        lines.append("__all__ = [")
        for model in collection.models:
            lines.append(f'    "{model.id}",')
        lines.append("]")
        return "\n".join(lines)

    def emit_connection_config(self, datasource: Datasource) -> dict[str, str]:
        """
        Sinh file database.py voi engine + pool config.

        Args:
            datasource: Datasource config de sinh connection code

        Returns:
            Dictionary {file_path: content}
        """
        lines: list[str] = []
        lines.append(_TRIPLE_DQ)
        lines.append(f"Database connection configuration - Auto-generated by Midicoder CE.")
        lines.append(f"Datasource: {datasource.name}")
        lines.append(f"Engine: {datasource.engine.value}")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from sqlalchemy import create_engine")
        lines.append("from sqlalchemy.orm import sessionmaker, DeclarativeBase")
        lines.append("from sqlalchemy.pool import QueuePool")
        lines.append("import os")
        lines.append("")
        lines.append("")
        lines.append(f"# Connection string (de: ${{{datasource.name}_URL}})")
        lines.append("DATABASE_URL = os.environ.get(")
        lines.append(f'    "{datasource.name.upper()}_URL",')
        lines.append(f'    "{datasource.connection_string}",')
        lines.append(")")
        lines.append("")
        lines.append("")
        lines.append("# Engine voi pool config")
        lines.append("engine = create_engine(")
        lines.append("    DATABASE_URL,")
        lines.append(f"    pool_size={datasource.pool_size},")
        lines.append(f"    max_overflow={datasource.max_overflow},")
        lines.append(f"    pool_timeout={datasource.pool_timeout},")
        lines.append(f"    pool_recycle={datasource.pool_recycle},")
        lines.append(f"    poolclass=QueuePool,")
        if datasource.ssl_enabled:
            lines.append("    connect_args={'ssl': True},")
        lines.append(")")
        lines.append("")
        lines.append("")
        lines.append("SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)")
        lines.append("")
        lines.append("")
        lines.append("class Base(DeclarativeBase):")
        lines.append(f"    {_TRIPLE_DQ}Base class for all SQLAlchemy models.{_TRIPLE_DQ}")
        lines.append("    pass")
        lines.append("")
        lines.append("")
        lines.append("def get_db():")
        lines.append(f"    {_TRIPLE_DQ}Dependency provider cho database session.{_TRIPLE_DQ}")
        lines.append("    db = SessionLocal()")
        lines.append("    try:")
        lines.append("        yield db")
        lines.append("    finally:")
        lines.append("        db.close()")

        # Sinh read replica config neu co
        if datasource.read_replicas:
            lines.append("")
            lines.append("")
            lines.append("# Read Replicas")
            for replica in datasource.read_replicas:
                replica_name = replica.name.upper()
                lines.append(f"{replica.name}_engine = create_engine(")
                lines.append(f'    os.environ.get("{replica_name}_URL", "{replica.connection_string}"),')
                lines.append(f"    pool_size={datasource.pool_size},")
                lines.append(")")

        return {"database.py": "\n".join(lines)}

    def emit_base_repository(self) -> dict[str, str]:
        """
        Sinh BaseRepository voi CRUD + tenant filter.

        Returns:
            Dictionary {file_path: content}
        """
        lines: list[str] = []
        lines.append(_TRIPLE_DQ)
        lines.append("Base Repository - CRUD base class voi tenant isolation (KPI-029)")
        lines.append("Auto-generated by Midicoder CE.")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from __future__ import annotations")
        lines.append("")
        lines.append("from typing import Any, Generic, TypeVar, Optional, Sequence")
        lines.append("from sqlalchemy.orm import Session")
        lines.append("")
        lines.append("")
        lines.append("ModelType = TypeVar('ModelType')")
        lines.append("")
        lines.append("")
        lines.append("class BaseRepository(Generic[ModelType]):")
        lines.append(f"    {_TRIPLE_DQ}Base repository voi CRUD operations va tenant isolation (KPI-029).")
        lines.append("    Usage:")
        lines.append("        class UserRepository(BaseRepository[User]):")
        lines.append("            model_class = User")
        lines.append(f"    {_TRIPLE_DQ}")
        lines.append("")
        lines.append("    model_class: type[ModelType]")
        lines.append("")
        lines.append("    def __init__(self, db: Session, tenant_id: str | None = None):")
        lines.append(f"        {_TRIPLE_DQ}Khai bao repository voi database session va tenant context.{_TRIPLE_DQ}")
        lines.append("        self.db = db")
        lines.append("        self.tenant_id = tenant_id")
        lines.append("")
        lines.append("    def get(self, id: Any) -> Optional[ModelType]:")
        lines.append(f"        {_TRIPLE_DQ}Lay record theo ID.{_TRIPLE_DQ}")
        lines.append("        return self.db.get(self.model_class, id)")
        lines.append("")
        lines.append("    def list(self, **filters: Any) -> Sequence[ModelType]:")
        lines.append(f"        {_TRIPLE_DQ}Lay danh sach records voi filters.{_TRIPLE_DQ}")
        lines.append("        query = self.db.query(self.model_class)")
        lines.append("        # KPI-029: Tu dong filter theo tenant_id neu co")
        lines.append("        if self.tenant_id:")
        lines.append("            query = query.filter_by(tenant_id=self.tenant_id)")
        lines.append("        for key, value in filters.items():")
        lines.append("            if value is not None:")
        lines.append("                query = query.filter(**{key: value})")
        lines.append("        return query.all()")
        lines.append("")
        lines.append("    def create(self, obj: ModelType) -> ModelType:")
        lines.append(f"        {_TRIPLE_DQ}Tao record moi.{_TRIPLE_DQ}")
        lines.append("        self.db.add(obj)")
        lines.append("        self.db.commit()")
        lines.append("        self.db.refresh(obj)")
        lines.append("        return obj")
        lines.append("")
        lines.append("    def update(self, id: Any, **kwargs: Any) -> Optional[ModelType]:")
        lines.append(f"        {_TRIPLE_DQ}Cap nhat record theo ID.{_TRIPLE_DQ}")
        lines.append("        obj = self.get(id)")
        lines.append("        if obj:")
        lines.append("            for key, value in kwargs.items():")
        lines.append("                setattr(obj, key, value)")
        lines.append("            self.db.commit()")
        lines.append("            self.db.refresh(obj)")
        lines.append("        return obj")
        lines.append("")
        lines.append("    def delete(self, id: Any) -> bool:")
        lines.append(f"        {_TRIPLE_DQ}Xoa record theo ID.{_TRIPLE_DQ}")
        lines.append("        obj = self.get(id)")
        lines.append("        if obj:")
        lines.append("            self.db.delete(obj)")
        lines.append("            self.db.commit()")
        lines.append("            return True")
        lines.append("        return False")

        return {"repositories/base_repository.py": "\n".join(lines)}

    def emit_migration(self, model: DataModel, version: str) -> dict[str, str]:
        """
        Sinh Alembic migration file cho model.

        Args:
            model: DataModel de sinh migration
            version: Version revision ID

        Returns:
            Dictionary {file_path: content}
        """
        lines: list[str] = []
        lines.append(_TRIPLE_DQ)
        lines.append(f"Create {model.table_name} table")
        lines.append("")
        lines.append(f"Revision ID: {version}")
        lines.append("Revises: ")
        lines.append("Create Date: 2026-05-06")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from alembic import op")
        lines.append("import sqlalchemy as sa")
        lines.append("")
        lines.append("")
        lines.append(f"revision = '{version}'")
        lines.append("down_revision = None")
        lines.append("branch_labels = None")
        lines.append("depends_on = None")
        lines.append("")
        lines.append("")
        lines.append("def upgrade() -> None:")
        lines.append(f'    op.create_table("{model.table_name}",')

        # Columns
        for col in model.columns:
            sa_type = _SQLALCHEMY_TYPE_MAP.get(col.column_type, "sa.String")
            nullable = "nullable=True" if not col.required and not col.primary_key else "nullable=False"
            col_line = f'        sa.Column("{col.name}", {sa_type}, {nullable})'
            if col.primary_key:
                col_line = f'        sa.Column("{col.name}", {sa_type}, primary_key=True)'
            lines.append(col_line + ",")

        lines.append("    )")

        # Indexes
        for idx in model.indexes:
            unique_param = "unique=True" if idx.unique else "unique=False"
            lines.append(f'    op.create_index(op.f("{idx.name}"), "{model.table_name}", {idx.columns}, {unique_param})')

        lines.append("")
        lines.append("")
        lines.append("def downgrade() -> None:")
        # Reverse indexes
        for idx in model.indexes:
            lines.append(f'    op.drop_index(op.f("{idx.name}"), table_name="{model.table_name}")')
        lines.append(f'    op.drop_table("{model.table_name}")')

        filename = f"migrations/versions/{version}_create_{model.table_name}.py"
        return {filename: "\n".join(lines)}

    def emit_seed_data(self, models: list[DataModel]) -> dict[str, str]:
        """
        Sinh seed data Python script.

        Args:
            models: Danh sach models de sinh seed data

        Returns:
            Dictionary {file_path: content}
        """
        lines: list[str] = []
        lines.append(_TRIPLE_DQ)
        lines.append("Seed data script - Auto-generated by Midicoder CE.")
        lines.append("Su dung: python seed_data.py")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from sqlalchemy.orm import Session")
        lines.append("from database import SessionLocal, Base, engine")
        lines.append("")
        lines.append("")
        lines.append("def seed():")
        lines.append(f"    {_TRIPLE_DQ}Tao seed data cho cac bang.{_TRIPLE_DQ}")
        lines.append("    Base.metadata.create_all(bind=engine)")
        lines.append("    db = SessionLocal()")
        lines.append("    try:")
        for model in models:
            lines.append(f"        # Seed data cho {model.table_name}")
            lines.append(f'        print(f"Seeding {model.table_name}...")')
            lines.append("")
        lines.append('        print("Seed data completed!")')
        lines.append("    finally:")
        lines.append("        db.close()")
        lines.append("")
        lines.append("")
        lines.append(f"if __name__ == '{_TRIPLE_SQ}__main__{_TRIPLE_SQ}':")
        lines.append("    seed()")

        return {"seed_data.py": "\n".join(lines)}

    @staticmethod
    def _to_snake_case(name: str) -> str:
        """Chuyen PascalCase sang snake_case."""
        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
        return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()

    # ------------------------------------------------------------------
    # Advanced Capabilities
    # ------------------------------------------------------------------

    def emit_spatial_columns(self, columns: list[SpatialColumn]) -> dict[str, str]:
        """Sinh PostGIS spatial helper module."""
        lines: list[str] = []
        lines.append(_TRIPLE_DQ)
        lines.append("PostGIS Spatial Helpers — Auto-generated by Midicoder CE.")
        lines.append("Obligation: All spatial columns must declare explicit SRID (default: 4326 WGS84)")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from sqlalchemy import Column, Index")
        lines.append("from sqlalchemy.ext.mutable import Mutable")
        lines.append("")
        lines.append("")
        lines.append("# PostGIS spatial column types")
        lines.append("# Obligation: All spatial columns must declare explicit SRID (default: 4326 WGS84)")
        lines.append("DEFAULT_SRID = 4326")
        lines.append("")
        lines.append("")

        for col in columns:
            srid_val = col.srid or 4326
            safe_name = col.name.replace("_", "").title()
            lines.append(f"class {safe_name}Geometry(Mutable):")
            lines.append(f"    {_TRIPLE_DQ}PostGIS {col.spatial_type.value} column (SRID={srid_val}).{_TRIPLE_DQ}")
            lines.append(f"    __dialect_name__ = '{col.spatial_type.value.lower()}'")
            lines.append(f"    srid = {srid_val}")
            lines.append("")

        lines.append("")
        lines.append("def spatial_distance(column, lon: float, lat: float, radius_km: float):")
        lines.append(f"    {_TRIPLE_DQ}ST_DWithin query — find points within radius_km.{_TRIPLE_DQ}")
        lines.append("    from sqlalchemy import text")
        lines.append("    radius_m = radius_km * 1000")
        lines.append("    return text(f\"ST_DWithin({column}, ST_Point(:lon, :lat, 4326), :radius_m)\")")
        lines.append("")
        lines.append("")
        lines.append("def spatial_contains(polygon_col, point_col):")
        lines.append(f"    {_TRIPLE_DQ}ST_Contains query — check if polygon contains point.{_TRIPLE_DQ}")
        lines.append("    from sqlalchemy import text")
        lines.append("    return text(f\"ST_Contains({polygon_col}, {point_col})\")")

        return {"spatial/spatial_helpers.py": "\n".join(lines)}

    def emit_spatial_index(self, indexes: list[SpatialIndex]) -> dict[str, str]:
        """Sinh spatial index migration SQL helper."""
        lines: list[str] = []
        lines.append(_TRIPLE_DQ)
        lines.append("Spatial Index Definitions — Auto-generated by Midicoder CE.")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from alembic import op")
        lines.append("")
        lines.append("")
        lines.append("def create_spatial_indexes():")
        lines.append(f"    {_TRIPLE_DQ}Create GiST/SP-GiST/BRIN indexes for spatial columns.{_TRIPLE_DQ}")
        for idx in indexes:
            lines.append(f'    op.create_index("{idx.name}", table_name="{idx.column}_table", columns=["{idx.column}"], postgresql_using="{idx.index_type.value}")')
        lines.append("")
        lines.append("")
        lines.append("def drop_spatial_indexes():")
        for idx in indexes:
            lines.append(f'    op.drop_index("{idx.name}")')

        return {"spatial/spatial_indexes.py": "\n".join(lines)}

    def emit_time_series_model(self, model: TimeSeriesModel) -> dict[str, str]:
        """Sinh time-series model với partitioning."""
        lines: list[str] = []
        lines.append(_TRIPLE_DQ)
        lines.append(f"Time-Series Model: {model.id}")
        lines.append(f"Timestamp Column: {model.timestamp_column}")
        lines.append(f"Granularity: {model.granularity.value}")
        if model.retention_policy:
            lines.append(f"Retention: {model.retention_policy.policy_type.value} — threshold={model.retention_policy.threshold}")
        lines.append("")
        lines.append("Auto-generated by Midicoder CE.")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from __future__ import annotations")
        lines.append("")
        lines.append("from datetime import datetime")
        lines.append("from sqlalchemy import Column, String, DateTime, Integer, Index")
        lines.append("from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column")
        lines.append("from typing import Optional")
        lines.append("")
        lines.append("")
        lines.append(f"class {model.id}(Base):")
        lines.append(f"    {_TRIPLE_DQ}Time-series partitioned table.")
        lines.append(f"    Timestamp column: {model.timestamp_column}")
        lines.append(f"    Granularity: {model.granularity.value}")
        if model.retention_policy:
            lines.append(f"    Retention: {model.retention_policy.policy_type.value}")
        lines.append(f"    {_TRIPLE_DQ}")
        lines.append(f"    __tablename__ = '{model.table_name}'")
        lines.append("")
        lines.append(f"    id: Mapped[str] = mapped_column(primary_key=True)")
        lines.append(f"    {model.timestamp_column}: Mapped[datetime] = mapped_column(nullable=False, index=True)")

        for vc in model.value_columns:
            lines.append(f"    {vc}: Mapped[Optional[float]] = mapped_column(nullable=True)")
        for gc in model.grain_columns:
            lines.append(f"    {gc}: Mapped[Optional[str]] = mapped_column(nullable=True)")

        if model.retention_policy:
            lines.append("")
            lines.append(f"    # Retention: {model.retention_policy.policy_type.value} — threshold={model.retention_policy.threshold}")

        lines.extend(["", ""])
        lines.append("")
        lines.append(f"# Migration: create partitioned time-series table")
        lines.append(f"# Run via Alembic migration:")
        lines.append(f"#   SELECT create_hypertable('{model.table_name}', '{model.timestamp_column}',")
        lines.append(f"#       timescaledb.skip_custom_backfill := true,")
        lines.append(f"#       number_partitions := 4);")
        if model.retention_policy:
            lines.append(f"#   SELECT add_retention_policy('{model.table_name}', INTERVAL '{model.retention_policy.threshold} days');")

        filename = f"time_series/{model.table_name}.py"
        return {filename: "\n".join(lines)}

    def emit_read_model(self, read_model: ReadModel) -> dict[str, str]:
        """Sinh CQRS read model (materialized view / denormalized table)."""
        lines: list[str] = []
        lines.append(_TRIPLE_DQ)
        lines.append(f"CQRS Read Model: {read_model.id}")
        lines.append(f"Source: {read_model.source.value}")
        lines.append(f"Refresh: {read_model.refresh_strategy.value}")
        lines.append("")
        lines.append("Auto-generated by Midicoder CE.")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from __future__ import annotations")
        lines.append("from datetime import datetime")
        lines.append("")
        lines.append("from sqlalchemy import Column, String, DateTime, Integer")
        lines.append("from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column")
        lines.append("from typing import Optional")
        lines.append("")
        lines.append("")
        lines.append(f"class {read_model.id}(Base):")
        lines.append(f"    {_TRIPLE_DQ}Read model — {read_model.source.value}")
        lines.append(f"    Refresh strategy: {read_model.refresh_strategy.value}")
        lines.append(f"    Source tables: {', '.join(read_model.source_models)}")
        lines.append(f"    {_TRIPLE_DQ}")
        lines.append(f"    __tablename__ = '{read_model.table_name}'")
        lines.append("")
        lines.append(f"    id: Mapped[str] = mapped_column(primary_key=True)")

        for col in read_model.columns:
            sa_type = _SQLALCHEMY_TYPE_MAP.get(col.column_type, "String")
            col_options = []
            if col.required:
                col_options.append("nullable=False")
            options_str = ", ".join(col_options)
            if options_str:
                lines.append(f"    {col.name}: Mapped[{sa_type}] = mapped_column({options_str})")
            else:
                lines.append(f"    {col.name}: Mapped[{sa_type}] = mapped_column()")

        lines.append("")
        lines.append(f"    last_refreshed_at: Mapped[Optional[datetime]] = mapped_column(nullable=True)")

        lines.append("")
        lines.append(f"    @classmethod")
        lines.append(f"    def refresh(cls, db):")
        lines.append(f"        {_TRIPLE_DQ}Refresh read model from source tables.{_TRIPLE_DQ}")
        strategy = read_model.refresh_strategy.value
        if strategy == "real_time":
            lines.append(f"        # Real-time: triggered by event handler on every write")
        elif strategy == "batch":
            lines.append(f"        # Batch: scheduled CRON job")
        elif strategy == "lazy":
            lines.append(f"        # Lazy: refreshed on first read after staleness threshold")
        elif strategy == "event_driven":
            lines.append(f"        # Event-driven: triggered by domain events")
        lines.append(f"        pass  # implementation depends on source_tables")

        lines.extend(["", ""])

        filename = f"read_models/{read_model.table_name}.py"
        return {filename: "\n".join(lines)}

    def emit_distributed_transaction(self, tx: DistributedTransaction) -> dict[str, str]:
        """Sinh distributed transaction coordinator (Saga/2PC/Outbox/TCC)."""
        lines: list[str] = []
        lines.append(_TRIPLE_DQ)
        lines.append(f"Distributed Transaction: {tx.id}")
        lines.append(f"Protocol: {tx.protocol.value}")
        lines.append(f"Timeout: {tx.timeout_seconds}s")
        lines.append("")
        lines.append("Auto-generated by Midicoder CE.")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from enum import Enum")
        lines.append("from typing import Any, Optional, List")
        lines.append("from sqlalchemy import Column, String, DateTime, Integer, Text, Boolean")
        lines.append("from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column")
        lines.append("import uuid")
        lines.append("")
        lines.append("")

        if tx.protocol.value == "saga":
            lines.append(f"class SagaStep(str, Enum):")
            lines.append(f"    {_TRIPLE_DQ}Saga steps for transaction '{tx.id}'.{_TRIPLE_DQ}")
            for p in tx.participants:
                step_name = p.role.upper().replace(" ", "_")
                lines.append(f"    {step_name} = '{p.role}'")
                lines.append(f"    {step_name}_COMPENSATE = '{p.role}_compensate'")
            lines.append("")
            lines.append("")
            lines.append(f"class {tx.id.replace('-', '_').title().replace('_', '')}Saga:")
            lines.append(f"    {_TRIPLE_DQ}Saga orchestrator for '{tx.id}'.")
            lines.append(f"    Participants: {len(tx.participants)}")
            lines.append(f"    Timeout: {tx.timeout_seconds}s")
            lines.append(f"    {_TRIPLE_DQ}")
            lines.append("")
            lines.append(f"    def __init__(self, db, tenant_id: Optional[str] = None):")
            lines.append(f"        self.db = db")
            lines.append(f"        self.tenant_id = tenant_id")
            lines.append(f"        self.steps: List = []")
            lines.append(f"        self.completed_steps: List = []")
            lines.append("")
            lines.append(f"    async def execute(self) -> bool:")
            lines.append(f"        {_TRIPLE_DQ}Execute saga steps forward; on failure, compensate.{_TRIPLE_DQ}")
            lines.append(f"        for step in self.steps:")
            lines.append(f"            try:")
            lines.append(f"                await step.execute(self.db, self.tenant_id)")
            lines.append(f"                self.completed_steps.append(step)")
            lines.append(f"            except Exception as e:")
            lines.append(f"                await self.compensate(e)")
            lines.append(f"                return False")
            lines.append(f"        return True")
            lines.append("")
            lines.append(f"    async def compensate(self, error: Exception):")
            lines.append(f"        {_TRIPLE_DQ}Execute compensation steps in reverse.{_TRIPLE_DQ}")
            lines.append(f"        for step in reversed(self.completed_steps):")
            lines.append(f"            try:")
            lines.append(f"                await step.compensate(self.db, self.tenant_id)")
            lines.append(f"            except Exception:")
            lines.append(f"                pass  # log and continue compensation chain")

        elif tx.protocol.value == "two_phase_commit":
            lines.append(f"class {tx.id.replace('-', '_').title().replace('_', '')}Coordinator:")
            lines.append(f"    {_TRIPLE_DQ}Two-Phase Commit coordinator for '{tx.id}'.")
            lines.append(f"    {_TRIPLE_DQ}")
            lines.append("")
            lines.append(f"    def __init__(self, db, tenant_id: Optional[str] = None):")
            lines.append(f"        self.db = db")
            lines.append(f"        self.tenant_id = tenant_id")
            lines.append(f"        self.participants = {len(tx.participants)}")
            lines.append("")
            lines.append(f"    async def prepare(self) -> dict[str, bool]:")
            lines.append(f"        {_TRIPLE_DQ}Phase 1: ask all participants to prepare.{_TRIPLE_DQ}")
            lines.append(f"        results = {{}}")
            for p in tx.participants:
                lines.append(f"        results['{p.role}'] = await self._prepare_{p.role.replace(' ', '_')}()")
            lines.append(f"        return results")
            lines.append("")
            lines.append(f"    async def commit(self) -> bool:")
            lines.append(f"        {_TRIPLE_DQ}Phase 2: commit all if all prepared.{_TRIPLE_DQ}")
            lines.append(f"        pass")
            lines.append("")
            lines.append(f"    async def abort(self) -> bool:")
            lines.append(f"        {_TRIPLE_DQ}Phase 2: abort all if any failed.{_TRIPLE_DQ}")
            lines.append(f"        pass")

        else:
            lines.append(f"class {tx.id.replace('-', '_').title().replace('_', '')}Outbox:")
            lines.append(f"    {_TRIPLE_DQ}Outbox pattern for '{tx.id}'.")
            lines.append(f"    {_TRIPLE_DQ}")
            lines.append("")
            lines.append(f"    __tablename__ = 'outbox_{tx.id.replace('-', '_')}'")
            lines.append("")
            lines.append(f"    id: Mapped[str] = mapped_column(primary_key=True)")
            lines.append(f"    aggregate_type: Mapped[str] = mapped_column(nullable=False)")
            lines.append(f"    aggregate_id: Mapped[str] = mapped_column(nullable=False)")
            lines.append(f"    event_type: Mapped[str] = mapped_column(nullable=False)")
            lines.append(f"    payload: Mapped[Optional[str]] = mapped_column(nullable=True)")
            lines.append(f"    published: Mapped[bool] = mapped_column(default=False)")

        lines.extend(["", ""])

        filename = f"transactions/{tx.id.replace('-', '_')}.py"
        return {filename: "\n".join(lines)}

    def emit_jsonb_columns(self, columns: list[JSONBColumn]) -> dict[str, str]:
        """Sinh JSONB column definitions + GIN index + query helpers."""
        lines: list[str] = []
        lines.append(_TRIPLE_DQ)
        lines.append("JSONB Column Helpers — Auto-generated by Midicoder CE.")
        lines.append(_TRIPLE_DQ)
        lines.append("")
        lines.append("from sqlalchemy import Column, Index, text")
        lines.append("from sqlalchemy.dialects.postgresql import JSONB")
        lines.append("from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column")
        lines.append("")
        lines.append("")

        for col in columns:
            lines.append(f"# JSONB column: {col.name}")
            if col.validation_mode.value != "none":
                lines.append(f"# Validation: {col.validation_mode.value}")
            if col.jsonb_indexes:
                lines.append(f"# GIN Index: {len(col.jsonb_indexes)} indexes defined")
            lines.append("")

        lines.append("")
        lines.append("# GIN indexes for JSONB columns")
        for col in columns:
            for idx in col.jsonb_indexes:
                lines.append(f"# CREATE INDEX {idx.name} ON {{table}} USING {idx.index_type.value} ({col.name});")

        lines.append("")
        lines.append("")
        lines.append("def jsonb_path_query(column, path: str):")
        lines.append(f"    {_TRIPLE_DQ}Query JSONB column at path using -> operator.{_TRIPLE_DQ}")
        lines.append("    return text(f\":column {path}\")")
        lines.append("")
        lines.append("")
        lines.append("def jsonb_contains(column, value):")
        lines.append(f"    {_TRIPLE_DQ}Check if JSONB column contains key/value pair.{_TRIPLE_DQ}")
        lines.append("    return text(f\":column @> :value\")")

        return {"jsonb/jsonb_helpers.py": "\n".join(lines)}